"""First-party optional Agent Harness Capabilities."""

from importlib import import_module
from typing import TYPE_CHECKING

from .codeact import CodeActCapability, CodeActConfig
from .context import (
    CompactionCapability,
    CompactionPolicy,
    CompactionSummaryEvent,
    FileContextCapability,
    FileContextConfiguration,
    HandoffCapability,
    HandoffConfiguration,
    RuntimeContextCapability,
    RuntimeContextConfiguration,
    WorkspaceOutlineCapability,
    WorkspaceOutlineConfiguration,
)
from .documents import (
    DocumentAsset,
    DocumentConversionError,
    DocumentConversionRequest,
    DocumentConversionResult,
    DocumentConverter,
    DocumentKind,
    DocumentsCapability,
    DocumentsConfiguration,
    DocumentsRunCapability,
)
from .interaction import (
    AskUserQuestionRequest,
    UserInteractionCapability,
    UserQuestion,
    UserQuestionAnswers,
    UserQuestionOption,
)
from .media import (
    MediaCapability,
    MediaConfiguration,
    MediaKind,
    MediaReader,
    MediaReadError,
    MediaReadRequest,
    MediaResource,
    MediaRunCapability,
)
from .native_image_generation import NativeImageGenerationCapability, NativeImageSaver
from .skills import (
    BoundSkillCatalog,
    BoundSkillCatalogItem,
    FileSkillSource,
    SkillCatalogItem,
    SkillManager,
    SkillMaterializer,
    SkillsCapability,
    SkillSelectionRunCapability,
    SkillSource,
    SkillsPolicy,
)
from .subagents import (
    MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS,
    AsyncDelegateRequest,
    AsyncExecutionView,
    AsyncResumeRequest,
    InlineSubagentCollectionState,
    InlineSubagentState,
    ResolvedDelegationContext,
    SubagentActivitySnapshot,
    SubagentCancelRequest,
    SubagentCancelResult,
    SubagentCapability,
    SubagentDelegationPlan,
    SubagentExecutionView,
    SubagentInfoRequest,
    SubagentInfoResult,
    SubagentOperator,
    SubagentOperatorContext,
    SubagentStatus,
    SubagentSteerRequest,
    SubagentSteerResult,
    SubagentToolCallContext,
    SubagentToolCallSnapshot,
    SubagentToolCallStatus,
    SubagentWaitRequest,
    SubagentWaitResult,
)
from .tool_proxy import ToolProxyCapability, ToolProxyConfig, ToolProxyGroup, ToolProxyPlan, ToolProxySelection
from .tool_review import (
    AgentToolReviewer,
    ToolReviewAssessment,
    ToolReviewConfig,
    ToolReviewer,
    ToolReviewError,
    ToolReviewPolicy,
    ToolReviewRequest,
    ToolReviewResult,
    ToolReviewRule,
    ToolRiskLevel,
)
from .web import (
    WEB_SCRAPE_BACKEND_ENV,
    WEB_SCRAPE_BACKEND_PRIORITY_ENV,
    WEB_SCRAPE_MODE_ENV,
    WEB_SEARCH_BACKEND_ENV,
    WEB_SEARCH_BACKEND_PRIORITY_ENV,
    WEB_SEARCH_CONTEXT_SIZE_ENV,
    WEB_SEARCH_MODE_ENV,
    WebCapability,
    WebClient,
    WebConfiguration,
    WebPolicy,
    WebProviderError,
    WebRequest,
    WebResponse,
    WebRunCapability,
    WebScrapeBackendBinding,
    WebScrapeConfiguration,
    WebScrapeProvider,
    WebScrapeRequest,
    WebScrapeResult,
    WebSearchBackendBinding,
    WebSearchConfiguration,
    WebSearchProvider,
    WebSearchRequest,
    WebSearchResponse,
    WebSearchResult,
)
from .working_state import (
    CreateTask,
    EmbeddedTaskStateCell,
    ProviderTaskCursor,
    Task,
    TaskMutation,
    TaskState,
    TaskStateCell,
    TaskStateError,
    TaskStateRunCapability,
    WorkingState,
    WorkingStateCapability,
    WorkingStateConfiguration,
)

if TYPE_CHECKING:
    from .mem0 import MEM0_API_KEY_ENV, MEM0_BASE_URL_ENV, Mem0Capability, Mem0Scope


def __getattr__(name: str) -> object:
    # Importing any capability must not initialize an unused memory SDK and its
    # vector-store integrations. Preserve the public re-exports on explicit use.
    if name in {"MEM0_API_KEY_ENV", "MEM0_BASE_URL_ENV", "Mem0Capability", "Mem0Scope"}:
        value = vars(import_module(".mem0", __name__))[name]
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS",
    "MEM0_API_KEY_ENV",
    "MEM0_BASE_URL_ENV",
    "WEB_SCRAPE_BACKEND_ENV",
    "WEB_SCRAPE_BACKEND_PRIORITY_ENV",
    "WEB_SCRAPE_MODE_ENV",
    "WEB_SEARCH_BACKEND_ENV",
    "WEB_SEARCH_BACKEND_PRIORITY_ENV",
    "WEB_SEARCH_CONTEXT_SIZE_ENV",
    "WEB_SEARCH_MODE_ENV",
    "AgentToolReviewer",
    "AskUserQuestionRequest",
    "AsyncDelegateRequest",
    "AsyncExecutionView",
    "AsyncResumeRequest",
    "BoundSkillCatalog",
    "BoundSkillCatalogItem",
    "CodeActCapability",
    "CodeActConfig",
    "CompactionCapability",
    "CompactionPolicy",
    "CompactionSummaryEvent",
    "CreateTask",
    "DocumentAsset",
    "DocumentConversionError",
    "DocumentConversionRequest",
    "DocumentConversionResult",
    "DocumentConverter",
    "DocumentKind",
    "DocumentsCapability",
    "DocumentsConfiguration",
    "DocumentsRunCapability",
    "EmbeddedTaskStateCell",
    "FileContextCapability",
    "FileContextConfiguration",
    "FileSkillSource",
    "HandoffCapability",
    "HandoffConfiguration",
    "InlineSubagentCollectionState",
    "InlineSubagentState",
    "MediaCapability",
    "MediaConfiguration",
    "MediaKind",
    "MediaReadError",
    "MediaReadRequest",
    "MediaReader",
    "MediaResource",
    "MediaRunCapability",
    "Mem0Capability",
    "Mem0Scope",
    "NativeImageGenerationCapability",
    "NativeImageSaver",
    "ProviderTaskCursor",
    "ResolvedDelegationContext",
    "RuntimeContextCapability",
    "RuntimeContextConfiguration",
    "SkillCatalogItem",
    "SkillManager",
    "SkillMaterializer",
    "SkillSelectionRunCapability",
    "SkillSource",
    "SkillsCapability",
    "SkillsPolicy",
    "SubagentActivitySnapshot",
    "SubagentCancelRequest",
    "SubagentCancelResult",
    "SubagentCapability",
    "SubagentDelegationPlan",
    "SubagentExecutionView",
    "SubagentInfoRequest",
    "SubagentInfoResult",
    "SubagentOperator",
    "SubagentOperatorContext",
    "SubagentStatus",
    "SubagentSteerRequest",
    "SubagentSteerResult",
    "SubagentToolCallContext",
    "SubagentToolCallSnapshot",
    "SubagentToolCallStatus",
    "SubagentWaitRequest",
    "SubagentWaitResult",
    "Task",
    "TaskMutation",
    "TaskState",
    "TaskStateCell",
    "TaskStateError",
    "TaskStateRunCapability",
    "ToolProxyCapability",
    "ToolProxyConfig",
    "ToolProxyGroup",
    "ToolProxyPlan",
    "ToolProxySelection",
    "ToolReviewAssessment",
    "ToolReviewConfig",
    "ToolReviewError",
    "ToolReviewPolicy",
    "ToolReviewRequest",
    "ToolReviewResult",
    "ToolReviewRule",
    "ToolReviewer",
    "ToolRiskLevel",
    "UserInteractionCapability",
    "UserQuestion",
    "UserQuestionAnswers",
    "UserQuestionOption",
    "WebCapability",
    "WebClient",
    "WebConfiguration",
    "WebPolicy",
    "WebProviderError",
    "WebRequest",
    "WebResponse",
    "WebRunCapability",
    "WebScrapeBackendBinding",
    "WebScrapeConfiguration",
    "WebScrapeProvider",
    "WebScrapeRequest",
    "WebScrapeResult",
    "WebSearchBackendBinding",
    "WebSearchConfiguration",
    "WebSearchProvider",
    "WebSearchRequest",
    "WebSearchResponse",
    "WebSearchResult",
    "WorkingState",
    "WorkingStateCapability",
    "WorkingStateConfiguration",
    "WorkspaceOutlineCapability",
    "WorkspaceOutlineConfiguration",
]
