"""First-party optional Agent Harness Capabilities."""
# ruff: noqa: F401  # `_EXPORTS` owns the surface; these imports serve type checkers.

from typing import TYPE_CHECKING, Any

from a13n_harness._exports import exported_names, load_export

if TYPE_CHECKING:
    from .codeact import CodeActCapability, CodeActConfig
    from .context import (
        CompactionCapability,
        CompactionPolicy,
        CompactionSummaryEvent,
        ContextRestoredEvent,
        FileContextCapability,
        FileContextConfiguration,
        HandoffCapability,
        HandoffConfiguration,
        RuntimeContextCapability,
        RuntimeContextConfiguration,
        WorkspaceOutlineCapability,
        WorkspaceOutlineConfiguration,
    )
    from .documents import (
        DocumentAsset,
        DocumentConversionError,
        DocumentConversionRequest,
        DocumentConversionResult,
        DocumentConverter,
        DocumentKind,
        DocumentsCapability,
        DocumentsConfiguration,
    )
    from .interaction import (
        AskUserQuestionRequest,
        UserInteractionCapability,
        UserQuestion,
        UserQuestionAnswers,
        UserQuestionOption,
    )
    from .memory import (
        DEFAULT_FILE_GUIDE,
        DEFAULT_RECORD_GUIDE,
        FILE_MEMORY_CAPABILITY_ID,
        FILE_TOOL_KEYS,
        RECORD_MEMORY_CAPABILITY_ID,
        RECORD_TOOL_KEYS,
        FileMemoryCapability,
        FileMemoryLimits,
        FileMount,
        FileToolKey,
        MemoryCursors,
        RecordMemoryCapability,
        RecordMemoryLimits,
        RecordMount,
        RecordToolKey,
    )
    from .native_image_generation import NativeImageGenerationCapability, NativeImageSaver
    from .skills import (
        BoundSkillCatalog,
        BoundSkillCatalogItem,
        FileSkillSource,
        SkillCatalogItem,
        SkillManager,
        SkillMaterializer,
        SkillsCapability,
        SkillSource,
        SkillsPolicy,
    )
    from .subagents import (
        MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS,
        AsyncDelegateRequest,
        AsyncExecutionView,
        AsyncResumeRequest,
        InlineSubagentCollectionState,
        InlineSubagentState,
        ResolvedDelegationContext,
        SubagentActivitySnapshot,
        SubagentCancelRequest,
        SubagentCancelResult,
        SubagentCapability,
        SubagentDelegationPlan,
        SubagentExecutionView,
        SubagentInfoRequest,
        SubagentInfoResult,
        SubagentOperator,
        SubagentOperatorContext,
        SubagentStatus,
        SubagentSteerRequest,
        SubagentSteerResult,
        SubagentToolCallContext,
        SubagentToolCallSnapshot,
        SubagentToolCallStatus,
        SubagentWaitRequest,
        SubagentWaitResult,
    )
    from .tool_proxy import ToolProxyCapability, ToolProxyConfig, ToolProxyGroup, ToolProxyPlan, ToolProxySelection
    from .tool_review import (
        AgentToolReviewer,
        ToolReviewAssessment,
        ToolReviewConfig,
        ToolReviewer,
        ToolReviewError,
        ToolReviewPolicy,
        ToolReviewRequest,
        ToolReviewResult,
        ToolReviewRule,
        ToolRiskLevel,
    )
    from .video_url import VideoUrlCapability
    from .web import (
        WEB_SCRAPE_BACKEND_ENV,
        WEB_SCRAPE_BACKEND_PRIORITY_ENV,
        WEB_SCRAPE_MODE_ENV,
        WEB_SEARCH_BACKEND_ENV,
        WEB_SEARCH_BACKEND_PRIORITY_ENV,
        WEB_SEARCH_CONTEXT_SIZE_ENV,
        WEB_SEARCH_MODE_ENV,
        WebBinding,
        WebCapability,
        WebClient,
        WebConfiguration,
        WebDownloadConfiguration,
        WebFetchConfiguration,
        WebPolicy,
        WebProviderError,
        WebRequest,
        WebResponse,
        WebScrapeBackendBinding,
        WebScrapeConfiguration,
        WebScrapeProvider,
        WebScrapeRequest,
        WebScrapeResult,
        WebSearchBackendBinding,
        WebSearchConfiguration,
        WebSearchProvider,
        WebSearchRequest,
        WebSearchResponse,
        WebSearchResult,
    )
    from .working_state import (
        CreateTask,
        EmbeddedTaskStateCell,
        ProviderTaskCursor,
        Task,
        TaskMutation,
        TaskState,
        TaskStateBinding,
        TaskStateCell,
        TaskStateError,
        WorkingState,
        WorkingStateCapability,
        WorkingStateConfiguration,
        WorkingStateObservation,
        WorkingStateObserver,
    )

_EXPORTS = {
    "a13n_harness.capabilities.codeact": (
        "CodeActCapability",
        "CodeActConfig",
    ),
    "a13n_harness.capabilities.context": (
        "CompactionCapability",
        "CompactionPolicy",
        "CompactionSummaryEvent",
        "ContextRestoredEvent",
        "FileContextCapability",
        "FileContextConfiguration",
        "HandoffCapability",
        "HandoffConfiguration",
        "RuntimeContextCapability",
        "RuntimeContextConfiguration",
        "WorkspaceOutlineCapability",
        "WorkspaceOutlineConfiguration",
    ),
    "a13n_harness.capabilities.documents": (
        "DocumentAsset",
        "DocumentConversionError",
        "DocumentConversionRequest",
        "DocumentConversionResult",
        "DocumentConverter",
        "DocumentKind",
        "DocumentsCapability",
        "DocumentsConfiguration",
    ),
    "a13n_harness.capabilities.interaction": (
        "AskUserQuestionRequest",
        "UserInteractionCapability",
        "UserQuestion",
        "UserQuestionAnswers",
        "UserQuestionOption",
    ),
    "a13n_harness.capabilities.video_url": ("VideoUrlCapability",),
    "a13n_harness.capabilities.memory": (
        "DEFAULT_FILE_GUIDE",
        "DEFAULT_RECORD_GUIDE",
        "FILE_MEMORY_CAPABILITY_ID",
        "FILE_TOOL_KEYS",
        "RECORD_MEMORY_CAPABILITY_ID",
        "RECORD_TOOL_KEYS",
        "FileMemoryCapability",
        "FileMemoryLimits",
        "FileMount",
        "FileToolKey",
        "MemoryCursors",
        "RecordMemoryCapability",
        "RecordMemoryLimits",
        "RecordMount",
        "RecordToolKey",
    ),
    "a13n_harness.capabilities.native_image_generation": (
        "NativeImageGenerationCapability",
        "NativeImageSaver",
    ),
    "a13n_harness.capabilities.skills": (
        "BoundSkillCatalog",
        "BoundSkillCatalogItem",
        "FileSkillSource",
        "SkillCatalogItem",
        "SkillManager",
        "SkillMaterializer",
        "SkillSource",
        "SkillsCapability",
        "SkillsPolicy",
    ),
    "a13n_harness.capabilities.subagents": (
        "AsyncDelegateRequest",
        "AsyncExecutionView",
        "AsyncResumeRequest",
        "InlineSubagentCollectionState",
        "InlineSubagentState",
        "MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS",
        "ResolvedDelegationContext",
        "SubagentActivitySnapshot",
        "SubagentCancelRequest",
        "SubagentCancelResult",
        "SubagentCapability",
        "SubagentDelegationPlan",
        "SubagentExecutionView",
        "SubagentInfoRequest",
        "SubagentInfoResult",
        "SubagentOperator",
        "SubagentOperatorContext",
        "SubagentStatus",
        "SubagentSteerRequest",
        "SubagentSteerResult",
        "SubagentToolCallContext",
        "SubagentToolCallSnapshot",
        "SubagentToolCallStatus",
        "SubagentWaitRequest",
        "SubagentWaitResult",
    ),
    "a13n_harness.capabilities.tool_proxy": (
        "ToolProxyCapability",
        "ToolProxyConfig",
        "ToolProxyGroup",
        "ToolProxyPlan",
        "ToolProxySelection",
    ),
    "a13n_harness.capabilities.tool_review": (
        "AgentToolReviewer",
        "ToolReviewAssessment",
        "ToolReviewConfig",
        "ToolReviewError",
        "ToolReviewPolicy",
        "ToolReviewRequest",
        "ToolReviewResult",
        "ToolReviewRule",
        "ToolReviewer",
        "ToolRiskLevel",
    ),
    "a13n_harness.capabilities.web": (
        "WEB_SCRAPE_BACKEND_ENV",
        "WEB_SCRAPE_BACKEND_PRIORITY_ENV",
        "WEB_SCRAPE_MODE_ENV",
        "WEB_SEARCH_BACKEND_ENV",
        "WEB_SEARCH_BACKEND_PRIORITY_ENV",
        "WEB_SEARCH_CONTEXT_SIZE_ENV",
        "WEB_SEARCH_MODE_ENV",
        "WebBinding",
        "WebCapability",
        "WebClient",
        "WebConfiguration",
        "WebDownloadConfiguration",
        "WebFetchConfiguration",
        "WebPolicy",
        "WebProviderError",
        "WebRequest",
        "WebResponse",
        "WebScrapeBackendBinding",
        "WebScrapeConfiguration",
        "WebScrapeProvider",
        "WebScrapeRequest",
        "WebScrapeResult",
        "WebSearchBackendBinding",
        "WebSearchConfiguration",
        "WebSearchProvider",
        "WebSearchRequest",
        "WebSearchResponse",
        "WebSearchResult",
    ),
    "a13n_harness.capabilities.working_state": (
        "CreateTask",
        "EmbeddedTaskStateCell",
        "ProviderTaskCursor",
        "Task",
        "TaskMutation",
        "TaskState",
        "TaskStateBinding",
        "TaskStateCell",
        "TaskStateError",
        "WorkingState",
        "WorkingStateCapability",
        "WorkingStateConfiguration",
        "WorkingStateObservation",
        "WorkingStateObserver",
    ),
}


def __getattr__(name: str) -> Any:
    return load_export(__name__, globals(), _EXPORTS, name)


__all__ = exported_names(_EXPORTS)  # pyright: ignore[reportUnsupportedDunderAll]
