"""First-party optional Agent Harness Capabilities."""

from typing import TYPE_CHECKING, Any

from a13n_harness._exports import load_export

if TYPE_CHECKING:
    from .codeact import CodeActCapability, CodeActConfig
    from .context import (
        CompactionCapability,
        CompactionPolicy,
        CompactionSummaryEvent,
        FileContextCapability,
        FileContextConfiguration,
        HandoffCapability,
        HandoffConfiguration,
        RuntimeContextCapability,
        RuntimeContextConfiguration,
        WorkspaceOutlineCapability,
        WorkspaceOutlineConfiguration,
    )
    from .documents import (
        DocumentAsset,
        DocumentConversionError,
        DocumentConversionRequest,
        DocumentConversionResult,
        DocumentConverter,
        DocumentKind,
        DocumentsCapability,
        DocumentsConfiguration,
    )
    from .interaction import (
        AskUserQuestionRequest,
        UserInteractionCapability,
        UserQuestion,
        UserQuestionAnswers,
        UserQuestionOption,
    )
    from .media import (
        MediaCapability,
        MediaConfiguration,
        MediaKind,
        MediaReader,
        MediaReadError,
        MediaReadRequest,
        MediaResource,
    )
    from .memory import MemoryCapability, MemoryScope
    from .native_image_generation import NativeImageGenerationCapability, NativeImageSaver
    from .skills import (
        BoundSkillCatalog,
        BoundSkillCatalogItem,
        FileSkillSource,
        SkillCatalogItem,
        SkillManager,
        SkillMaterializer,
        SkillsCapability,
        SkillSource,
        SkillsPolicy,
    )
    from .subagents import (
        MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS,
        AsyncDelegateRequest,
        AsyncExecutionView,
        AsyncResumeRequest,
        InlineSubagentCollectionState,
        InlineSubagentState,
        ResolvedDelegationContext,
        SubagentActivitySnapshot,
        SubagentCancelRequest,
        SubagentCancelResult,
        SubagentCapability,
        SubagentDelegationPlan,
        SubagentExecutionView,
        SubagentInfoRequest,
        SubagentInfoResult,
        SubagentOperator,
        SubagentOperatorContext,
        SubagentStatus,
        SubagentSteerRequest,
        SubagentSteerResult,
        SubagentToolCallContext,
        SubagentToolCallSnapshot,
        SubagentToolCallStatus,
        SubagentWaitRequest,
        SubagentWaitResult,
    )
    from .tool_proxy import ToolProxyCapability, ToolProxyConfig, ToolProxyGroup, ToolProxyPlan, ToolProxySelection
    from .tool_review import (
        AgentToolReviewer,
        ToolReviewAssessment,
        ToolReviewConfig,
        ToolReviewer,
        ToolReviewError,
        ToolReviewPolicy,
        ToolReviewRequest,
        ToolReviewResult,
        ToolReviewRule,
        ToolRiskLevel,
    )
    from .web import (
        WEB_SCRAPE_BACKEND_ENV,
        WEB_SCRAPE_BACKEND_PRIORITY_ENV,
        WEB_SCRAPE_MODE_ENV,
        WEB_SEARCH_BACKEND_ENV,
        WEB_SEARCH_BACKEND_PRIORITY_ENV,
        WEB_SEARCH_CONTEXT_SIZE_ENV,
        WEB_SEARCH_MODE_ENV,
        WebBinding,
        WebCapability,
        WebClient,
        WebConfiguration,
        WebDownloadConfiguration,
        WebFetchConfiguration,
        WebPolicy,
        WebProviderError,
        WebRequest,
        WebResponse,
        WebScrapeBackendBinding,
        WebScrapeConfiguration,
        WebScrapeProvider,
        WebScrapeRequest,
        WebScrapeResult,
        WebSearchBackendBinding,
        WebSearchConfiguration,
        WebSearchProvider,
        WebSearchRequest,
        WebSearchResponse,
        WebSearchResult,
    )
    from .working_state import (
        CreateTask,
        EmbeddedTaskStateCell,
        ProviderTaskCursor,
        Task,
        TaskMutation,
        TaskState,
        TaskStateBinding,
        TaskStateCell,
        TaskStateError,
        WorkingState,
        WorkingStateCapability,
        WorkingStateConfiguration,
        WorkingStateObservation,
        WorkingStateObserver,
    )

_EXPORTS = {
    "CodeActCapability": ("a13n_harness.capabilities.codeact", "CodeActCapability"),
    "CodeActConfig": ("a13n_harness.capabilities.codeact", "CodeActConfig"),
    "CompactionCapability": ("a13n_harness.capabilities.context", "CompactionCapability"),
    "CompactionPolicy": ("a13n_harness.capabilities.context", "CompactionPolicy"),
    "CompactionSummaryEvent": ("a13n_harness.capabilities.context", "CompactionSummaryEvent"),
    "FileContextCapability": ("a13n_harness.capabilities.context", "FileContextCapability"),
    "FileContextConfiguration": ("a13n_harness.capabilities.context", "FileContextConfiguration"),
    "HandoffCapability": ("a13n_harness.capabilities.context", "HandoffCapability"),
    "HandoffConfiguration": ("a13n_harness.capabilities.context", "HandoffConfiguration"),
    "RuntimeContextCapability": ("a13n_harness.capabilities.context", "RuntimeContextCapability"),
    "RuntimeContextConfiguration": ("a13n_harness.capabilities.context", "RuntimeContextConfiguration"),
    "WorkspaceOutlineCapability": ("a13n_harness.capabilities.context", "WorkspaceOutlineCapability"),
    "WorkspaceOutlineConfiguration": ("a13n_harness.capabilities.context", "WorkspaceOutlineConfiguration"),
    "DocumentAsset": ("a13n_harness.capabilities.documents", "DocumentAsset"),
    "DocumentConversionError": ("a13n_harness.capabilities.documents", "DocumentConversionError"),
    "DocumentConversionRequest": ("a13n_harness.capabilities.documents", "DocumentConversionRequest"),
    "DocumentConversionResult": ("a13n_harness.capabilities.documents", "DocumentConversionResult"),
    "DocumentConverter": ("a13n_harness.capabilities.documents", "DocumentConverter"),
    "DocumentKind": ("a13n_harness.capabilities.documents", "DocumentKind"),
    "DocumentsCapability": ("a13n_harness.capabilities.documents", "DocumentsCapability"),
    "DocumentsConfiguration": ("a13n_harness.capabilities.documents", "DocumentsConfiguration"),
    "AskUserQuestionRequest": ("a13n_harness.capabilities.interaction", "AskUserQuestionRequest"),
    "UserInteractionCapability": ("a13n_harness.capabilities.interaction", "UserInteractionCapability"),
    "UserQuestion": ("a13n_harness.capabilities.interaction", "UserQuestion"),
    "UserQuestionAnswers": ("a13n_harness.capabilities.interaction", "UserQuestionAnswers"),
    "UserQuestionOption": ("a13n_harness.capabilities.interaction", "UserQuestionOption"),
    "MediaCapability": ("a13n_harness.capabilities.media", "MediaCapability"),
    "MediaConfiguration": ("a13n_harness.capabilities.media", "MediaConfiguration"),
    "MediaKind": ("a13n_harness.capabilities.media", "MediaKind"),
    "MediaReader": ("a13n_harness.capabilities.media", "MediaReader"),
    "MediaReadError": ("a13n_harness.capabilities.media", "MediaReadError"),
    "MediaReadRequest": ("a13n_harness.capabilities.media", "MediaReadRequest"),
    "MediaResource": ("a13n_harness.capabilities.media", "MediaResource"),
    "MemoryCapability": ("a13n_harness.capabilities.memory", "MemoryCapability"),
    "MemoryScope": ("a13n_harness.capabilities.memory", "MemoryScope"),
    "NativeImageGenerationCapability": (
        "a13n_harness.capabilities.native_image_generation",
        "NativeImageGenerationCapability",
    ),
    "NativeImageSaver": ("a13n_harness.capabilities.native_image_generation", "NativeImageSaver"),
    "BoundSkillCatalog": ("a13n_harness.capabilities.skills", "BoundSkillCatalog"),
    "BoundSkillCatalogItem": ("a13n_harness.capabilities.skills", "BoundSkillCatalogItem"),
    "FileSkillSource": ("a13n_harness.capabilities.skills", "FileSkillSource"),
    "SkillCatalogItem": ("a13n_harness.capabilities.skills", "SkillCatalogItem"),
    "SkillManager": ("a13n_harness.capabilities.skills", "SkillManager"),
    "SkillMaterializer": ("a13n_harness.capabilities.skills", "SkillMaterializer"),
    "SkillsCapability": ("a13n_harness.capabilities.skills", "SkillsCapability"),
    "SkillSource": ("a13n_harness.capabilities.skills", "SkillSource"),
    "SkillsPolicy": ("a13n_harness.capabilities.skills", "SkillsPolicy"),
    "MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS": ("a13n_harness.capabilities.subagents", "MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS"),
    "AsyncDelegateRequest": ("a13n_harness.capabilities.subagents", "AsyncDelegateRequest"),
    "AsyncExecutionView": ("a13n_harness.capabilities.subagents", "AsyncExecutionView"),
    "AsyncResumeRequest": ("a13n_harness.capabilities.subagents", "AsyncResumeRequest"),
    "InlineSubagentCollectionState": ("a13n_harness.capabilities.subagents", "InlineSubagentCollectionState"),
    "InlineSubagentState": ("a13n_harness.capabilities.subagents", "InlineSubagentState"),
    "ResolvedDelegationContext": ("a13n_harness.capabilities.subagents", "ResolvedDelegationContext"),
    "SubagentActivitySnapshot": ("a13n_harness.capabilities.subagents", "SubagentActivitySnapshot"),
    "SubagentCancelRequest": ("a13n_harness.capabilities.subagents", "SubagentCancelRequest"),
    "SubagentCancelResult": ("a13n_harness.capabilities.subagents", "SubagentCancelResult"),
    "SubagentCapability": ("a13n_harness.capabilities.subagents", "SubagentCapability"),
    "SubagentDelegationPlan": ("a13n_harness.capabilities.subagents", "SubagentDelegationPlan"),
    "SubagentExecutionView": ("a13n_harness.capabilities.subagents", "SubagentExecutionView"),
    "SubagentInfoRequest": ("a13n_harness.capabilities.subagents", "SubagentInfoRequest"),
    "SubagentInfoResult": ("a13n_harness.capabilities.subagents", "SubagentInfoResult"),
    "SubagentOperator": ("a13n_harness.capabilities.subagents", "SubagentOperator"),
    "SubagentOperatorContext": ("a13n_harness.capabilities.subagents", "SubagentOperatorContext"),
    "SubagentStatus": ("a13n_harness.capabilities.subagents", "SubagentStatus"),
    "SubagentSteerRequest": ("a13n_harness.capabilities.subagents", "SubagentSteerRequest"),
    "SubagentSteerResult": ("a13n_harness.capabilities.subagents", "SubagentSteerResult"),
    "SubagentToolCallContext": ("a13n_harness.capabilities.subagents", "SubagentToolCallContext"),
    "SubagentToolCallSnapshot": ("a13n_harness.capabilities.subagents", "SubagentToolCallSnapshot"),
    "SubagentToolCallStatus": ("a13n_harness.capabilities.subagents", "SubagentToolCallStatus"),
    "SubagentWaitRequest": ("a13n_harness.capabilities.subagents", "SubagentWaitRequest"),
    "SubagentWaitResult": ("a13n_harness.capabilities.subagents", "SubagentWaitResult"),
    "ToolProxyCapability": ("a13n_harness.capabilities.tool_proxy", "ToolProxyCapability"),
    "ToolProxyConfig": ("a13n_harness.capabilities.tool_proxy", "ToolProxyConfig"),
    "ToolProxyGroup": ("a13n_harness.capabilities.tool_proxy", "ToolProxyGroup"),
    "ToolProxyPlan": ("a13n_harness.capabilities.tool_proxy", "ToolProxyPlan"),
    "ToolProxySelection": ("a13n_harness.capabilities.tool_proxy", "ToolProxySelection"),
    "AgentToolReviewer": ("a13n_harness.capabilities.tool_review", "AgentToolReviewer"),
    "ToolReviewAssessment": ("a13n_harness.capabilities.tool_review", "ToolReviewAssessment"),
    "ToolReviewConfig": ("a13n_harness.capabilities.tool_review", "ToolReviewConfig"),
    "ToolReviewer": ("a13n_harness.capabilities.tool_review", "ToolReviewer"),
    "ToolReviewError": ("a13n_harness.capabilities.tool_review", "ToolReviewError"),
    "ToolReviewPolicy": ("a13n_harness.capabilities.tool_review", "ToolReviewPolicy"),
    "ToolReviewRequest": ("a13n_harness.capabilities.tool_review", "ToolReviewRequest"),
    "ToolReviewResult": ("a13n_harness.capabilities.tool_review", "ToolReviewResult"),
    "ToolReviewRule": ("a13n_harness.capabilities.tool_review", "ToolReviewRule"),
    "ToolRiskLevel": ("a13n_harness.capabilities.tool_review", "ToolRiskLevel"),
    "WEB_SCRAPE_BACKEND_ENV": ("a13n_harness.capabilities.web", "WEB_SCRAPE_BACKEND_ENV"),
    "WEB_SCRAPE_BACKEND_PRIORITY_ENV": ("a13n_harness.capabilities.web", "WEB_SCRAPE_BACKEND_PRIORITY_ENV"),
    "WEB_SCRAPE_MODE_ENV": ("a13n_harness.capabilities.web", "WEB_SCRAPE_MODE_ENV"),
    "WEB_SEARCH_BACKEND_ENV": ("a13n_harness.capabilities.web", "WEB_SEARCH_BACKEND_ENV"),
    "WEB_SEARCH_BACKEND_PRIORITY_ENV": ("a13n_harness.capabilities.web", "WEB_SEARCH_BACKEND_PRIORITY_ENV"),
    "WEB_SEARCH_CONTEXT_SIZE_ENV": ("a13n_harness.capabilities.web", "WEB_SEARCH_CONTEXT_SIZE_ENV"),
    "WEB_SEARCH_MODE_ENV": ("a13n_harness.capabilities.web", "WEB_SEARCH_MODE_ENV"),
    "WebBinding": ("a13n_harness.capabilities.web", "WebBinding"),
    "WebCapability": ("a13n_harness.capabilities.web", "WebCapability"),
    "WebClient": ("a13n_harness.capabilities.web", "WebClient"),
    "WebConfiguration": ("a13n_harness.capabilities.web", "WebConfiguration"),
    "WebDownloadConfiguration": ("a13n_harness.capabilities.web", "WebDownloadConfiguration"),
    "WebFetchConfiguration": ("a13n_harness.capabilities.web", "WebFetchConfiguration"),
    "WebPolicy": ("a13n_harness.capabilities.web", "WebPolicy"),
    "WebProviderError": ("a13n_harness.capabilities.web", "WebProviderError"),
    "WebRequest": ("a13n_harness.capabilities.web", "WebRequest"),
    "WebResponse": ("a13n_harness.capabilities.web", "WebResponse"),
    "WebScrapeBackendBinding": ("a13n_harness.capabilities.web", "WebScrapeBackendBinding"),
    "WebScrapeConfiguration": ("a13n_harness.capabilities.web", "WebScrapeConfiguration"),
    "WebScrapeProvider": ("a13n_harness.capabilities.web", "WebScrapeProvider"),
    "WebScrapeRequest": ("a13n_harness.capabilities.web", "WebScrapeRequest"),
    "WebScrapeResult": ("a13n_harness.capabilities.web", "WebScrapeResult"),
    "WebSearchBackendBinding": ("a13n_harness.capabilities.web", "WebSearchBackendBinding"),
    "WebSearchConfiguration": ("a13n_harness.capabilities.web", "WebSearchConfiguration"),
    "WebSearchProvider": ("a13n_harness.capabilities.web", "WebSearchProvider"),
    "WebSearchRequest": ("a13n_harness.capabilities.web", "WebSearchRequest"),
    "WebSearchResponse": ("a13n_harness.capabilities.web", "WebSearchResponse"),
    "WebSearchResult": ("a13n_harness.capabilities.web", "WebSearchResult"),
    "CreateTask": ("a13n_harness.capabilities.working_state", "CreateTask"),
    "EmbeddedTaskStateCell": ("a13n_harness.capabilities.working_state", "EmbeddedTaskStateCell"),
    "ProviderTaskCursor": ("a13n_harness.capabilities.working_state", "ProviderTaskCursor"),
    "Task": ("a13n_harness.capabilities.working_state", "Task"),
    "TaskMutation": ("a13n_harness.capabilities.working_state", "TaskMutation"),
    "TaskState": ("a13n_harness.capabilities.working_state", "TaskState"),
    "TaskStateBinding": ("a13n_harness.capabilities.working_state", "TaskStateBinding"),
    "TaskStateCell": ("a13n_harness.capabilities.working_state", "TaskStateCell"),
    "TaskStateError": ("a13n_harness.capabilities.working_state", "TaskStateError"),
    "WorkingState": ("a13n_harness.capabilities.working_state", "WorkingState"),
    "WorkingStateCapability": ("a13n_harness.capabilities.working_state", "WorkingStateCapability"),
    "WorkingStateConfiguration": ("a13n_harness.capabilities.working_state", "WorkingStateConfiguration"),
    "WorkingStateObservation": ("a13n_harness.capabilities.working_state", "WorkingStateObservation"),
    "WorkingStateObserver": ("a13n_harness.capabilities.working_state", "WorkingStateObserver"),
}


def __getattr__(name: str) -> Any:
    return load_export(__name__, globals(), _EXPORTS, name)


__all__ = [
    "MAX_SUBAGENT_ACTIVITY_OUTPUT_CHARS",
    "WEB_SCRAPE_BACKEND_ENV",
    "WEB_SCRAPE_BACKEND_PRIORITY_ENV",
    "WEB_SCRAPE_MODE_ENV",
    "WEB_SEARCH_BACKEND_ENV",
    "WEB_SEARCH_BACKEND_PRIORITY_ENV",
    "WEB_SEARCH_CONTEXT_SIZE_ENV",
    "WEB_SEARCH_MODE_ENV",
    "AgentToolReviewer",
    "AskUserQuestionRequest",
    "AsyncDelegateRequest",
    "AsyncExecutionView",
    "AsyncResumeRequest",
    "BoundSkillCatalog",
    "BoundSkillCatalogItem",
    "CodeActCapability",
    "CodeActConfig",
    "CompactionCapability",
    "CompactionPolicy",
    "CompactionSummaryEvent",
    "CreateTask",
    "DocumentAsset",
    "DocumentConversionError",
    "DocumentConversionRequest",
    "DocumentConversionResult",
    "DocumentConverter",
    "DocumentKind",
    "DocumentsCapability",
    "DocumentsConfiguration",
    "EmbeddedTaskStateCell",
    "FileContextCapability",
    "FileContextConfiguration",
    "FileSkillSource",
    "HandoffCapability",
    "HandoffConfiguration",
    "InlineSubagentCollectionState",
    "InlineSubagentState",
    "MediaCapability",
    "MediaConfiguration",
    "MediaKind",
    "MediaReadError",
    "MediaReadRequest",
    "MediaReader",
    "MediaResource",
    "MemoryCapability",
    "MemoryScope",
    "NativeImageGenerationCapability",
    "NativeImageSaver",
    "ProviderTaskCursor",
    "ResolvedDelegationContext",
    "RuntimeContextCapability",
    "RuntimeContextConfiguration",
    "SkillCatalogItem",
    "SkillManager",
    "SkillMaterializer",
    "SkillSource",
    "SkillsCapability",
    "SkillsPolicy",
    "SubagentActivitySnapshot",
    "SubagentCancelRequest",
    "SubagentCancelResult",
    "SubagentCapability",
    "SubagentDelegationPlan",
    "SubagentExecutionView",
    "SubagentInfoRequest",
    "SubagentInfoResult",
    "SubagentOperator",
    "SubagentOperatorContext",
    "SubagentStatus",
    "SubagentSteerRequest",
    "SubagentSteerResult",
    "SubagentToolCallContext",
    "SubagentToolCallSnapshot",
    "SubagentToolCallStatus",
    "SubagentWaitRequest",
    "SubagentWaitResult",
    "Task",
    "TaskMutation",
    "TaskState",
    "TaskStateBinding",
    "TaskStateCell",
    "TaskStateError",
    "ToolProxyCapability",
    "ToolProxyConfig",
    "ToolProxyGroup",
    "ToolProxyPlan",
    "ToolProxySelection",
    "ToolReviewAssessment",
    "ToolReviewConfig",
    "ToolReviewError",
    "ToolReviewPolicy",
    "ToolReviewRequest",
    "ToolReviewResult",
    "ToolReviewRule",
    "ToolReviewer",
    "ToolRiskLevel",
    "UserInteractionCapability",
    "UserQuestion",
    "UserQuestionAnswers",
    "UserQuestionOption",
    "WebBinding",
    "WebCapability",
    "WebClient",
    "WebConfiguration",
    "WebDownloadConfiguration",
    "WebFetchConfiguration",
    "WebPolicy",
    "WebProviderError",
    "WebRequest",
    "WebResponse",
    "WebScrapeBackendBinding",
    "WebScrapeConfiguration",
    "WebScrapeProvider",
    "WebScrapeRequest",
    "WebScrapeResult",
    "WebSearchBackendBinding",
    "WebSearchConfiguration",
    "WebSearchProvider",
    "WebSearchRequest",
    "WebSearchResponse",
    "WebSearchResult",
    "WorkingState",
    "WorkingStateCapability",
    "WorkingStateConfiguration",
    "WorkingStateObservation",
    "WorkingStateObserver",
    "WorkspaceOutlineCapability",
    "WorkspaceOutlineConfiguration",
]
