# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Final, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, model_validator

from .models import EIPError, Identifier

EIP_PROTOCOL_VERSION: Final = "0.1"
EIP_PROTOCOL_MAJOR: Final = 0
EIP_PROTOCOL_MINOR: Final = 1
EIP_PROTO_PACKAGE: Final = "a13n.agent_envd.eip.v1"
EIP_DESCRIPTOR_SHA256: Final = "7a3f4a5a6abcfbd1d15c50a18e9d215b968a26732265209d073d5e9ee9b9eecb"

type JsonRpcId = StrictStr | Annotated[StrictInt, Field(ge=-(2**63), le=2**63 - 1)]


class JsonRpcEnvelope(BaseModel):
    model_config = ConfigDict(extra="ignore", frozen=True)
    eip_session: Identifier | None = None

    @model_validator(mode="before")
    @classmethod
    def _reject_reserved_extensions(cls, value: object) -> object:
        if isinstance(value, dict):
            unknown = set(value) - set(cls.model_fields)
            reserved = sorted(name for name in unknown if isinstance(name, str) and name.startswith("eip_"))
            if reserved:
                raise ValueError("unknown reserved JSON-RPC field: {reserved[0]}")
        return value


class JsonRpcRequest(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    method: StrictStr
    params: dict[str, object]


class JsonRpcSuccessResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    result: dict[str, object]


class JsonRpcErrorResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId | None
    error: EIPError
