"""Foundation Connector domain and trusted Provider extension boundary."""

from .capability import ConnectorAttemptAuthorizer, ConnectorCapabilityClaims, ConnectorCapabilityCodec
from .client import build_connector_mcp_client
from .domain import (
    AcceptedTriggerSource,
    AgentConnectorDeclaration,
    Connection,
    ConnectionAccount,
    ConnectionSetupReceipt,
    ConnectionStatus,
    Connector,
    ConnectorCreateResult,
    ConnectorEventTriggerSource,
    ConnectorProviderContractLock,
    ConnectorRevision,
    ConnectorRevisionCreateResult,
    ConnectorRunSelection,
    CreateConnector,
    CreateConnectorRevision,
    CreateTrigger,
    PrincipalRef,
    ScheduleTriggerSource,
    StartConnectionSetup,
    Trigger,
    TriggerOccurrenceReceipt,
    TriggerStatus,
    UpdateConnection,
    UpdateConnector,
    UpdateTrigger,
)
from .errors import (
    ConnectorError,
    ConnectorProviderCapabilityError,
    ConnectorProviderError,
    ConnectorReauthorizationRequired,
)
from .mcp import (
    AttemptConnectorMCPAuthenticator,
    ConnectorMCPGateway,
    ConnectorMCPInvocation,
    ConnectorMCPRequestAuthenticator,
    StandardConnectorMCPAuthenticator,
)
from .occurrence import TriggerIngressService, TriggerRunAcceptor
from .operations import ConnectorProviderOperations, LocalConnectorProviderOperations
from .provider import (
    ConnectorConnectionProvider,
    ConnectorEventProvider,
    ConnectorPollingProvider,
    ConnectorProvider,
    ConnectorProviderAccount,
    ConnectorProviderCapabilities,
    ConnectorProviderConnection,
    ConnectorProviderConnectionResult,
    ConnectorProviderContext,
    ConnectorProviderEvent,
    ConnectorProviderEventSourceResult,
    ConnectorProviderEventType,
    ConnectorProviderMetadata,
    ConnectorProviderSecret,
    ConnectorProviderSetupResult,
    ConnectorProviderTool,
    ConnectorProviderToolResult,
    ConnectorToolProvider,
    ConnectorWebhookProvider,
)
from .registry import (
    CONNECTOR_PROVIDER_ENTRY_POINT_GROUP,
    ConnectorProviderCatalog,
    ConnectorProviderReference,
    ConnectorProviderRegistration,
    ConnectorProviderTrust,
    build_connector_provider_catalog,
    discover_connector_provider_references,
)
from .runtime import ConnectorInvocationAuthorizer, ConnectorProviderRuntime, freeze_provider_tools
from .secrets import DatabaseConnectorSecretStore
from .service import ConnectionSecretStore, ConnectionService, ConnectorService, resolve_connection
from .setup import ConnectionSetupService, ConnectionSetupStateProtector
from .transport import RemoteConnectorProviderOperations, create_connector_provider_operations_app
from .trigger import AgentTriggerTargetValidator, TriggerSecretStore, TriggerService

__all__ = [
    "CONNECTOR_PROVIDER_ENTRY_POINT_GROUP",
    "AcceptedTriggerSource",
    "AgentConnectorDeclaration",
    "AgentTriggerTargetValidator",
    "AttemptConnectorMCPAuthenticator",
    "Connection",
    "ConnectionAccount",
    "ConnectionSecretStore",
    "ConnectionService",
    "ConnectionSetupReceipt",
    "ConnectionSetupService",
    "ConnectionSetupStateProtector",
    "ConnectionStatus",
    "Connector",
    "ConnectorAttemptAuthorizer",
    "ConnectorCapabilityClaims",
    "ConnectorCapabilityCodec",
    "ConnectorConnectionProvider",
    "ConnectorCreateResult",
    "ConnectorError",
    "ConnectorEventProvider",
    "ConnectorEventTriggerSource",
    "ConnectorInvocationAuthorizer",
    "ConnectorMCPGateway",
    "ConnectorMCPInvocation",
    "ConnectorMCPRequestAuthenticator",
    "ConnectorPollingProvider",
    "ConnectorProvider",
    "ConnectorProviderAccount",
    "ConnectorProviderCapabilities",
    "ConnectorProviderCapabilityError",
    "ConnectorProviderCatalog",
    "ConnectorProviderConnection",
    "ConnectorProviderConnectionResult",
    "ConnectorProviderContext",
    "ConnectorProviderContractLock",
    "ConnectorProviderError",
    "ConnectorProviderEvent",
    "ConnectorProviderEventSourceResult",
    "ConnectorProviderEventType",
    "ConnectorProviderMetadata",
    "ConnectorProviderOperations",
    "ConnectorProviderReference",
    "ConnectorProviderRegistration",
    "ConnectorProviderRuntime",
    "ConnectorProviderSecret",
    "ConnectorProviderSetupResult",
    "ConnectorProviderTool",
    "ConnectorProviderToolResult",
    "ConnectorProviderTrust",
    "ConnectorReauthorizationRequired",
    "ConnectorRevision",
    "ConnectorRevisionCreateResult",
    "ConnectorRunSelection",
    "ConnectorService",
    "ConnectorToolProvider",
    "ConnectorWebhookProvider",
    "CreateConnector",
    "CreateConnectorRevision",
    "CreateTrigger",
    "DatabaseConnectorSecretStore",
    "LocalConnectorProviderOperations",
    "PrincipalRef",
    "RemoteConnectorProviderOperations",
    "ScheduleTriggerSource",
    "StandardConnectorMCPAuthenticator",
    "StartConnectionSetup",
    "Trigger",
    "TriggerIngressService",
    "TriggerOccurrenceReceipt",
    "TriggerRunAcceptor",
    "TriggerSecretStore",
    "TriggerService",
    "TriggerStatus",
    "UpdateConnection",
    "UpdateConnector",
    "UpdateTrigger",
    "build_connector_mcp_client",
    "build_connector_provider_catalog",
    "create_connector_provider_operations_app",
    "discover_connector_provider_references",
    "freeze_provider_tools",
    "resolve_connection",
]
