"""Foundation Connector domain and trusted Provider extension boundary."""

from .domain import (
    AcceptedTriggerSource,
    AgentConnectorDeclaration,
    Connection,
    ConnectionAccount,
    ConnectionSetupReceipt,
    ConnectionStatus,
    Connector,
    ConnectorCreateResult,
    ConnectorEventTriggerSource,
    ConnectorProviderDependencyLock,
    ConnectorRevision,
    ConnectorRevisionCreateResult,
    ConnectorTurnSelection,
    CreateConnector,
    CreateConnectorRevision,
    CreateTrigger,
    FrozenConnectorTool,
    PrincipalRef,
    ScheduleTriggerSource,
    StartConnectionSetup,
    Trigger,
    TriggerOccurrenceReceipt,
    TriggerStatus,
    UpdateConnection,
    UpdateConnector,
    UpdateTrigger,
)
from .errors import (
    ConnectorError,
    ConnectorProviderCapabilityError,
    ConnectorProviderError,
    ConnectorReauthorizationRequired,
)
from .occurrence import TriggerIngressService, TriggerTurnAcceptor
from .provider import (
    ConnectorProvider,
    ConnectorProviderAccount,
    ConnectorProviderCapabilities,
    ConnectorProviderConnection,
    ConnectorProviderConnectionResult,
    ConnectorProviderContext,
    ConnectorProviderEvent,
    ConnectorProviderEventSourceResult,
    ConnectorProviderEventType,
    ConnectorProviderMetadata,
    ConnectorProviderSecret,
    ConnectorProviderSetupResult,
    ConnectorProviderTool,
    ConnectorProviderToolResult,
)
from .registry import (
    CONNECTOR_PROVIDER_ENTRY_POINT_GROUP,
    ConnectorProviderCatalog,
    ConnectorProviderReference,
    ConnectorProviderRegistration,
    ConnectorProviderTrust,
    build_connector_provider_catalog,
    discover_connector_provider_references,
)
from .runtime import ConnectorRunAuthorizer, ConnectorToolRuntime
from .service import ConnectionSecretStore, ConnectionService, ConnectorService, resolve_connection
from .setup import ConnectionSetupService, ConnectionSetupStateProtector
from .toolset import ConnectorManagedToolset
from .trigger import AgentTriggerTargetValidator, TriggerSecretStore, TriggerService

__all__ = [
    "CONNECTOR_PROVIDER_ENTRY_POINT_GROUP",
    "AcceptedTriggerSource",
    "AgentConnectorDeclaration",
    "AgentTriggerTargetValidator",
    "Connection",
    "ConnectionAccount",
    "ConnectionSecretStore",
    "ConnectionService",
    "ConnectionSetupReceipt",
    "ConnectionSetupService",
    "ConnectionSetupStateProtector",
    "ConnectionStatus",
    "Connector",
    "ConnectorCreateResult",
    "ConnectorError",
    "ConnectorEventTriggerSource",
    "ConnectorManagedToolset",
    "ConnectorProvider",
    "ConnectorProviderAccount",
    "ConnectorProviderCapabilities",
    "ConnectorProviderCapabilityError",
    "ConnectorProviderCatalog",
    "ConnectorProviderConnection",
    "ConnectorProviderConnectionResult",
    "ConnectorProviderContext",
    "ConnectorProviderDependencyLock",
    "ConnectorProviderError",
    "ConnectorProviderEvent",
    "ConnectorProviderEventSourceResult",
    "ConnectorProviderEventType",
    "ConnectorProviderMetadata",
    "ConnectorProviderReference",
    "ConnectorProviderRegistration",
    "ConnectorProviderSecret",
    "ConnectorProviderSetupResult",
    "ConnectorProviderTool",
    "ConnectorProviderToolResult",
    "ConnectorProviderTrust",
    "ConnectorReauthorizationRequired",
    "ConnectorRevision",
    "ConnectorRevisionCreateResult",
    "ConnectorRunAuthorizer",
    "ConnectorService",
    "ConnectorToolRuntime",
    "ConnectorTurnSelection",
    "CreateConnector",
    "CreateConnectorRevision",
    "CreateTrigger",
    "FrozenConnectorTool",
    "PrincipalRef",
    "ScheduleTriggerSource",
    "StartConnectionSetup",
    "Trigger",
    "TriggerIngressService",
    "TriggerOccurrenceReceipt",
    "TriggerSecretStore",
    "TriggerService",
    "TriggerStatus",
    "TriggerTurnAcceptor",
    "UpdateConnection",
    "UpdateConnector",
    "UpdateTrigger",
    "build_connector_provider_catalog",
    "discover_connector_provider_references",
    "resolve_connection",
]
