"""add sessions environments runs and events.

Revision ID: 4cc465468a88
Revises: dadd6e6c8d41
Create Date: 2026-08-27 14:04:19.399520+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4cc465468a88"
down_revision: str | Sequence[str] | None = "dadd6e6c8d41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host_environment_resource",
        sa.Column("host_resource_id", sa.String(length=80), nullable=False),
        sa.Column("provider_key", sa.String(length=128), nullable=False),
        sa.Column("provider_schema_version", sa.String(length=64), nullable=False),
        sa.Column("provider_spec_digest", sa.String(length=64), nullable=False),
        sa.Column("provider_parameters_json", sa.Text(), nullable=False),
        sa.Column("resource_allocation", sa.String(length=32), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=32), nullable=False),
        sa.Column("operation_fence", sa.Integer(), nullable=False),
        sa.Column("selected_provider_state_digest", sa.String(length=64), nullable=True),
        sa.Column("last_operation_id", sa.String(length=128), nullable=True),
        sa.Column("last_operation_action", sa.String(length=16), nullable=True),
        sa.Column("last_operation_attempt", sa.Integer(), nullable=True),
        sa.Column("failure_json", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_state IN ('unprovisioned', 'creating', 'available', 'pausing', 'paused', 'resuming', 'destroying', 'destroyed', 'missing', 'unknown', 'failed')",
            name=op.f("ck_host_environment_resource_lifecycle_state"),
        ),
        sa.CheckConstraint(
            "resource_allocation IN ('single_from_spec', 'multiple_from_spec')",
            name=op.f("ck_host_environment_resource_resource_allocation"),
        ),
        sa.ForeignKeyConstraint(
            ["selected_provider_state_digest"],
            ["immutable_object.logical_digest"],
            name=op.f("fk_host_environment_resource_selected_provider_state_digest_immutable_object"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("host_resource_id", name=op.f("pk_host_environment_resource")),
    )
    with op.batch_alter_table("host_environment_resource", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_host_environment_resource_lifecycle_state"), ["lifecycle_state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_host_environment_resource_provider_key"), ["provider_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_host_environment_resource_provider_spec_digest"), ["provider_spec_digest"], unique=False
        )

    op.create_table(
        "local_session",
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("creation_request_id", sa.String(length=128), nullable=False),
        sa.Column("root_thread_id", sa.String(length=128), nullable=True),
        sa.Column("lifecycle_state", sa.String(length=32), nullable=False),
        sa.Column("lifecycle_failure_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("control_version", sa.Integer(), nullable=False),
        sa.Column("agent_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("environment_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("skill_selections_json", sa.Text(), nullable=False),
        sa.Column("parent_fork_json", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "lifecycle_state IN ('provisioning', 'ready', 'blocked', 'deleting', 'cleanup_pending', 'deleted')",
            name=op.f("ck_local_session_lifecycle_state"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_snapshot_id"],
            ["composition_snapshot.snapshot_id"],
            name=op.f("fk_local_session_agent_snapshot_id_composition_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["environment_snapshot_id"],
            ["composition_snapshot.snapshot_id"],
            name=op.f("fk_local_session_environment_snapshot_id_composition_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["root_thread_id"],
            ["session_thread.thread_id"],
            name=op.f("fk_local_session_root_thread_id_session_thread"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_local_session")),
        sa.UniqueConstraint("creation_request_id", name=op.f("uq_local_session_creation_request_id")),
        sa.UniqueConstraint("root_thread_id", name=op.f("uq_local_session_root_thread_id")),
    )
    with op.batch_alter_table("local_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_local_session_archived_at"), ["archived_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_local_session_lifecycle_state"), ["lifecycle_state"], unique=False)
        batch_op.create_index(batch_op.f("ix_local_session_pinned"), ["pinned"], unique=False)
        batch_op.create_index(batch_op.f("ix_local_session_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "event_segment",
        sa.Column("segment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("first_sequence", sa.Integer(), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("previous_segment_digest", sa.String(length=64), nullable=True),
        sa.Column("logical_digest", sa.String(length=64), nullable=False),
        sa.Column("relative_path", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["local_session.session_id"],
            name=op.f("fk_event_segment_session_id_local_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("segment_id", name=op.f("pk_event_segment")),
        sa.UniqueConstraint("logical_digest", name="logical_identity"),
        sa.UniqueConstraint("relative_path", name=op.f("uq_event_segment_relative_path")),
        sa.UniqueConstraint("session_id", "first_sequence", name="range_start"),
        sa.UniqueConstraint("session_id", "last_sequence", name="range_end"),
    )
    with op.batch_alter_table("event_segment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_segment_session_id"), ["session_id"], unique=False)

    op.create_table(
        "item_projection",
        sa.Column("projection_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("turn_id", sa.String(length=80), nullable=True),
        sa.Column("item_id", sa.String(length=128), nullable=False),
        sa.Column("item_kind", sa.String(length=64), nullable=False),
        sa.Column("first_sequence", sa.Integer(), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("summary_json", sa.Text(), nullable=False),
        sa.Column("searchable_text", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["local_session.session_id"],
            name=op.f("fk_item_projection_session_id_local_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("projection_id", name=op.f("pk_item_projection")),
        sa.UniqueConstraint("session_id", "item_id", name="session_item"),
    )
    with op.batch_alter_table("item_projection", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_projection_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_item_projection_thread_id"), ["thread_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_item_projection_turn_id"), ["turn_id"], unique=False)

    op.create_table(
        "session_environment_assignment",
        sa.Column("assignment_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("mount_name", sa.String(length=128), nullable=False),
        sa.Column("model_alias", sa.String(length=63), nullable=False),
        sa.Column("permission_ceiling_json", sa.Text(), nullable=False),
        sa.Column("scope_key", sa.String(length=128), nullable=False),
        sa.Column("host_resource_id", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_resource_id"],
            ["host_environment_resource.host_resource_id"],
            name=op.f("fk_session_environment_assignment_host_resource_id_host_environment_resource"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["local_session.session_id"],
            name=op.f("fk_session_environment_assignment_session_id_local_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("assignment_id", name=op.f("pk_session_environment_assignment")),
        sa.UniqueConstraint("session_id", "mount_name", "scope_key", name="scope_mount"),
    )
    with op.batch_alter_table("session_environment_assignment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_environment_assignment_host_resource_id"), ["host_resource_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_session_environment_assignment_session_id"), ["session_id"], unique=False)

    op.create_table(
        "session_presentation",
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.Column("retention_generation", sa.Integer(), nullable=False),
        sa.Column("projection_watermark", sa.Integer(), nullable=False),
        sa.Column("last_segment_digest", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["local_session.session_id"],
            name=op.f("fk_session_presentation_session_id_local_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_presentation")),
    )
    op.create_table(
        "session_thread",
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("root_ordinal", sa.Integer(), nullable=False),
        sa.Column("commit_version", sa.Integer(), nullable=False),
        sa.Column("queue_version", sa.Integer(), nullable=False),
        sa.Column("selected_checkpoint_id", sa.String(length=80), nullable=True),
        sa.Column("active_turn_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_turn_id"],
            ["thread_turn.turn_id"],
            name=op.f("fk_session_thread_active_turn_id_thread_turn"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["selected_checkpoint_id"],
            ["thread_checkpoint.checkpoint_id"],
            name=op.f("fk_session_thread_selected_checkpoint_id_thread_checkpoint"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["local_session.session_id"],
            name=op.f("fk_session_thread_session_id_local_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_session_thread")),
        sa.UniqueConstraint("active_turn_id", name=op.f("uq_session_thread_active_turn_id")),
        sa.UniqueConstraint("session_id", "root_ordinal", name="session_root"),
        sa.UniqueConstraint("thread_id", "session_id", name="thread_session_identity"),
    )
    with op.batch_alter_table("session_thread", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_thread_session_id"), ["session_id"], unique=False)

    op.create_table(
        "pending_submission",
        sa.Column("submission_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["local_session.session_id"],
            name=op.f("fk_pending_submission_session_id_local_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["session_thread.thread_id"],
            name=op.f("fk_pending_submission_thread_id_session_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("submission_id", name=op.f("pk_pending_submission")),
        sa.UniqueConstraint("thread_id", "ordinal", name="thread_order"),
    )
    with op.batch_alter_table("pending_submission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pending_submission_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "thread_turn",
        sa.Column("turn_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("waiting_reason", sa.String(length=32), nullable=True),
        sa.Column("base_checkpoint_id", sa.String(length=80), nullable=True),
        sa.Column("selected_checkpoint_id", sa.String(length=80), nullable=True),
        sa.Column("terminal_projection_json", sa.Text(), nullable=True),
        sa.Column("failure_json", sa.Text(), nullable=True),
        sa.Column("process_generation", sa.String(length=64), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('accepted', 'running', 'waiting', 'completed', 'failed', 'cancelled', 'interrupted')",
            name=op.f("ck_thread_turn_state"),
        ),
        sa.CheckConstraint(
            "waiting_reason IS NULL OR waiting_reason IN ('deferred_tool', 'approval', 'external_input')",
            name=op.f("ck_thread_turn_waiting_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["base_checkpoint_id"],
            ["thread_checkpoint.checkpoint_id"],
            name=op.f("fk_thread_turn_base_checkpoint_id_thread_checkpoint"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["selected_checkpoint_id"],
            ["thread_checkpoint.checkpoint_id"],
            name=op.f("fk_thread_turn_selected_checkpoint_id_thread_checkpoint"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "session_id"],
            ["session_thread.thread_id", "session_thread.session_id"],
            name=op.f("fk_thread_turn_thread_id_session_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("turn_id", name=op.f("pk_thread_turn")),
        sa.UniqueConstraint("turn_id", "thread_id", name="turn_thread_identity"),
    )
    with op.batch_alter_table("thread_turn", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thread_turn_process_generation"), ["process_generation"], unique=False)
        batch_op.create_index(batch_op.f("ix_thread_turn_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_thread_turn_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_thread_turn_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "pending_deferred",
        sa.Column("turn_id", sa.String(length=80), nullable=False),
        sa.Column("object_digest", sa.String(length=64), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("request_codec_version", sa.String(length=64), nullable=False),
        sa.Column("source_run_id", sa.String(length=128), nullable=False),
        sa.Column("consumed_by_run_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["object_digest"],
            ["immutable_object.logical_digest"],
            name=op.f("fk_pending_deferred_object_digest_immutable_object"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["thread_turn.turn_id"],
            name=op.f("fk_pending_deferred_turn_id_thread_turn"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("turn_id", name=op.f("pk_pending_deferred")),
        sa.UniqueConstraint("consumed_by_run_id", name=op.f("uq_pending_deferred_consumed_by_run_id")),
        sa.UniqueConstraint("object_digest", name=op.f("uq_pending_deferred_object_digest")),
    )
    op.create_table(
        "thread_checkpoint",
        sa.Column("checkpoint_id", sa.String(length=80), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("owner_kind", sa.String(length=32), nullable=False),
        sa.Column("owner_turn_id", sa.String(length=80), nullable=True),
        sa.Column("state_object_digest", sa.String(length=64), nullable=False),
        sa.Column("harness_release", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(owner_kind = 'root_turn' AND owner_turn_id IS NOT NULL) OR (owner_kind != 'root_turn' AND owner_turn_id IS NULL)",
            name=op.f("ck_thread_checkpoint_owner_shape"),
        ),
        sa.CheckConstraint(
            "owner_kind IN ('session_baseline', 'session_fork', 'root_turn')",
            name=op.f("ck_thread_checkpoint_owner_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_turn_id", "thread_id"],
            ["thread_turn.turn_id", "thread_turn.thread_id"],
            name=op.f("fk_thread_checkpoint_owner_turn_id_thread_turn"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["state_object_digest"],
            ["immutable_object.logical_digest"],
            name=op.f("fk_thread_checkpoint_state_object_digest_immutable_object"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("checkpoint_id", name=op.f("pk_thread_checkpoint")),
        sa.UniqueConstraint("state_object_digest", name=op.f("uq_thread_checkpoint_state_object_digest")),
    )
    with op.batch_alter_table("thread_checkpoint", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thread_checkpoint_owner_turn_id"), ["owner_turn_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_thread_checkpoint_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "turn_run",
        sa.Column("turn_id", sa.String(length=80), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["thread_turn.turn_id"], name=op.f("fk_turn_run_turn_id_thread_turn"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("turn_id", "ordinal", name=op.f("pk_turn_run")),
        sa.UniqueConstraint("run_id", name="run_identity"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn_run")
    with op.batch_alter_table("thread_checkpoint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_checkpoint_thread_id"))
        batch_op.drop_index(batch_op.f("ix_thread_checkpoint_owner_turn_id"))

    op.drop_table("thread_checkpoint")
    op.drop_table("pending_deferred")
    with op.batch_alter_table("thread_turn", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_turn_thread_id"))
        batch_op.drop_index(batch_op.f("ix_thread_turn_state"))
        batch_op.drop_index(batch_op.f("ix_thread_turn_session_id"))
        batch_op.drop_index(batch_op.f("ix_thread_turn_process_generation"))

    op.drop_table("thread_turn")
    with op.batch_alter_table("pending_submission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pending_submission_thread_id"))

    op.drop_table("pending_submission")
    with op.batch_alter_table("session_thread", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_thread_session_id"))

    op.drop_table("session_thread")
    op.drop_table("session_presentation")
    with op.batch_alter_table("session_environment_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_environment_assignment_session_id"))
        batch_op.drop_index(batch_op.f("ix_session_environment_assignment_host_resource_id"))

    op.drop_table("session_environment_assignment")
    with op.batch_alter_table("item_projection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_projection_turn_id"))
        batch_op.drop_index(batch_op.f("ix_item_projection_thread_id"))
        batch_op.drop_index(batch_op.f("ix_item_projection_session_id"))

    op.drop_table("item_projection")
    with op.batch_alter_table("event_segment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_segment_session_id"))

    op.drop_table("event_segment")
    with op.batch_alter_table("local_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_local_session_updated_at"))
        batch_op.drop_index(batch_op.f("ix_local_session_pinned"))
        batch_op.drop_index(batch_op.f("ix_local_session_lifecycle_state"))
        batch_op.drop_index(batch_op.f("ix_local_session_archived_at"))

    op.drop_table("local_session")
    with op.batch_alter_table("host_environment_resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_host_environment_resource_provider_spec_digest"))
        batch_op.drop_index(batch_op.f("ix_host_environment_resource_provider_key"))
        batch_op.drop_index(batch_op.f("ix_host_environment_resource_lifecycle_state"))

    op.drop_table("host_environment_resource")
    # ### end Alembic commands ###
