"""initialize local store.

Revision ID: cb6bfc715597
Revises:
Create Date: 2026-08-26 06:33:48.893620+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cb6bfc715597"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "immutable_object",
        sa.Column("logical_digest", sa.String(length=64), nullable=False),
        sa.Column("object_kind", sa.String(length=64), nullable=False),
        sa.Column("object_schema_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("logical_digest", name=op.f("pk_immutable_object")),
    )
    with op.batch_alter_table("immutable_object", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_immutable_object_object_kind"), ["object_kind"], unique=False)

    op.create_table(
        "recovery_diagnostic",
        sa.Column("diagnostic_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("process_generation", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("diagnostic_id", name=op.f("pk_recovery_diagnostic")),
    )
    with op.batch_alter_table("recovery_diagnostic", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recovery_diagnostic_process_generation"), ["process_generation"], unique=False
        )

    op.create_table(
        "store_lease",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("process_generation", sa.String(length=64), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("singleton_id = 1", name=op.f("ck_store_lease_singleton")),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_store_lease")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_lease")
    with op.batch_alter_table("recovery_diagnostic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recovery_diagnostic_process_generation"))

    op.drop_table("recovery_diagnostic")
    with op.batch_alter_table("immutable_object", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_immutable_object_object_kind"))

    op.drop_table("immutable_object")
    # ### end Alembic commands ###
