"""add composition snapshots.

Revision ID: dadd6e6c8d41
Revises: ec1669d88bac
Create Date: 2026-08-27 06:40:50.278542+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dadd6e6c8d41"
down_revision: str | Sequence[str] | None = "ec1669d88bac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "composition_snapshot",
        sa.Column("snapshot_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_digest", sa.String(length=64), nullable=False),
        sa.Column("object_digest", sa.String(length=64), nullable=False),
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.Column("root_resource_kind", sa.String(length=32), nullable=False),
        sa.Column("root_resource_id", sa.String(length=128), nullable=False),
        sa.Column("root_content_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "snapshot_kind IN ('agent', 'environment')", name=op.f("ck_composition_snapshot_snapshot_kind")
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["configuration_generation.generation_id"],
            name=op.f("fk_composition_snapshot_generation_id_configuration_generation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["object_digest"],
            ["immutable_object.logical_digest"],
            name=op.f("fk_composition_snapshot_object_digest_immutable_object"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["root_resource_kind", "root_resource_id", "root_content_digest"],
            ["resource_revision.resource_kind", "resource_revision.resource_id", "resource_revision.content_digest"],
            name=op.f("fk_composition_snapshot_root_resource_kind_resource_revision"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_composition_snapshot")),
        sa.UniqueConstraint("object_digest", name=op.f("uq_composition_snapshot_object_digest")),
        sa.UniqueConstraint("snapshot_kind", "logical_digest", name="identity"),
    )
    with op.batch_alter_table("composition_snapshot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_composition_snapshot_generation_id"), ["generation_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("composition_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_composition_snapshot_generation_id"))

    op.drop_table("composition_snapshot")
    # ### end Alembic commands ###
