"""add configuration catalog.

Revision ID: ec1669d88bac
Revises: cb6bfc715597
Create Date: 2026-08-26 09:28:38.099890+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec1669d88bac"
down_revision: str | Sequence[str] | None = "cb6bfc715597"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_diagnostic",
        sa.Column("diagnostic_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("process_generation", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("diagnostic_id", name=op.f("pk_configuration_diagnostic")),
    )
    with op.batch_alter_table("configuration_diagnostic", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_configuration_diagnostic_process_generation"), ["process_generation"], unique=False
        )

    op.create_table(
        "configuration_generation",
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("process_settings_digest", sa.String(length=64), nullable=False),
        sa.Column("process_settings_json", sa.Text(), nullable=False),
        sa.Column("catalog_digest", sa.String(length=64), nullable=False),
        sa.Column("restart_required", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("generation_id", name=op.f("pk_configuration_generation")),
        sa.UniqueConstraint("sequence", name=op.f("uq_configuration_generation_sequence")),
    )
    with op.batch_alter_table("configuration_generation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_configuration_generation_catalog_digest"), ["catalog_digest"], unique=False
        )

    op.create_table(
        "current_configuration",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("singleton_id = 1", name=op.f("ck_current_configuration_singleton")),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["configuration_generation.generation_id"],
            name=op.f("fk_current_configuration_generation_id_configuration_generation"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_current_configuration")),
        sa.UniqueConstraint("generation_id", name=op.f("uq_current_configuration_generation_id")),
    )
    op.create_table(
        "resource_revision",
        sa.Column("revision_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_kind", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("object_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_digest"],
            ["immutable_object.logical_digest"],
            name=op.f("fk_resource_revision_object_digest_immutable_object"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("revision_id", name=op.f("pk_resource_revision")),
        sa.UniqueConstraint("object_digest", name=op.f("uq_resource_revision_object_digest")),
        sa.UniqueConstraint("resource_kind", "resource_id", "content_digest", name="identity"),
    )
    op.create_table(
        "generation_resource",
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("resource_kind", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["configuration_generation.generation_id"],
            name=op.f("fk_generation_resource_generation_id_configuration_generation"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_kind", "resource_id", "content_digest"],
            ["resource_revision.resource_kind", "resource_revision.resource_id", "resource_revision.content_digest"],
            name=op.f("fk_generation_resource_resource_kind_resource_revision"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("generation_id", "ordinal", name=op.f("pk_generation_resource")),
        sa.UniqueConstraint("generation_id", "resource_kind", "resource_id", name="resource_identity"),
    )
    op.create_table(
        "skill_package_reference",
        sa.Column("resource_kind", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("object_digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint("resource_kind = 'skill'", name=op.f("ck_skill_package_reference_skill_kind")),
        sa.ForeignKeyConstraint(
            ["object_digest"],
            ["immutable_object.logical_digest"],
            name=op.f("fk_skill_package_reference_object_digest_immutable_object"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resource_kind", "resource_id", "content_digest"],
            ["resource_revision.resource_kind", "resource_revision.resource_id", "resource_revision.content_digest"],
            name=op.f("fk_skill_package_reference_resource_kind_resource_revision"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "resource_kind", "resource_id", "content_digest", name=op.f("pk_skill_package_reference")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_package_reference")
    op.drop_table("generation_resource")
    op.drop_table("resource_revision")
    op.drop_table("current_configuration")
    with op.batch_alter_table("configuration_generation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configuration_generation_catalog_digest"))

    op.drop_table("configuration_generation")
    with op.batch_alter_table("configuration_diagnostic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configuration_diagnostic_process_generation"))

    op.drop_table("configuration_diagnostic")
    # ### end Alembic commands ###
