"""add findings and managed analyst

Revision ID: c5d0c6c08220
Revises: 7dc8ec393cc1
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c5d0c6c08220"
down_revision = "7dc8ec393cc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finding_analyses",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(length=72), nullable=False),
        sa.Column("thread_id", sa.String(length=72), nullable=False),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("request_key", sa.String(length=512), nullable=False),
        sa.Column("request_digest", sa.String(), nullable=False),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_runs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selection_truncated", sa.Boolean(), nullable=False),
        sa.Column("read_trace_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_trace_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reported", sa.Boolean(), nullable=False),
        sa.Column("limitations", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["principals.id"], name=op.f("fk_finding_analyses_created_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_finding_analyses_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_finding_analyses_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_finding_analyses_run_id_runs")),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], name=op.f("fk_finding_analyses_session_id_sessions")),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], name=op.f("fk_finding_analyses_thread_id_threads")),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["principals.id"], name=op.f("fk_finding_analyses_updated_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.workspace_id", "agents.id"],
            name=op.f("fk_finding_analyses_workspace_id_agents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_analyses")),
        sa.UniqueConstraint("run_id", name=op.f("uq_finding_analyses_run_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "created_by_id",
            "request_key",
            name=op.f("uq_finding_analyses_workspace_id_created_by_id_request_key"),
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_finding_analyses_workspace_id_id")),
    )
    op.create_index(
        "ix_finding_analyses_workspace_created", "finding_analyses", ["workspace_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("agent_revision_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("explanation", sa.String(), nullable=False),
        sa.Column("suggestion", sa.String(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", sa.String(), nullable=False),
        sa.Column("source_key", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=True),
        sa.Column("source_run_id", sa.String(length=72), nullable=True),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("assessment", sa.String(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "assessment IN ('unreviewed', 'confirmed', 'expected', 'insufficient')", name=op.f("ck_findings_assessment")
        ),
        sa.CheckConstraint("severity IN ('critical', 'warning', 'suggestion')", name=op.f("ck_findings_severity")),
        sa.ForeignKeyConstraint(
            ["agent_id", "agent_revision_id"],
            ["agent_revisions.agent_id", "agent_revisions.id"],
            name=op.f("fk_findings_agent_id_agent_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["principals.id"], name=op.f("fk_findings_created_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_findings_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_findings_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["source_run_id"], ["runs.id"], name=op.f("fk_findings_source_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["principals.id"], name=op.f("fk_findings_updated_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.workspace_id", "agents.id"],
            name=op.f("fk_findings_workspace_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "analysis_id"],
            ["finding_analyses.workspace_id", "finding_analyses.id"],
            name=op.f("fk_findings_workspace_id_finding_analyses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint(
            "workspace_id",
            "created_by_id",
            "source_key",
            name=op.f("uq_findings_workspace_id_created_by_id_source_key"),
        ),
    )
    op.create_index("ix_findings_workspace_created", "findings", ["workspace_id", "created_at", "id"], unique=False)
    op.add_column("agents", sa.Column("preset_kind", sa.String(length=32), nullable=True))
    # Existing builtin heads are Composer; retain their identity and revision history.
    op.execute("UPDATE agents SET preset_kind = 'composer' WHERE source = 'builtin'")
    op.drop_index(op.f("uq_agents_builtin"), table_name="agents", postgresql_where="((source)::text = 'builtin'::text)")
    op.create_index(
        "uq_agents_builtin",
        "agents",
        ["workspace_id", "preset_kind"],
        unique=True,
        postgresql_where=sa.text("source = 'builtin'"),
    )
    op.create_check_constraint(
        op.f("ck_agents_preset"),
        "agents",
        "(source = 'builtin' AND preset_kind IS NOT NULL AND preset_kind IN ('composer', 'finding')) OR (source = 'custom' AND preset_kind IS NULL)",
    )
    op.execute(
        """
    CREATE TRIGGER stamp_resource BEFORE UPDATE ON finding_analyses FOR EACH ROW EXECUTE FUNCTION stamp_resource()
    """
    )
    op.execute(
        """
    CREATE TRIGGER guard_identity BEFORE UPDATE ON finding_analyses FOR EACH ROW EXECUTE FUNCTION guard_identity()
    """
    )
    op.execute(
        """
    CREATE TRIGGER stamp_resource BEFORE UPDATE ON findings FOR EACH ROW EXECUTE FUNCTION stamp_resource()
    """
    )
    op.execute(
        """
    CREATE TRIGGER guard_identity BEFORE UPDATE ON findings FOR EACH ROW EXECUTE FUNCTION guard_identity()
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_agents_preset"), "agents", type_="check")
    op.drop_index("uq_agents_builtin", table_name="agents", postgresql_where=sa.text("source = 'builtin'"))
    # Preserve Finding Agents and their referenced runs when returning to the single-preset schema.
    op.execute("UPDATE agents SET source = 'custom' WHERE preset_kind = 'finding'")
    op.create_index(
        op.f("uq_agents_builtin"),
        "agents",
        ["workspace_id"],
        unique=True,
        postgresql_where="((source)::text = 'builtin'::text)",
    )
    op.drop_column("agents", "preset_kind")
    op.drop_index("ix_findings_workspace_created", table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_finding_analyses_workspace_created", table_name="finding_analyses")
    op.drop_table("finding_analyses")
    # ### end Alembic commands ###
