"""add uploads

Revision ID: 123fec952fe1
Revises: 98a4fd1ba8f7
"""

import sqlalchemy as sa
from alembic import op

revision = "123fec952fe1"
down_revision = "98a4fd1ba8f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("request_key", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("size >= 0", name=op.f("ck_uploads_size")),
        sa.ForeignKeyConstraint(["created_by_id"], ["principals.id"], name=op.f("fk_uploads_created_by_id_principals")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_uploads_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_uploads_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
        sa.UniqueConstraint(
            "workspace_id",
            "created_by_id",
            "request_key",
            name=op.f("uq_uploads_workspace_id_created_by_id_request_key"),
        ),
    )
    op.execute(
        """
    CREATE TRIGGER refuse_mutation BEFORE UPDATE OR DELETE ON uploads FOR EACH ROW EXECUTE FUNCTION refuse_mutation()
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uploads")
    # ### end Alembic commands ###
