import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";

const check = process.argv.includes("--check");
const output = check ? mkdtempSync(join(tmpdir(), "a13n-ui-contract-")) : "src";
try {
  execFileSync(
    "uv",
    [
      "run",
      "--locked",
      "--package",
      "a13n-ui",
      "--no-default-groups",
      "python",
      "../../scripts/export-agent-ui-openapi.py",
      "--output",
      `${output}/openapi.json`,
    ],
    { stdio: "inherit" },
  );
  execFileSync(
    "node",
    [
      "node_modules/openapi-typescript/bin/cli.js",
      `${output}/openapi.json`,
      "-o",
      `${output}/api.generated.ts`,
    ],
    { stdio: "inherit" },
  );
  const schema = JSON.parse(readFileSync(`${output}/openapi.json`, "utf8"));
  const ajv = new Ajv2020({
    strict: false,
    code: { source: true, esm: true },
    validateFormats: true,
  });
  addFormats(ajv);
  ajv.addSchema(schema, "adapter");
  const exports = {};
  const pointers = {};
  for (const [path, methods] of Object.entries(schema.paths)) {
    for (const [method, operation] of Object.entries(methods)) {
      if (!operation.responses?.["200"]?.content?.["application/json"]?.schema)
        continue;
      const pointer = `#/paths/${path.replaceAll("~", "~0").replaceAll("/", "~1")}/${method}/responses/200/content/application~1json/schema`;
      const name = `v${Object.keys(exports).length}`;
      ajv.getSchema(`adapter${pointer}`);
      exports[name] = `adapter${pointer}`;
      pointers[pointer] = name;
    }
  }
  let code = standaloneCode(ajv, exports);
  // Ajv's portable runtime helpers are CJS. Emit static ESM imports for Vite;
  // no runtime compilation or unsafe-eval is needed in the browser.
  const imports = new Map();
  code = code.replace(/require\("([^"]+)"\)/g, (_match, path) => {
    if (!imports.has(path)) imports.set(path, `runtime${imports.size}`);
    return imports.get(path);
  });
  code =
    [...imports]
      .map(([path, name]) => `import ${name} from ${JSON.stringify(path)};`)
      .join("\n") +
    "\n" +
    code;
  code += `\nexport const validators = {${Object.entries(pointers)
    .map(([pointer, name]) => `${JSON.stringify(pointer)}: ${name}`)
    .join(",\n")}};\n`;
  writeFileSync(
    `${output}/validators.generated.js`,
    "// Generated by generate-client.mjs. Do not edit.\n" + code,
  );
  writeFileSync(
    `${output}/validators.generated.d.ts`,
    "// Generated by generate-client.mjs. Do not edit.\nexport const validators: Record<string, (value: unknown) => boolean>;\n",
  );

  if (check) {
    for (const file of [
      "openapi.json",
      "api.generated.ts",
      "validators.generated.js",
      "validators.generated.d.ts",
    ]) {
      if (
        !readFileSync(`${output}/${file}`).equals(readFileSync(`src/${file}`))
      )
        throw new Error(
          `Generated contract drift: ${file}. Run npm run generate.`,
        );
    }
  }
} finally {
  if (check) rmSync(output, { recursive: true, force: true });
}
