import { mcpServers, type MCPServerId } from "a13n-mcp-directory";
import type { MCPPreset } from "./presets";

/** Directory snapshot and public discovery checked 2026-09-11.
 * Presets offer connection settings, not completed account or business-tool verification.
 * Provider account, license, and administrator requirements still apply.
 * Saved connections never follow catalog updates.
 */
const ACCOUNT_ACCESS =
  "Sign in with an account that can access the requested data. Provider plan and administrator policies may apply.";
const PUBLIC_ACCESS =
  "Public tools are available without sign-in. Provider usage limits and feature requirements may apply.";

function preset(
  id: MCPServerId,
  details: Omit<MCPPreset, "id" | "endpoint">,
): MCPPreset {
  return { id, endpoint: mcpServers[id].endpoint, ...details };
}

export const mcpPresets: readonly MCPPreset[] = [
  preset("adobe-experience-manager", {
    name: "Adobe Experience Manager",
    description: "Manage your Adobe Experience Manager content",
    auth: "oauth",
    docs: "https://claude.com/connectors/adobe-experience-manager",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("airops", {
    name: "AirOps",
    description: "Create and optimize content for AI search.",
    auth: "oauth",
    docs: "https://docs.airops.com/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("airtable", {
    name: "Airtable",
    description: "Bases, records, comments, and workspace schemas",
    auth: "oauth",
    docs: "https://support.airtable.com/articles/9897799762-using-the-airtable-mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("airwallex", {
    name: "Airwallex",
    description: "Access Airwallex platform APIs.",
    auth: "oauth",
    docs: "https://claude.com/connectors/airwallex",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("aiwyn-tax", {
    name: "Aiwyn Tax",
    description: "Estimate your federal & state taxes with Aiwyn's tax engine",
    auth: "none",
    docs: "https://claude.com/connectors/aiwyn-tax",
    requirements: PUBLIC_ACCESS,
  }),
  preset("alltrails", {
    name: "AllTrails",
    description: "Find your next hike",
    auth: "none",
    docs: "https://claude.com/connectors/alltrails",
    requirements: PUBLIC_ACCESS,
  }),
  preset("amplitude", {
    name: "Amplitude",
    description: "Analytics, experiments, cohorts, and tracking plans",
    auth: "oauth",
    docs: "https://amplitude.com/docs/amplitude-ai/amplitude-mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("apollo-io", {
    name: "Apollo.io",
    description: "Contacts, companies, sales engagement",
    auth: "oauth",
    docs: "https://knowledge.apollo.io/hc/en-us/articles/43827318678541-Integrate-Apollo-with-Claude",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("asana", {
    name: "Asana",
    description: "Work with tasks, projects, and portfolios.",
    auth: "oauth",
    docs: "https://developers.asana.com/docs/integrating-with-asanas-mcp-server",
    requirements:
      "Create an Asana MCP app, register the displayed redirect URI, and distribute it to your workspace.",
  }),
  preset("atlassian", {
    name: "Atlassian",
    description: "Work with Jira and Confluence using an Atlassian API token.",
    auth: "oauth",
    docs: "https://support.atlassian.com/atlassian-ai-gateway/docs/get-started-with-the-atlassian-remote-mcp-server/",
    requirements:
      "Requires Jira or Confluence Cloud access. Your organization administrator may need to allow the connection.",
  }),
  preset("attio", {
    name: "Attio",
    description: "CRM records, notes, tasks",
    auth: "oauth",
    docs: "https://docs.attio.com/mcp/overview",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("aurora", {
    name: "Aurora",
    description: "Search your Consilio matters, docs, and more.",
    auth: "oauth",
    docs: "https://mcp-docs.ai.consilio.com/docs/quickstart/",
    requirements: "Requires a Consilio Aurora account.",
  }),
  preset("autodesk-product-help", {
    name: "Autodesk Product Help",
    description: "Securely access Autodesk's help documentation",
    auth: "none",
    docs: "https://claude.com/connectors/autodesk-product-help",
    requirements: PUBLIC_ACCESS,
  }),
  preset("base44", {
    name: "Base44",
    description: "AI app building, backend, data",
    auth: "oauth",
    docs: "https://docs.base44.com/developers/backend/overview/mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("blockscout", {
    name: "Blockscout",
    description: "Access and analyze blockchain data",
    auth: "none",
    docs: "https://claude.com/connectors/blockscout",
    requirements: PUBLIC_ACCESS,
  }),
  preset("calendly", {
    name: "Calendly",
    description: "Scheduling, events, and availability",
    auth: "oauth",
    docs: "https://help.calendly.com/hc/en-us/articles/36734570264855-Connect-Calendly-to-your-AI-tools-with-Calendly-MCP",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("campfire", {
    name: "Campfire",
    description: "Search, analyze, and export ERP data",
    auth: "oauth",
    docs: "https://docs.campfire.ai/guides/ai-integration",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("candid", {
    name: "Candid",
    description: "Research nonprofits, funders, and grants",
    auth: "oauth",
    docs: "https://support.claude.com/en/articles/12923235-using-the-candid-connector-in-claude",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("canva", {
    name: "Canva",
    description: "Designs, assets, exports, comments",
    auth: "oauth",
    docs: "https://www.canva.dev/docs/mcp/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("carta", {
    name: "Carta",
    description: "Manage private capital data.",
    auth: "oauth",
    docs: "https://claude.com/connectors/carta",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("cash-app", {
    name: "Cash App",
    description: "Discover local food spots and order with a conversation",
    auth: "none",
    docs: "https://claude.com/connectors/cash-app",
    requirements: PUBLIC_ACCESS,
  }),
  preset("cdata-connect-ai", {
    name: "CData Connect AI",
    description: "Managed MCP access to 350+ data sources",
    auth: "oauth",
    docs: "https://cloud.cdata.com/docs/Claude-Client.html",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("circleback", {
    name: "Circleback",
    description: "Meeting notes, transcripts, action items",
    auth: "oauth",
    docs: "https://circleback.ai/docs/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("clarify", {
    name: "Clarify",
    description: "Search CRM data and create records.",
    auth: "oauth",
    docs: "https://claude.com/connectors/clarify",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("clarity-ai", {
    name: "Clarity AI",
    description: "Simulate fund classifications under proposed SFDR 2.0",
    auth: "none",
    docs: "https://claude.com/connectors/clarity-ai",
    requirements: PUBLIC_ACCESS,
  }),
  preset("clay", {
    name: "Clay",
    description: "Prospecting, enrichment, GTM workflows",
    auth: "oauth",
    docs: "https://www.clay.com/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("clerk", {
    name: "Clerk",
    description: "Look up Clerk SDK documentation and snippets.",
    auth: "none",
    docs: "https://clerk.com/docs/guides/ai/mcp/clerk-mcp-server",
    requirements: "Public Clerk SDK documentation tools; no account required.",
  }),
  preset("clickup", {
    name: "ClickUp",
    description: "Manage tasks, projects, and team collaboration.",
    auth: "oauth",
    docs: "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
    requirements: "Requires access to a ClickUp workspace.",
  }),
  preset("close", {
    name: "Close",
    description: "CRM leads, calls, and pipelines",
    auth: "oauth",
    docs: "https://help.close.com/v1/docs/en/mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("cloudflare", {
    name: "Cloudflare",
    description: "Workers, D1, R2, DNS, account APIs",
    auth: "oauth",
    docs: "https://github.com/cloudflare/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("codex-resets", {
    name: "Codex Resets",
    description: "Codex usage-limit resets and history",
    auth: "none",
    docs: "https://codex-resets.com/",
    requirements: PUBLIC_ACCESS,
  }),
  preset("coindesk", {
    name: "CoinDesk",
    description: "Access Live & Historical Crypto Data, Indices",
    auth: "oauth",
    docs: "https://claude.com/connectors/coindesk",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("common-room", {
    name: "Common Room",
    description: "Community signals, GTM intelligence",
    auth: "oauth",
    docs: "https://www.commonroom.io/docs/using-common-room/common-room-for-claude-connector-and-plugin/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("conductor", {
    name: "Conductor",
    description: "Cloud workspaces, coding agents, sessions",
    auth: "oauth",
    docs: "https://www.conductor.build/docs/api/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("contentsquare", {
    name: "Contentsquare",
    description: "Experience analytics platform for digital businesses",
    auth: "oauth",
    docs: "https://claude.com/connectors/contentsquare",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("context7", {
    name: "Context7",
    description:
      "Look up current library documentation with your Context7 API key.",
    auth: "bearer",
    docs: "https://context7.com/docs/resources/all-clients",
    requirements:
      "Create a Context7 API key. Anonymous access is also available with lower limits.",
  }),
  preset("control-plane", {
    name: "Control Plane",
    description: "Multi-cloud workloads, GVCs, infrastructure",
    auth: "oauth",
    docs: "https://docs.controlplane.com/ai/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("cortellis-regulatory-intelligence", {
    name: "Cortellis Regulatory Intelligence",
    description: "Drug regulatory guidance, Clarivate",
    auth: "oauth",
    docs: "https://api.clarivate.com/lifesciences/mcp-regulatory/documentation",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("coupler-io", {
    name: "Coupler.io",
    description: "Access business data from hundreds of sources",
    auth: "oauth",
    docs: "https://claude.com/connectors/coupler-io",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("courtlistener", {
    name: "CourtListener",
    description: "Legal research across millions of court records",
    auth: "oauth",
    docs: "https://claude.com/connectors/courtlistener",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("courtroom5", {
    name: "Courtroom5",
    description: "Civil legal guidance for self-represented litigants",
    auth: "none",
    docs: "https://claude.com/connectors/courtroom5",
    requirements: PUBLIC_ACCESS,
  }),
  preset("crossbeam", {
    name: "Crossbeam",
    description: "Explore partner data and ecosystem insights.",
    auth: "oauth",
    docs: "https://claude.com/connectors/crossbeam",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("daloopa", {
    name: "Daloopa",
    description: "Financial fundamental data and KPIs with hyperlinks",
    auth: "oauth",
    docs: "https://claude.com/connectors/daloopa",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("day-ai", {
    name: "Day AI",
    description: "Explore CRM contacts, prospects, and customers.",
    auth: "oauth",
    docs: "https://claude.com/connectors/day-ai",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("deepwiki", {
    name: "DeepWiki",
    description: "Explore documentation for public repositories.",
    auth: "none",
    docs: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    requirements: "Public repository documentation; no account required.",
  }),
  preset("definely", {
    name: "Definely",
    description: "Structured contract review tools for legal teams",
    auth: "oauth",
    docs: "https://claude.com/connectors/definely",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("descrybe-legal-engine", {
    name: "Descrybe Legal Engine",
    description: "Ground your work in clean, structured U.S. primary law",
    auth: "none",
    docs: "https://claude.com/connectors/descrybe-legal-engine",
    requirements: PUBLIC_ACCESS,
  }),
  preset("devrev", {
    name: "DevRev",
    description: "Search and update your company's knowledge graph",
    auth: "bearer",
    docs: "https://support.devrev.ai/en-US/devrev/article/ART-21859-remote-mcp-server",
    requirements:
      "Supply a DevRev personal access token with the required organization permissions.",
  }),
  preset("dice", {
    name: "Dice",
    description: "Search active technology jobs",
    auth: "none",
    docs: "https://www.dice.com/about/mcp",
    requirements: "Public job search; no account required.",
  }),
  preset("digits", {
    name: "Digits",
    description: "Track and analyze your finances with Digits",
    auth: "oauth",
    docs: "https://claude.com/connectors/digits",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("dovetail", {
    name: "Dovetail",
    description: "Turn feedback into decisions",
    auth: "oauth",
    docs: "https://claude.com/connectors/dovetail",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("enterpret", {
    name: "Enterpret",
    description: "Get answers from unified feedback of your customers.",
    auth: "oauth",
    docs: "https://claude.com/connectors/enterpret",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("eraser", {
    name: "Eraser",
    description: "Generate, manage, and update Eraser diagrams and files",
    auth: "oauth",
    docs: "https://claude.com/connectors/eraser",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("exa", {
    name: "Exa",
    description: "Web Search + Code Docs Search",
    auth: "none",
    docs: "https://claude.com/connectors/exa",
    requirements: PUBLIC_ACCESS,
  }),
  preset("excalidraw-app-demo", {
    name: "Excalidraw",
    description:
      "MCP for creating interactive hand-drawn diagrams in Excalidraw",
    auth: "none",
    docs: "https://claude.com/connectors/excalidraw-app-demo",
    requirements: PUBLIC_ACCESS,
  }),
  preset("factset", {
    name: "FactSet",
    description: "Financial data and analytics",
    auth: "oauth",
    docs: "https://developer.factset.com/mcp/factset-ai-ready-data-mcp#connect-proprietary-mcp-client",
    requirements:
      "Requires a FactSet account with the relevant data entitlements.",
  }),
  preset("fathom", {
    name: "Fathom",
    description: "Search meeting transcripts and summaries.",
    auth: "oauth",
    docs: "https://claude.com/connectors/fathom",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("fellow-ai", {
    name: "Fellow.ai",
    description: "Meeting transcripts, insights, and action items",
    auth: "oauth",
    docs: "https://help.fellow.ai/en/articles/12622641-fellow-s-mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("fever-event-discovery", {
    name: "Fever Event Discovery",
    description: "Discover live entertainment events worldwide",
    auth: "oauth",
    docs: "https://claude.com/connectors/fever-event-discovery",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("fireflies", {
    name: "Fireflies",
    description: "Meeting transcripts, summaries, search",
    auth: "oauth",
    docs: "https://guide.fireflies.ai/articles/8272956938-learn-about-the-fireflies-mcp-server-model-context-protocol",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("function-health", {
    name: "Function Health",
    description: "Lab results, health answers, nutrition plans",
    auth: "oauth",
    docs: "https://services.functionhealth.com/auth0/acul/claude_connector_docs.html",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("gainsight-staircase-ai", {
    name: "Gainsight (Staircase AI)",
    description: "Power AI Workflows with Customer Context",
    auth: "oauth",
    docs: "https://claude.com/connectors/gainsight-staircase-ai",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("github", {
    name: "GitHub",
    description:
      "Access repositories, issues, and pull requests with a personal access token.",
    auth: "bearer",
    docs: "https://github.com/github/github-mcp-server/blob/main/docs/remote-server.md",
    requirements:
      "Supply a GitHub personal access token with access to the intended repositories.",
  }),
  preset("gitlab", {
    name: "GitLab",
    description: "Connect AI tools securely to your GitLab data",
    auth: "oauth",
    docs: "https://claude.com/connectors/gitlab",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("gocardless", {
    name: "GoCardless",
    description: "Build GoCardless payment API integrations",
    auth: "oauth",
    docs: "https://claude.com/connectors/gocardless",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("godaddy", {
    name: "GoDaddy",
    description: "Search domains and check availability",
    auth: "none",
    docs: "https://claude.com/connectors/godaddy",
    requirements: PUBLIC_ACCESS,
  }),
  preset("goodnotes", {
    name: "Goodnotes",
    description: "Turn AI insights into documents",
    auth: "none",
    docs: "https://claude.com/connectors/goodnotes",
    requirements: PUBLIC_ACCESS,
  }),
  preset("bigquery", {
    name: "Google Cloud BigQuery",
    description: "BigQuery: Advanced analytical insights for agents",
    auth: "static_headers",
    docs: "https://docs.cloud.google.com/mcp/set-up-authentication-mcp-servers",
    requirements:
      "Enable the Google Cloud API and grant MCP Tool User plus resource permissions. Set Authorization to Bearer followed by a Google access token, and x-goog-user-project to your project ID. Replace the token when it expires.",
    headerNames: ["Authorization", "x-goog-user-project"],
  }),
  preset("google-compute-engine", {
    name: "Google Compute Engine",
    description: "Manage Google Cloud compute infrastructure",
    auth: "static_headers",
    docs: "https://docs.cloud.google.com/mcp/set-up-authentication-mcp-servers",
    requirements:
      "Enable the Google Cloud API and grant MCP Tool User plus resource permissions. Set Authorization to Bearer followed by a Google access token, and x-goog-user-project to your project ID. Replace the token when it expires.",
    headerNames: ["Authorization", "x-goog-user-project"],
  }),
  preset("granola", {
    name: "Granola",
    description: "The AI notepad for meetings",
    auth: "oauth",
    docs: "https://claude.com/connectors/granola",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("granted", {
    name: "Granted",
    description: "Discover grant opportunities.",
    auth: "none",
    docs: "https://claude.com/connectors/granted",
    requirements: PUBLIC_ACCESS,
  }),
  preset("graphos-tools", {
    name: "GraphOS MCP Tools",
    description: "Search Apollo docs, specs, and best practices",
    auth: "none",
    docs: "https://claude.com/connectors/graphos-tools",
    requirements: PUBLIC_ACCESS,
  }),
  preset("guidepoint", {
    name: "Guidepoint",
    description: "Real-time access to trusted expert knowledge",
    auth: "oauth",
    docs: "https://claude.com/connectors/guidepoint",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("guru", {
    name: "Guru",
    description: "Company knowledge, cards, answers",
    auth: "oauth",
    docs: "https://help.getguru.com/docs/connecting-gurus-mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("hex", {
    name: "Hex",
    description: "Answer questions with the Hex agent",
    auth: "oauth",
    docs: "https://claude.com/connectors/hex",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("honeycomb", {
    name: "Honeycomb",
    description: "Query and explore observability data and SLOs",
    auth: "oauth",
    docs: "https://claude.com/connectors/honeycomb",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("hubspot", {
    name: "HubSpot",
    description: "Work with CRM records and business data.",
    auth: "oauth",
    docs: "https://developers.hubspot.com/docs/apps/developer-platform/build-apps/integrate-with-the-remote-hubspot-mcp-server",
    requirements:
      "Create a HubSpot MCP Auth App with the displayed redirect URI. Select client secret in request body.",
  }),
  preset("hugging-face", {
    name: "Hugging Face",
    description: "Access the HF Hub and thousands of Gradio Apps",
    auth: "oauth",
    docs: "https://huggingface.co/docs/hub/en/mcp",
    requirements:
      "Sign in to Hugging Face to use your configured tools and private resources. Public Hub tools are also available without sign-in.",
  }),
  preset("ibisworld", {
    name: "IBISWorld",
    description: "Financials, risk data and analysis on 50,000 industries",
    auth: "oauth",
    docs: "https://claude.com/connectors/ibisworld",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("ibkr", {
    name: "IBKR",
    description: "Portfolios, research, trade instructions",
    auth: "oauth",
    docs: "https://www.interactivebrokers.com/en/trading/ai-integrations.php",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("ifttt", {
    name: "IFTTT",
    description: "Connect, control, and automate 1,000+ apps with IFTTT",
    auth: "oauth",
    docs: "https://claude.com/connectors/ifttt",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("jam", {
    name: "Jam",
    description: "Record screen and collect automatic context for issues",
    auth: "oauth",
    docs: "https://claude.com/connectors/jam",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("jentic", {
    name: "Jentic",
    description: "Secure access to 1,500+ APIs",
    auth: "static_headers",
    docs: "https://docs.jentic.com/guides/mcp/cursor-remote/",
    requirements:
      "Create a Jentic Live Capabilities agent, configure its integration credentials, and enter its Agent API Key as x-jentic-api-key.",
    headerNames: ["x-jentic-api-key"],
  }),
  preset("jotform", {
    name: "Jotform",
    description: "Create forms and analyze submissions.",
    auth: "oauth",
    docs: "https://claude.com/connectors/jotform",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("ketryx", {
    name: "Ketryx",
    description: "Search and explore regulated software lifecycle data",
    auth: "oauth",
    docs: "https://claude.com/connectors/ketryx",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("kiwi", {
    name: "Kiwi.com",
    description: "Flight search and travel",
    auth: "none",
    docs: "https://mcp-install-instructions.alpic.cloud/servers/kiwi-com-flight-search",
    requirements: PUBLIC_ACCESS,
  }),
  preset("klaviyo", {
    name: "Klaviyo",
    description: "Marketing campaigns, profiles, analytics",
    auth: "oauth",
    docs: "https://developers.klaviyo.com/en/docs/klaviyo_mcp_server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("lawve-ai", {
    name: "Lawve AI",
    description: "Discover expert-written skills for legal work",
    auth: "oauth",
    docs: "https://claude.com/connectors/lawve-ai",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("legal-data-hunter", {
    name: "Legal Data Hunter",
    description: "Search 23M+ legal docs in 160+ jurisdictions.",
    auth: "oauth",
    docs: "https://claude.com/connectors/legal-data-hunter",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("lilt", {
    name: "LILT",
    description: "High-quality translation with human verification",
    auth: "oauth",
    docs: "https://claude.com/connectors/lilt",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("linear", {
    name: "Linear",
    description: "Work with issues, projects, and teams.",
    auth: "oauth",
    docs: "https://linear.app/docs/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("local-falcon", {
    name: "Local Falcon",
    description: "AI visibility and local search intelligence platform",
    auth: "oauth",
    docs: "https://claude.com/connectors/local-falcon",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("longbridge", {
    name: "Longbridge",
    description: "Market data, portfolio, and trading",
    auth: "oauth",
    docs: "https://open.longbridge.com/docs/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("lorikeet", {
    name: "Lorikeet",
    description: "A universal concierge for complex businesses",
    auth: "oauth",
    docs: "https://claude.com/connectors/lorikeet",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("lucid", {
    name: "Lucid",
    description: "Ideate, diagram, and align teams",
    auth: "oauth",
    docs: "https://claude.com/connectors/lucid",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("lumin", {
    name: "Lumin",
    description:
      "Manage documents, send signature requests, and convert Markdown to PDF",
    auth: "oauth",
    docs: "https://claude.com/connectors/lumin",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("lunarcrush", {
    name: "LunarCrush",
    description: "Real-time social and market intelligence",
    auth: "bearer",
    docs: "https://lunarcrush.com/en/developers/mcp",
    requirements:
      "Supply a LunarCrush API key. Tool access and request limits depend on your plan.",
  }),
  preset("lusha", {
    name: "Lusha",
    description: "Find and enrich B2B contacts and companies",
    auth: "oauth",
    docs: "https://claude.com/connectors/lusha",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("magic-patterns", {
    name: "Magic Patterns",
    description: "Discuss and iterate on Magic Patterns designs",
    auth: "oauth",
    docs: "https://www.magicpatterns.com/docs/documentation/features/mcp-server/overview",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("mailerlite", {
    name: "MailerLite",
    description: "Manage email campaigns and subscribers.",
    auth: "oauth",
    docs: "https://developers.mailerlite.com/mcp",
    requirements: "Requires a MailerLite account.",
  }),
  preset("make", {
    name: "Make",
    description: "Run scenarios and manage your Make account",
    auth: "oauth",
    docs: "https://developers.make.com/mcp-server/connect-using-oauth",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("malwarebytes", {
    name: "Malwarebytes",
    description: "Check links, phones, and emails for scams",
    auth: "none",
    docs: "https://claude.com/connectors/malwarebytes",
    requirements: PUBLIC_ACCESS,
  }),
  preset("mdn", {
    name: "MDN",
    description: "Web docs, search, and browser compatibility data",
    auth: "none",
    docs: "https://developer.mozilla.org/en-US/mcp",
    requirements:
      "Public experimental MDN documentation tools; no account required.",
  }),
  preset("medidata", {
    name: "Medidata",
    description: "Clinical trial help and predictive site ranking",
    auth: "oauth",
    docs: "https://learn.medidata.com/en-US/bundle/mcp-server-documentation/page/medidata_mcp_server_documentation.html",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("mem", {
    name: "Mem",
    description: "Search and manage notes.",
    auth: "oauth",
    docs: "https://docs.mem.ai/mcp/setup",
    requirements: "Requires a Mem workspace.",
  }),
  preset("mercury", {
    name: "Mercury",
    description: "Accounts, transactions, balances, and cards",
    auth: "oauth",
    docs: "https://docs.mercury.com/docs/connecting-mercury-mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("mermaid-chart", {
    name: "Mermaid Chart",
    description: "Validate and render Mermaid diagrams.",
    auth: "none",
    docs: "https://claude.com/connectors/mermaid-chart",
    requirements: PUBLIC_ACCESS,
  }),
  preset("metaview", {
    name: "Metaview",
    description: "The AI platform for recruiting.",
    auth: "oauth",
    docs: "https://claude.com/connectors/metaview",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("midpage", {
    name: "Midpage Legal Research",
    description: "Search legal sources and case law.",
    auth: "oauth",
    docs: "https://docs.midpage.ai/documentation/integration/mcp-tools",
    requirements: "Requires a Midpage account.",
  }),
  preset("mintlify", {
    name: "Mintlify",
    description: "Search, read, and edit your documentation",
    auth: "oauth",
    docs: "https://claude.com/connectors/mintlify",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("miro", {
    name: "Miro",
    description: "Access and create new content on Miro boards",
    auth: "oauth",
    docs: "https://claude.com/connectors/miro",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("mixpanel", {
    name: "Mixpanel",
    description: "Analyze, query, and manage your Mixpanel data",
    auth: "oauth",
    docs: "https://claude.com/connectors/mixpanel",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("monday", {
    name: "Monday",
    description: "Manage projects, boards, and workflows in monday.com",
    auth: "bearer",
    docs: "https://developer.monday.com/api-reference/docs/mcp-api-token",
    requirements:
      "Supply a monday.com personal API token for your own account. Shared integrations require a registered OAuth app and the provider's distribution process.",
  }),
  preset("monte-carlo", {
    name: "Monte Carlo",
    description: "Data & AI observability",
    auth: "oauth",
    docs: "https://claude.com/connectors/monte-carlo",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("moodys", {
    name: "Moody's",
    description: "Credit ratings and risk data",
    auth: "oauth",
    docs: "https://www.moodys.com/web/en/us/genai/model-context-protocol.html",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("morningstar", {
    name: "Morningstar",
    description: "Investment research and data",
    auth: "bearer",
    docs: "https://developer.morningstar.com/direct-web-services/documentation/morningstar-ai-integrations/morningstar-mcp-server/overview#programmatic-access",
    requirements:
      "Requires licensed Morningstar access. Obtain a bearer token through its Authentication API and replace it when it expires.",
  }),
  preset("mospi", {
    name: "MoSPI",
    description: "India's official statistics in natural language",
    auth: "none",
    docs: "https://www.datainnovation.mospi.gov.in/mospi-mcp",
    requirements: PUBLIC_ACCESS,
  }),
  preset("motherduck", {
    name: "MotherDuck",
    description: "DuckDB cloud warehouse, SQL",
    auth: "oauth",
    docs: "https://motherduck.com/docs/sql-reference/mcp/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("motion", {
    name: "Motion Creative Analytics",
    description: "Analyze creative advertising performance.",
    auth: "oauth",
    docs: "https://help.motionapp.com/en/articles/14315735-motion-mcp",
    requirements:
      "Requires an eligible Motion Creative Analytics account and Owner, Admin, or Collaborator role. Performance data currently covers Meta.",
  }),
  preset("msci", {
    name: "MSCI",
    description: "Indexes, private-markets analytics",
    auth: "oauth",
    docs: "https://www.msci.com/downloads/web/msci-com/data-and-analytics/private-asset-solutions/ai-for-private-markets/msci-mcp-msci-connector-user-guide.pdf",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("mt-newswires", {
    name: "MT Newswires",
    description: "Real-time financial news",
    auth: "oauth",
    docs: "https://console.blueskyapi.com/docs/EDGE/news/MT_NEWSWIRES_Global",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("navan", {
    name: "Navan",
    description: "Travel, expenses, transactions, policy data",
    auth: "oauth",
    docs: "https://navan.com/blog/navan-mcp-powering-agentic-ai",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("neon", {
    name: "Neon",
    description: "Postgres projects, branches, SQL, docs",
    auth: "oauth",
    docs: "https://neon.com/docs/ai/neon-mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("netdocuments", {
    name: "NetDocuments (US)",
    description: "Securely access your documents in NetDocuments",
    auth: "oauth",
    docs: "https://claude.com/connectors/netdocuments",
    requirements:
      "Requires NetDocuments account access. This preset uses the United States endpoint; use your regional endpoint for other accounts.",
  }),
  preset("netlify", {
    name: "Netlify",
    description: "Create, deploy, manage, and secure websites on Netlify",
    auth: "oauth",
    docs: "https://claude.com/connectors/netlify",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("notion", {
    name: "Notion",
    description: "Search and work with pages and databases.",
    auth: "oauth",
    docs: "https://developers.notion.com/guides/mcp/get-started-with-mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("omni-analytics", {
    name: "Omni Analytics",
    description:
      "Query your data using natural language through Omni's semantic model",
    auth: "oauth",
    docs: "https://claude.com/connectors/omni-analytics",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("openrouter", {
    name: "OpenRouter",
    description: "Models, pricing, credits, test prompts",
    auth: "oauth",
    docs: "https://openrouter.ai/docs/mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("orion", {
    name: "Orion by Gravity",
    description: "Get insights from your autonomous AI analyst",
    auth: "oauth",
    docs: "https://claude.com/connectors/orion",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("otter-ai", {
    name: "Otter.ai",
    description: "Meeting transcripts, conversations, and insights",
    auth: "oauth",
    docs: "https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("parallel", {
    name: "Parallel Search",
    description: "Real-time web search and content extraction",
    auth: "none",
    docs: "https://docs.parallel.ai/integrations/mcp/search-mcp",
    requirements:
      "Public web search with anonymous limits. A Parallel bearer API key enables higher limits.",
  }),
  preset("paypal", {
    name: "PayPal",
    description: "Access PayPal payments platform",
    auth: "oauth",
    docs: "https://claude.com/connectors/paypal",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("peec-ai", {
    name: "Peec AI",
    description: "Analyze your brand's visibility across LLMs",
    auth: "oauth",
    docs: "https://claude.com/connectors/peec-ai",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("pendo", {
    name: "Pendo (US)",
    description: "Product analytics, guides, feedback",
    auth: "oauth",
    docs: "https://support.pendo.io/hc/en-us/articles/41102236924955-Connect-to-the-Pendo-MCP-server",
    requirements:
      "US subscription endpoint. An administrator must enable AI access; use your regional endpoint for other subscriptions.",
  }),
  preset("pg-aiguide", {
    name: "pg-aiguide",
    description: "Search pg and Tiger docs, learn database skills",
    auth: "none",
    docs: "https://claude.com/connectors/pg-aiguide",
    requirements: PUBLIC_ACCESS,
  }),
  preset("pitchbook", {
    name: "PitchBook",
    description: "Private market intelligence",
    auth: "oauth",
    docs: "https://help.pitchbook.com/s/article/PitchBook-Premium-for-Claude-by-Anthropic",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("planetscale", {
    name: "PlanetScale",
    description: "Manage Postgres and MySQL databases.",
    auth: "oauth",
    docs: "https://planetscale.com/docs/mcp-server",
    requirements: "Requires access to a PlanetScale organization.",
  }),
  preset("play-sheet-music", {
    name: "Play Sheet Music",
    description: "Generate and play interactive sheet music",
    auth: "none",
    docs: "https://github.com/modelcontextprotocol/ext-apps/tree/main/examples/sheet-music-server",
    requirements: PUBLIC_ACCESS,
  }),
  preset("playmcp", {
    name: "PlayMCP",
    description: "Connect Kakao and other PlayMCP services",
    auth: "oauth",
    docs: "https://www.notion.so/2189b97b4888803dbbdcef264e7eff58",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("posthog", {
    name: "PostHog",
    description: "Product analytics, flags, insights",
    auth: "oauth",
    docs: "https://posthog.com/docs/model-context-protocol",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("postman", {
    name: "Postman",
    description: "Give API context to your coding agents",
    auth: "oauth",
    docs: "https://claude.com/connectors/postman",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("privacy", {
    name: "Privacy.com",
    description: "Manage virtual cards and track your spending patterns",
    auth: "oauth",
    docs: "https://claude.com/connectors/privacy",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("process-street", {
    name: "Process Street",
    description: "Explore and update workflow operations",
    auth: "oauth",
    docs: "https://www.process.st/help/docs/mcp-server/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("quartr", {
    name: "Quartr",
    description: "Financial data and AI infrastructure for company research.",
    auth: "oauth",
    docs: "https://claude.com/connectors/quartr",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("quo", {
    name: "Quo",
    description: "Surface call insights and missed opportunities",
    auth: "oauth",
    docs: "https://claude.com/connectors/quo",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("railway", {
    name: "Railway",
    description: "Projects, services, environments, deployments",
    auth: "oauth",
    docs: "https://docs.railway.com/ai/remote-mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("ramp", {
    name: "Ramp",
    description: "Search, access, and analyze your Ramp financial data",
    auth: "oauth",
    docs: "https://claude.com/connectors/ramp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("ramp-data", {
    name: "Ramp Data",
    description: "Search and analyze Ramp spend across 50,000+ businesses",
    auth: "none",
    docs: "https://claude.com/connectors/ramp-data",
    requirements: PUBLIC_ACCESS,
  }),
  preset("razorpay", {
    name: "Razorpay",
    description: "Payments, orders, and settlements",
    auth: "oauth",
    docs: "https://razorpay.com/docs/mcp-server/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("readwise", {
    name: "Readwise",
    description: "Highlights, Reader documents, reading library",
    auth: "oauth",
    docs: "https://readwise.io/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("resend", {
    name: "Resend",
    description: "Emails, templates, contacts, broadcasts, and domains",
    auth: "oauth",
    docs: "https://resend.com/docs/mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("sp-global", {
    name: "S&P Global",
    description: "Capital IQ financials, market data",
    auth: "oauth",
    docs: "https://docs.kensho.com/llmreadyapi/mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("sanity", {
    name: "Sanity",
    description: "Create, query, and manage structured content in Sanity",
    auth: "oauth",
    docs: "https://claude.com/connectors/sanity",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("scholar-gateway", {
    name: "Scholar Gateway",
    description: "Peer-reviewed research, citations",
    auth: "oauth",
    docs: "https://docs.scholargateway.ai/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("scite", {
    name: "Scite",
    description: "Evidence-based answers grounded in research",
    auth: "oauth",
    docs: "https://claude.com/connectors/scite",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("send", {
    name: "Send",
    description: "Create shareable documents, one-pagers, and decks",
    auth: "oauth",
    docs: "https://claude.com/connectors/send",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("sentry", {
    name: "Sentry",
    description: "Investigate application errors and performance.",
    auth: "oauth",
    docs: "https://mcp.sentry.dev/",
    requirements: "Requires access to a Sentry organization.",
  }),
  preset("signnow", {
    name: "SignNow",
    description: "E-signatures and documents",
    auth: "oauth",
    docs: "https://docs.signnow.com/docs/signnow/mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("splice", {
    name: "Splice",
    description: "Search Splice's sounds catalog, build stacks & more!",
    auth: "oauth",
    docs: "https://claude.com/connectors/splice",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("sprouts", {
    name: "Sprouts Data Intelligence",
    description: "Find and qualify sales leads.",
    auth: "none",
    docs: "https://claude.com/connectors/sprouts",
    requirements: PUBLIC_ACCESS,
  }),
  preset("square", {
    name: "Square",
    description: "Search and manage transaction, merchant, and payment data",
    auth: "oauth",
    docs: "https://claude.com/connectors/square",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("stripe", {
    name: "Stripe",
    description: "Work with your Stripe account and payments.",
    auth: "oauth",
    docs: "https://docs.stripe.com/mcp",
    requirements:
      "Authorize the intended Stripe account and sandbox or live environment. A restricted API key can also be used in Bearer token mode.",
  }),
  preset("stytch", {
    name: "Stytch",
    description: "Manage authentication project settings",
    auth: "oauth",
    docs: "https://stytch.com/docs/workspace-management/stytch-mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("supabase", {
    name: "Supabase",
    description: "Projects, database, docs",
    auth: "oauth",
    docs: "https://supabase.com/docs/guides/ai-tools/mcp",
    requirements:
      "Authorize a Supabase organization. Use a project-scoped endpoint and read-only mode when appropriate for your task.",
  }),
  preset("superhuman-mail", {
    name: "Superhuman Mail",
    description: "Manage email and calendar.",
    auth: "oauth",
    docs: "https://claude.com/connectors/superhuman-mail",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("supermetrics", {
    name: "Supermetrics",
    description: "Marketing data, analytics, and reporting",
    auth: "oauth",
    docs: "https://docs.supermetrics.com/docs/supermetrics-mcp-server",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("sybill", {
    name: "Sybill",
    description: "Sales calls, deals, and pipeline intelligence",
    auth: "oauth",
    docs: "https://api.sybill.ai/docs/mcp.html",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("synapse-org", {
    name: "Synapse.org",
    description: "Search collaborative scientific datasets",
    auth: "oauth",
    docs: "https://github.com/susheel/synapse-mcp?tab=readme-ov-file",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("synthesize-bio", {
    name: "Synthesize Bio",
    description: "Generate gene expression from a virtual human",
    auth: "oauth",
    docs: "https://claude.com/connectors/synthesize-bio",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("tango-government-contracting", {
    name: "Tango",
    description: "Search U.S. government contracting data",
    auth: "oauth",
    docs: "https://tango.makegov.com/docs/mcp/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("taskrabbit", {
    name: "Taskrabbit Booking Assistance",
    description: "Find & book local Taskrabbit services near you",
    auth: "none",
    docs: "https://claude.com/connectors/taskrabbit",
    requirements: PUBLIC_ACCESS,
  }),
  preset("tavily", {
    name: "Tavily",
    description: "Connect your AI agents to the web",
    auth: "oauth",
    docs: "https://claude.com/connectors/tavily",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("three-js-3d-viewer", {
    name: "Three.js 3D Viewer",
    description: "Render interactive 3D scenes and models",
    auth: "none",
    docs: "https://github.com/modelcontextprotocol/ext-apps/tree/main/examples/threejs-server",
    requirements: PUBLIC_ACCESS,
  }),
  preset("tldraw", {
    name: "tldraw",
    description: "Diagrams and whiteboards",
    auth: "none",
    docs: "https://tldraw.notion.site/tldraw-mcp-app",
    requirements: PUBLIC_ACCESS,
  }),
  preset("todoist", {
    name: "Todoist",
    description: "Search, complete, and manage your tasks in Todoist",
    auth: "oauth",
    docs: "https://claude.com/connectors/todoist",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("trellis", {
    name: "Trellis",
    description: "Research trial court litigation.",
    auth: "oauth",
    docs: "https://claude.com/connectors/trellis",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("trivago", {
    name: "Trivago",
    description: "Find your ideal hotel at the best price.",
    auth: "none",
    docs: "https://claude.com/connectors/trivago",
    requirements: PUBLIC_ACCESS,
  }),
  preset("twilio", {
    name: "Twilio",
    description: "Build powerful communications and customer engagement",
    auth: "none",
    docs: "https://claude.com/connectors/twilio",
    requirements: PUBLIC_ACCESS,
  }),
  preset("unthread", {
    name: "Unthread",
    description: "Manage customer support tickets.",
    auth: "oauth",
    docs: "https://docs.unthread.io/docs/unthread-ai/unthread-mcp",
    requirements: "Requires an active Unthread account and workspace access.",
  }),
  preset("verisk-xactrestore", {
    name: "Verisk XactRestore",
    description: "Natural-language estimating for XactRestore",
    auth: "oauth",
    docs: "https://claude.com/connectors/verisk-xactrestore",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("viator", {
    name: "Viator",
    description: "Book travel experiences around the world",
    auth: "none",
    docs: "https://claude.com/connectors/viator",
    requirements: PUBLIC_ACCESS,
  }),
  preset("webflow", {
    name: "Webflow",
    description: "Sites, CMS, publishing",
    auth: "oauth",
    docs: "https://developers.webflow.com/mcp/v1.0.0/reference/overview",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("windsor-ai", {
    name: "Windsor.ai",
    description: "Marketing data connectors and attribution",
    auth: "oauth",
    docs: "https://windsor.ai/introducing-windsor-mcp/",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("wix", {
    name: "Wix",
    description: "Sites, stores, bookings",
    auth: "oauth",
    docs: "https://dev.wix.com/docs/sdk/articles/use-the-wix-mcp/about-the-wix-mcp",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("wordpress-com", {
    name: "WordPress.com",
    description: "Secure AI access to manage your WordPress.com sites",
    auth: "oauth",
    docs: "https://claude.com/connectors/wordpress-com",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("workable", {
    name: "Workable",
    description: "Manage hiring and HR.",
    auth: "oauth",
    docs: "https://claude.com/connectors/workable",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("yahoo-finance", {
    name: "Yahoo Finance",
    description: "Market data through the mcpservers.org community gateway.",
    auth: "none",
    docs: "https://mcpservers.org/remote-mcp-servers/yahoo-finance",
    requirements:
      "Public market data through the mcpservers.org community gateway; provider usage limits apply.",
  }),
  preset("zapier", {
    name: "Zapier",
    description: "Actions across 8,000+ apps",
    auth: "oauth",
    docs: "https://docs.zapier.com/mcp/home",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("zocks", {
    name: "Zocks",
    description: "Analyze client conversations, patterns, and insights.",
    auth: "oauth",
    docs: "https://claude.com/connectors/zocks",
    requirements: ACCOUNT_ACCESS,
  }),
  preset("zoom", {
    name: "Zoom",
    description: "Meetings, recordings, summaries",
    auth: "oauth",
    docs: "https://developers.zoom.us/docs/mcp/servers/connect-to-zoom-mcp-servers/",
    requirements:
      "Create a Zoom General app with the displayed redirect URI, product licenses, and tool scopes. Select client secret in Basic header; administrator or developer access is required.",
  }),
];
