import type { MCPPreset } from "./presets";

/** Directory snapshot and public discovery checked 2026-09-11.
 * Presets offer connection settings, not completed account or business-tool verification.
 * Provider account, license, and administrator requirements still apply.
 * Saved connections never follow catalog updates.
 */
const ACCOUNT_ACCESS =
  "Sign in with an account that can access the requested data. Provider plan and administrator policies may apply.";
const PUBLIC_ACCESS =
  "Public tools are available without sign-in. Provider usage limits and feature requirements may apply.";

export const mcpPresets: readonly MCPPreset[] = [
  {
    id: "adobe-experience-manager",
    name: "Adobe Experience Manager",
    description: "Manage your Adobe Experience Manager content",
    endpoint: "https://mcp.adobeaemcloud.com/adobe/mcp/aem",
    auth: "oauth",
    docs: "https://claude.com/connectors/adobe-experience-manager",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f24b64e8d71dfd92fdd8d2_Adobe_icon_RGB_red%20%283%29%20-%20Sarah%20Xu.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "airops",
    name: "AirOps",
    description: "Create and optimize content for AI search.",
    endpoint: "https://app.airops.com/mcp",
    auth: "oauth",
    docs: "https://docs.airops.com/mcp",
    logo: "https://integrations.sh/logo/airops.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Bases, records, comments, and workspace schemas",
    endpoint: "https://mcp.airtable.com/mcp",
    auth: "oauth",
    docs: "https://support.airtable.com/articles/9897799762-using-the-airtable-mcp-server",
    logo: "https://cdn.simpleicons.org/airtable",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "airwallex",
    name: "Airwallex",
    description: "Access Airwallex platform APIs.",
    endpoint: "https://mcp-demo.airwallex.com/developer",
    auth: "oauth",
    docs: "https://claude.com/connectors/airwallex",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6977ee686ffe1cb730e94f07_Airwallex%20Mark%20-%20Colour%20-%20Square.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "aiwyn-tax",
    name: "Aiwyn Tax",
    description: "Estimate your federal & state taxes with Aiwyn's tax engine",
    endpoint: "https://mcp.columnapi.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/aiwyn-tax",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69c05a2e0f10f41c8f005ee0_Aiwyn_Logo_Mark_Square%20%281%29.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "alltrails",
    name: "AllTrails",
    description: "Find your next hike",
    endpoint: "https://www.alltrails.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/alltrails",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f517432a0d2180dc70610b_alltrails.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Analytics, experiments, cohorts, and tracking plans",
    endpoint: "https://mcp.amplitude.com/mcp",
    auth: "oauth",
    docs: "https://amplitude.com/docs/amplitude-ai/amplitude-mcp",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abdac9a60d37ccbb9f396_Amplitude.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "apollo-io",
    name: "Apollo.io",
    description: "Contacts, companies, sales engagement",
    endpoint: "https://mcp.apollo.io/mcp",
    auth: "oauth",
    docs: "https://knowledge.apollo.io/hc/en-us/articles/43827318678541-Integrate-Apollo-with-Claude",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "asana",
    name: "Asana",
    description: "Work with tasks, projects, and portfolios.",
    endpoint: "https://mcp.asana.com/v2/mcp",
    auth: "oauth",
    docs: "https://developers.asana.com/docs/integrating-with-asanas-mcp-server",
    logo: "https://svgl.app/library/asana-logo.svg",
    requirements:
      "Create an Asana MCP app, register the displayed redirect URI, and distribute it to your workspace.",
    oauthClient: "preregistered",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    description: "Work with Jira and Confluence using an Atlassian API token.",
    endpoint: "https://mcp.atlassian.com/v2/mcp",
    auth: "oauth",
    docs: "https://support.atlassian.com/atlassian-ai-gateway/docs/get-started-with-the-atlassian-remote-mcp-server/",
    logo: "https://svgl.app/library/atlassian.svg",
    requirements:
      "Requires Jira or Confluence Cloud access. Your organization administrator may need to allow the connection.",
  },
  {
    id: "attio",
    name: "Attio",
    description: "CRM records, notes, tasks",
    endpoint: "https://mcp.attio.com/mcp",
    auth: "oauth",
    docs: "https://docs.attio.com/mcp/overview",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Search your Consilio matters, docs, and more.",
    endpoint: "https://mcp.ai.consilio.com",
    auth: "oauth",
    docs: "https://mcp-docs.ai.consilio.com/docs/quickstart/",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b70a38d8e2b6e8fa1f71_consilio%20%281%29.svg",
    requirements: "Requires a Consilio Aurora account.",
  },
  {
    id: "autodesk-product-help",
    name: "Autodesk Product Help",
    description: "Securely access Autodesk's help documentation",
    endpoint: "https://developer.api.autodesk.com/knowledge/public/v1/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/autodesk-product-help",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f518707047601013a4983f_autodesk%20%281%29.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "base44",
    name: "Base44",
    description: "AI app building, backend, data",
    endpoint: "https://app.base44.com/mcp",
    auth: "oauth",
    docs: "https://docs.base44.com/developers/backend/overview/mcp-server",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "blockscout",
    name: "Blockscout",
    description: "Access and analyze blockchain data",
    endpoint: "https://mcp.blockscout.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/blockscout",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69409abb57bdbb7a4d76fdda_blockscout.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "calendly",
    name: "Calendly",
    description: "Scheduling, events, and availability",
    endpoint: "https://mcp.calendly.com",
    auth: "oauth",
    docs: "https://help.calendly.com/hc/en-us/articles/36734570264855-Connect-Calendly-to-your-AI-tools-with-Calendly-MCP",
    logo: "https://svgl.app/library/calendly.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "campfire",
    name: "Campfire",
    description: "Search, analyze, and export ERP data",
    endpoint: "https://api.meetcampfire.com/mcp",
    auth: "oauth",
    docs: "https://docs.campfire.ai/guides/ai-integration",
    logo: "https://integrations.sh/logo/campfire.ai",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "candid",
    name: "Candid",
    description: "Research nonprofits, funders, and grants",
    endpoint: "https://mcp.candid.org/mcp",
    auth: "oauth",
    docs: "https://support.claude.com/en/articles/12923235-using-the-candid-connector-in-claude",
    logo: "https://integrations.sh/logo/candid.org",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "canva",
    name: "Canva",
    description: "Designs, assets, exports, comments",
    endpoint: "https://mcp.canva.com/mcp",
    auth: "oauth",
    docs: "https://www.canva.dev/docs/mcp/",
    logo: "https://svgl.app/library/canva.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "carta",
    name: "Carta",
    description: "Manage private capital data.",
    endpoint: "https://mcp.app.carta.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/carta",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a04e2ce40eb4ecd77629d6d_Carta%20Logo%20%281%29%20-%20Annette%20Faynburd.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "cash-app",
    name: "Cash App",
    description: "Discover local food spots and order with a conversation",
    endpoint: "https://connect.squareup.com/v2/mcp/cash-app",
    auth: "none",
    docs: "https://claude.com/connectors/cash-app",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f5028e3442688ab17daa5c_cash-app-green-jewel.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "cdata-connect-ai",
    name: "CData Connect AI",
    description: "Managed MCP access to 350+ data sources",
    endpoint: "https://mcp.cloud.cdata.com/mcp",
    auth: "oauth",
    docs: "https://cloud.cdata.com/docs/Claude-Client.html",
    logo: "https://integrations.sh/logo/cdata.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "circleback",
    name: "Circleback",
    description: "Meeting notes, transcripts, action items",
    endpoint: "https://app.circleback.ai/api/mcp",
    auth: "oauth",
    docs: "https://circleback.ai/docs/mcp",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "clarify",
    name: "Clarify",
    description: "Search CRM data and create records.",
    endpoint: "https://api.clarify.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/clarify",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698d1004171e3fb37688cf6e_clarify.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "clarity-ai",
    name: "Clarity AI",
    description: "Simulate fund classifications under proposed SFDR 2.0",
    endpoint: "https://clarity-sfdr20-mcp.pro.clarity.ai/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/clarity-ai",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69addd1fbd98572d829d496b_clarity_ai.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "clay",
    name: "Clay",
    description: "Prospecting, enrichment, GTM workflows",
    endpoint: "https://api.clay.com/v3/mcp",
    auth: "oauth",
    docs: "https://www.clay.com/",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "clerk",
    name: "Clerk",
    description: "Look up Clerk SDK documentation and snippets.",
    endpoint: "https://mcp.clerk.com/mcp",
    auth: "none",
    docs: "https://clerk.com/docs/guides/ai/mcp/clerk-mcp-server",
    logo: "https://svgl.app/library/clerk-icon-light.svg",
    requirements: "Public Clerk SDK documentation tools; no account required.",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "Manage tasks, projects, and team collaboration.",
    endpoint: "https://mcp.clickup.com/mcp",
    auth: "oauth",
    docs: "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
    logo: "https://svgl.app/library/clickup.svg",
    requirements: "Requires access to a ClickUp workspace.",
  },
  {
    id: "close",
    name: "Close",
    description: "CRM leads, calls, and pipelines",
    endpoint: "https://mcp.close.com/mcp",
    auth: "oauth",
    docs: "https://help.close.com/v1/docs/en/mcp-server",
    logo: "https://integrations.sh/logo/close.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: "Workers, D1, R2, DNS, account APIs",
    endpoint: "https://mcp.cloudflare.com/mcp",
    auth: "oauth",
    docs: "https://github.com/cloudflare/mcp",
    logo: "https://svgl.app/library/cloudflare.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "codex-resets",
    name: "Codex Resets",
    description: "Codex usage-limit resets and history",
    endpoint: "https://codex-resets.com/mcp",
    auth: "none",
    docs: "https://codex-resets.com/",
    logo: "https://mcpservers.org/icon.png",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "coindesk",
    name: "CoinDesk",
    description: "Access Live & Historical Crypto Data, Indices",
    endpoint: "https://mcp.coindesk.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/coindesk",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f51a009621ccc50f144459_CoinDesk%20Logo%20-%20Toby%20Winterflood%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "common-room",
    name: "Common Room",
    description: "Community signals, GTM intelligence",
    endpoint: "https://mcp.commonroom.io/mcp",
    auth: "oauth",
    docs: "https://www.commonroom.io/docs/using-common-room/common-room-for-claude-connector-and-plugin/",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "conductor",
    name: "Conductor",
    description: "Cloud workspaces, coding agents, sessions",
    endpoint: "https://api.conductor.build/mcp",
    auth: "oauth",
    docs: "https://www.conductor.build/docs/api/mcp",
    logo: "https://www.conductor.build/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "contentsquare",
    name: "Contentsquare",
    description: "Experience analytics platform for digital businesses",
    endpoint: "https://api.contentsquare.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/contentsquare",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f185f9227e35cac1f35817_CSQ%20-%20Favicon%20Square.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "context7",
    name: "Context7",
    description:
      "Look up current library documentation with your Context7 API key.",
    endpoint: "https://mcp.context7.com/mcp",
    auth: "bearer",
    docs: "https://context7.com/docs/resources/all-clients",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698690879ec0fe5a8ed0e319_context7-icon-green.png",
    requirements:
      "Create a Context7 API key. Anonymous access is also available with lower limits.",
  },
  {
    id: "control-plane",
    name: "Control Plane",
    description: "Multi-cloud workloads, GVCs, infrastructure",
    endpoint: "https://mcp.cpln.io/mcp",
    auth: "oauth",
    docs: "https://docs.controlplane.com/ai/mcp",
    logo: "https://github.com/controlplane-com.png?size=128",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "cortellis-regulatory-intelligence",
    name: "Cortellis Regulatory Intelligence",
    description: "Drug regulatory guidance, Clarivate",
    endpoint: "https://api.clarivate.com/lifesciences/mcp-regulatory/mcp",
    auth: "oauth",
    docs: "https://api.clarivate.com/lifesciences/mcp-regulatory/documentation",
    logo: "https://cdn.simpleicons.org/clarivate",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "coupler-io",
    name: "Coupler.io",
    description: "Access business data from hundreds of sources",
    endpoint: "https://mcp.coupler.io/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/coupler-io",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abef0d363c9893d2b1511_coupler.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "courtlistener",
    name: "CourtListener",
    description: "Legal research across millions of court records",
    endpoint: "https://mcp.courtlistener.com/",
    auth: "oauth",
    docs: "https://claude.com/connectors/courtlistener",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b6cead61021be70a7f62_courtlistener.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "courtroom5",
    name: "Courtroom5",
    description: "Civil legal guidance for self-represented litigants",
    endpoint: "https://mcp.courtroom5.com/v1",
    auth: "none",
    docs: "https://claude.com/connectors/courtroom5",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b7c9fe9d6c948b934dda_C5-Icons-Outline-Orange%20-%20Sonja%20Ebron.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "crossbeam",
    name: "Crossbeam",
    description: "Explore partner data and ecosystem insights.",
    endpoint: "https://mcp.crossbeam.com",
    auth: "oauth",
    docs: "https://claude.com/connectors/crossbeam",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6913f587fda5ed6a14574a0a_crossbeam.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "daloopa",
    name: "Daloopa",
    description: "Financial fundamental data and KPIs with hyperlinks",
    endpoint: "https://mcp.daloopa.com/server/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/daloopa",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69b05bb16cd6ba7130dc119f_Daloopa.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "day-ai",
    name: "Day AI",
    description: "Explore CRM contacts, prospects, and customers.",
    endpoint: "https://day.ai/api/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/day-ai",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69a881c53b0a0800bff6afc8_day-ai.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "deepwiki",
    name: "DeepWiki",
    description: "Explore documentation for public repositories.",
    endpoint: "https://mcp.deepwiki.com/mcp",
    auth: "none",
    docs: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    logo: "",
    requirements: "Public repository documentation; no account required.",
  },
  {
    id: "definely",
    name: "Definely",
    description: "Structured contract review tools for legal teams",
    endpoint: "https://mcp.eu.definely.com/api/proxy/core-mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/definely",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b8dec4d7c5ef10a90ecc_Definely%20Logo%20Symbol_AW%20-%20Shima%20Rashidi.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "descrybe-legal-engine",
    name: "Descrybe Legal Engine",
    description: "Ground your work in clean, structured U.S. primary law",
    endpoint: "https://mcp.descrybe.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/descrybe-legal-engine",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b7f2a55395e024e4ad7b_Descrybe_SVG.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "devrev",
    name: "DevRev",
    description: "Search and update your company's knowledge graph",
    endpoint: "https://api.devrev.ai/mcp/v1",
    auth: "bearer",
    docs: "https://support.devrev.ai/en-US/devrev/article/ART-21859-remote-mcp-server",
    logo: "https://integrations.sh/logo/devrev.ai",
    requirements:
      "Supply a DevRev personal access token with the required organization permissions.",
  },
  {
    id: "dice",
    name: "Dice",
    description: "Search active technology jobs",
    endpoint: "https://mcp.dice.com/mcp",
    auth: "none",
    docs: "https://www.dice.com/about/mcp",
    logo: "https://integrations.sh/logo/dice.com",
    requirements: "Public job search; no account required.",
  },
  {
    id: "digits",
    name: "Digits",
    description: "Track and analyze your finances with Digits",
    endpoint: "https://api.digits.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/digits",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f15b8886a591bfc458852c_Digits_Server_Logo.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "dovetail",
    name: "Dovetail",
    description: "Turn feedback into decisions",
    endpoint: "https://dovetail.com/api/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/dovetail",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f1529651e90583ac17b70c_dovetail.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "enterpret",
    name: "Enterpret",
    description: "Get answers from unified feedback of your customers.",
    endpoint: "https://wisdom-api.enterpret.com/server/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/enterpret",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f1895c29b60a1fd0dd67d9_enterpret-logo.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "eraser",
    name: "Eraser",
    description: "Generate, manage, and update Eraser diagrams and files",
    endpoint: "https://app.eraser.io/api/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/eraser",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f81d0f8a9556d1bf7a4a6c_eraser.io.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "exa",
    name: "Exa",
    description: "Web Search + Code Docs Search",
    endpoint: "https://mcp.exa.ai/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/exa",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f18bcc1f3b9556c6c58ab9_exa.jpeg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "excalidraw-app-demo",
    name: "Excalidraw",
    description:
      "MCP for creating interactive hand-drawn diagrams in Excalidraw",
    endpoint: "https://excalidraw-mcp-app.vercel.app/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/excalidraw-app-demo",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698b6d382644a53ecb859c9b_idJpJtW9KY_logos.png",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "factset",
    name: "FactSet",
    description: "Financial data and analytics",
    endpoint: "https://mcp.factset.com/content/v1",
    auth: "oauth",
    docs: "https://developer.factset.com/mcp/factset-ai-ready-data-mcp#connect-proprietary-mcp-client",
    logo: "https://developer.factset.com/favicon.ico",
    requirements:
      "Requires a FactSet account with the relevant data entitlements.",
  },
  {
    id: "fathom",
    name: "Fathom",
    description: "Search meeting transcripts and summaries.",
    endpoint: "https://api.fathom.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/fathom",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f15b40f93248911c5249bc_fathom%20-%20Mike%20Nason.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "fellow-ai",
    name: "Fellow.ai",
    description: "Meeting transcripts, insights, and action items",
    endpoint: "https://fellow.app/mcp",
    auth: "oauth",
    docs: "https://help.fellow.ai/en/articles/12622641-fellow-s-mcp-server",
    logo: "https://integrations.sh/logo/fellow.ai",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "fever-event-discovery",
    name: "Fever Event Discovery",
    description: "Discover live entertainment events worldwide",
    endpoint: "https://data-search.apigw.feverup.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/fever-event-discovery",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69b4bb49b243700a3cd55721_fever.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "fireflies",
    name: "Fireflies",
    description: "Meeting transcripts, summaries, search",
    endpoint: "https://api.fireflies.ai/mcp",
    auth: "oauth",
    docs: "https://guide.fireflies.ai/articles/8272956938-learn-about-the-fireflies-mcp-server-model-context-protocol",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "function-health",
    name: "Function Health",
    description: "Lab results, health answers, nutrition plans",
    endpoint: "https://services.functionhealth.com/ai-chat/mcp",
    auth: "oauth",
    docs: "https://services.functionhealth.com/auth0/acul/claude_connector_docs.html",
    logo: "https://integrations.sh/logo/functionhealth.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "gainsight-staircase-ai",
    name: "Gainsight (Staircase AI)",
    description: "Power AI Workflows with Customer Context",
    endpoint: "https://mcp.staircase.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/gainsight-staircase-ai",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69c41f9fe5b4a5ee526cc06d_Staircase_Stars_Saturated%20-%20Mike%20Barnes.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "github",
    name: "GitHub",
    description:
      "Access repositories, issues, and pull requests with a personal access token.",
    endpoint: "https://api.githubcopilot.com/mcp/",
    auth: "bearer",
    docs: "https://github.com/github/github-mcp-server/blob/main/docs/remote-server.md",
    logo: "https://svgl.app/library/github_light.svg",
    requirements:
      "Supply a GitHub personal access token with access to the intended repositories.",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Connect AI tools securely to your GitLab data",
    endpoint: "https://gitlab.com/api/v4/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/gitlab",
    logo: "https://svgl.app/library/gitlab.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "gocardless",
    name: "GoCardless",
    description: "Build GoCardless payment API integrations",
    endpoint: "https://mcp.gocardless.com",
    auth: "oauth",
    docs: "https://claude.com/connectors/gocardless",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f189adf935b1f5a93bb112_GoCardless-Symbol-SQ-Positive-RGB-500px.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    description: "Search domains and check availability",
    endpoint: "https://api.godaddy.com/v1/domains/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/godaddy",
    logo: "https://svgl.app/library/godaddy.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "goodnotes",
    name: "Goodnotes",
    description: "Turn AI insights into documents",
    endpoint: "https://claude-mcp-api.ml.goodnotes.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/goodnotes",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f18c733105c2804a595da5_goodnotes.jpeg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "bigquery",
    name: "Google Cloud BigQuery",
    description: "BigQuery: Advanced analytical insights for agents",
    endpoint: "https://bigquery.googleapis.com/mcp",
    auth: "static_headers",
    docs: "https://docs.cloud.google.com/mcp/set-up-authentication-mcp-servers",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69825fde71dbb2043676fc68_brandmark-logo-google-bigquery.svg",
    requirements:
      "Enable the Google Cloud API and grant MCP Tool User plus resource permissions. Set Authorization to Bearer followed by a Google access token, and x-goog-user-project to your project ID. Replace the token when it expires.",
    headerNames: ["Authorization", "x-goog-user-project"],
  },
  {
    id: "google-compute-engine",
    name: "Google Compute Engine",
    description: "Manage Google Cloud compute infrastructure",
    endpoint: "https://compute.googleapis.com/mcp",
    auth: "static_headers",
    docs: "https://docs.cloud.google.com/mcp/set-up-authentication-mcp-servers",
    logo: "https://integrations.sh/logo/compute.googleapis.com",
    requirements:
      "Enable the Google Cloud API and grant MCP Tool User plus resource permissions. Set Authorization to Bearer followed by a Google access token, and x-goog-user-project to your project ID. Replace the token when it expires.",
    headerNames: ["Authorization", "x-goog-user-project"],
  },
  {
    id: "granola",
    name: "Granola",
    description: "The AI notepad for meetings",
    endpoint: "https://mcp.granola.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/granola",
    logo: "https://svgl.app/library/granola-light.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "granted",
    name: "Granted",
    description: "Discover grant opportunities.",
    endpoint: "https://grantedai.com/api/mcp/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/granted",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69badf81ee3313955f22b01c_granted.png",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "graphos-tools",
    name: "GraphOS MCP Tools",
    description: "Search Apollo docs, specs, and best practices",
    endpoint: "https://mcp.apollographql.com",
    auth: "none",
    docs: "https://claude.com/connectors/graphos-tools",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/699cf0031601d73ff0fd742e_graphos.png",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "guidepoint",
    name: "Guidepoint",
    description: "Real-time access to trusted expert knowledge",
    endpoint: "https://clapi.guidepoint.io/mcp-server/v1/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/guidepoint",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f81d5e802a0ea1197d6706_Guidepoint_MCP_favicon%20-%20Danny.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "guru",
    name: "Guru",
    description: "Company knowledge, cards, answers",
    endpoint: "https://mcp.api.getguru.com/mcp",
    auth: "oauth",
    docs: "https://help.getguru.com/docs/connecting-gurus-mcp-server",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "hex",
    name: "Hex",
    description: "Answer questions with the Hex agent",
    endpoint: "https://app.hex.tech/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/hex",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf6c6461f0fd29c63e59_Hex.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    description: "Query and explore observability data and SLOs",
    endpoint: "https://mcp.honeycomb.io/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/honeycomb",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bf27e6d9dd347e34ca26_honeycomb.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Work with CRM records and business data.",
    endpoint: "https://mcp.hubspot.com",
    auth: "oauth",
    docs: "https://developers.hubspot.com/docs/apps/developer-platform/build-apps/integrate-with-the-remote-hubspot-mcp-server",
    logo: "https://cdn.simpleicons.org/hubspot",
    requirements:
      "Create a HubSpot MCP Auth App with the displayed redirect URI. Select client secret in request body.",
    oauthClient: "preregistered",
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    description: "Access the HF Hub and thousands of Gradio Apps",
    endpoint: "https://huggingface.co/mcp",
    auth: "oauth",
    docs: "https://huggingface.co/docs/hub/en/mcp",
    logo: "https://svgl.app/library/hugging_face.svg",
    requirements:
      "Sign in to Hugging Face to use your configured tools and private resources. Public Hub tools are also available without sign-in.",
  },
  {
    id: "ibisworld",
    name: "IBISWorld",
    description: "Financials, risk data and analysis on 50,000 industries",
    endpoint: "https://mcp.ibisworld.com",
    auth: "oauth",
    docs: "https://claude.com/connectors/ibisworld",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f3d3ca09d07f3b8457c390_Favicon%201%202%20-%20Jackie%20Toomey%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "ibkr",
    name: "IBKR",
    description: "Portfolios, research, trade instructions",
    endpoint: "https://api.ibkr.com/v1/api/mcp",
    auth: "oauth",
    docs: "https://www.interactivebrokers.com/en/trading/ai-integrations.php",
    logo: "https://www.interactivebrokers.com/images/web/favicons/home-screen-icon-192x192.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "ifttt",
    name: "IFTTT",
    description: "Connect, control, and automate 1,000+ apps with IFTTT",
    endpoint: "https://ifttt.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/ifttt",
    logo: "https://cdn.simpleicons.org/ifttt",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "jam",
    name: "Jam",
    description: "Record screen and collect automatic context for issues",
    endpoint: "https://mcp.jam.dev/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/jam",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfb928bf214f7824247c_Jam.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "jentic",
    name: "Jentic",
    description: "Secure access to 1,500+ APIs",
    endpoint: "https://api.jentic.com/mcp",
    auth: "static_headers",
    docs: "https://docs.jentic.com/guides/mcp/cursor-remote/",
    logo: "https://integrations.sh/logo/jentic.com",
    requirements:
      "Create a Jentic Live Capabilities agent, configure its integration credentials, and enter its Agent API Key as x-jentic-api-key.",
    headerNames: ["x-jentic-api-key"],
  },
  {
    id: "jotform",
    name: "Jotform",
    description: "Create forms and analyze submissions.",
    endpoint: "https://mcp.jotform.com/mcp-app",
    auth: "oauth",
    docs: "https://claude.com/connectors/jotform",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfc71647ce192e81d28a_jotform.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "ketryx",
    name: "Ketryx",
    description: "Search and explore regulated software lifecycle data",
    endpoint: "https://app.ketryx.com/api/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/ketryx",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f15ad72c10ac3f096c1a74_ketryx.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "kiwi",
    name: "Kiwi.com",
    description: "Flight search and travel",
    endpoint: "https://mcp.kiwi.com",
    auth: "none",
    docs: "https://mcp-install-instructions.alpic.cloud/servers/kiwi-com-flight-search",
    logo: "https://mcpservers.org/icon.png",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    description: "Marketing campaigns, profiles, analytics",
    endpoint: "https://mcp.klaviyo.com/mcp",
    auth: "oauth",
    docs: "https://developers.klaviyo.com/en/docs/klaviyo_mcp_server",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "lawve-ai",
    name: "Lawve AI",
    description: "Discover expert-written skills for legal work",
    endpoint: "https://mcp.lawve.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/lawve-ai",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b9158a48ff22de1784b9_lawvable%20-%20Antoine%20Louis%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "legal-data-hunter",
    name: "Legal Data Hunter",
    description: "Search 23M+ legal docs in 160+ jurisdictions.",
    endpoint: "https://legaldatahunter.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/legal-data-hunter",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b899526d166cd7ad07e3_legal_data_hunter.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "lilt",
    name: "LILT",
    description: "High-quality translation with human verification",
    endpoint: "https://mcp.lilt.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/lilt",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d13e9fb2d1120753661ed_Lilt-LogoMark_Color.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "linear",
    name: "Linear",
    description: "Work with issues, projects, and teams.",
    endpoint: "https://mcp.linear.app/mcp",
    auth: "oauth",
    docs: "https://linear.app/docs/mcp",
    logo: "https://svgl.app/library/linear.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "local-falcon",
    name: "Local Falcon",
    description: "AI visibility and local search intelligence platform",
    endpoint: "https://mcp.localfalcon.com",
    auth: "oauth",
    docs: "https://claude.com/connectors/local-falcon",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69ae254459fe3a977afda9f1_local-falcon-mcp-logo.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "longbridge",
    name: "Longbridge",
    description: "Market data, portfolio, and trading",
    endpoint: "https://mcp.longbridge.com",
    auth: "oauth",
    docs: "https://open.longbridge.com/docs/mcp",
    logo: "https://github.com/longbridge.png?size=128",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "lorikeet",
    name: "Lorikeet",
    description: "A universal concierge for complex businesses",
    endpoint: "https://api.lorikeetcx.ai/v1/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/lorikeet",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f18cdfb640bd44e6b52062_Lorikeet-sq.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "lucid",
    name: "Lucid",
    description: "Ideate, diagram, and align teams",
    endpoint: "https://mcp.lucid.app/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/lucid",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f18b257b80134ef4df788a_lucidlogo%20-%20Jacob%20Brown%20%28Jake%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "lumin",
    name: "Lumin",
    description:
      "Manage documents, send signature requests, and convert Markdown to PDF",
    endpoint: "https://mcp.luminpdf.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/lumin",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69843e996011391070f38a40_lumin%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "lunarcrush",
    name: "LunarCrush",
    description: "Real-time social and market intelligence",
    endpoint: "https://lunarcrush.ai/mcp",
    auth: "bearer",
    docs: "https://lunarcrush.com/en/developers/mcp",
    logo: "https://integrations.sh/logo/lunarcrush.ai",
    requirements:
      "Supply a LunarCrush API key. Tool access and request limits depend on your plan.",
  },
  {
    id: "lusha",
    name: "Lusha",
    description: "Find and enrich B2B contacts and companies",
    endpoint: "https://mcp.lusha.com/mcp/claude",
    auth: "oauth",
    docs: "https://claude.com/connectors/lusha",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f185605c2fcaee0fa4db08_lusha-purple.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "magic-patterns",
    name: "Magic Patterns",
    description: "Discuss and iterate on Magic Patterns designs",
    endpoint: "https://mcp.magicpatterns.com/mcp",
    auth: "oauth",
    docs: "https://www.magicpatterns.com/docs/documentation/features/mcp-server/overview",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6983b706c57aa5fd1fd7a2d2_magicpatterns.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "mailerlite",
    name: "MailerLite",
    description: "Manage email campaigns and subscribers.",
    endpoint: "https://mcp.mailerlite.com/mcp",
    auth: "oauth",
    docs: "https://developers.mailerlite.com/mcp",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69a666eeaf51ef9283ed2fd8_mailerlite.jpeg",
    requirements: "Requires a MailerLite account.",
  },
  {
    id: "make",
    name: "Make",
    description: "Run scenarios and manage your Make account",
    endpoint: "https://mcp.make.com",
    auth: "oauth",
    docs: "https://developers.make.com/mcp-server/connect-using-oauth",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d14371cf45af84e39a93e_Make-Icon-Square-Purple.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "malwarebytes",
    name: "Malwarebytes",
    description: "Check links, phones, and emails for scams",
    endpoint: "https://scamguard.malwarebytes.com/claude/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/malwarebytes",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f14bd279dd849807ee34b3_malwarebytes.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "mdn",
    name: "MDN",
    description: "Web docs, search, and browser compatibility data",
    endpoint: "https://mcp.mdn.mozilla.net/",
    auth: "none",
    docs: "https://developer.mozilla.org/en-US/mcp",
    logo: "https://developer.mozilla.org/favicon.svg",
    requirements:
      "Public experimental MDN documentation tools; no account required.",
  },
  {
    id: "medidata",
    name: "Medidata",
    description: "Clinical trial help and predictive site ranking",
    endpoint: "https://mcp.imedidata.com/mcp",
    auth: "oauth",
    docs: "https://learn.medidata.com/en-US/bundle/mcp-server-documentation/page/medidata_mcp_server_documentation.html",
    logo: "https://integrations.sh/logo/imedidata.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "mem",
    name: "Mem",
    description: "Search and manage notes.",
    endpoint: "https://mcp.mem.ai/mcp",
    auth: "oauth",
    docs: "https://docs.mem.ai/mcp/setup",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69a772eb46aaa3bf051c52ed_mem_logo_square%20%281%29.svg",
    requirements: "Requires a Mem workspace.",
  },
  {
    id: "mercury",
    name: "Mercury",
    description: "Accounts, transactions, balances, and cards",
    endpoint: "https://mcp.mercury.com/mcp",
    auth: "oauth",
    docs: "https://docs.mercury.com/docs/connecting-mercury-mcp",
    logo: "https://mercury.com/favicon.ico",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "mermaid-chart",
    name: "Mermaid Chart",
    description: "Validate and render Mermaid diagrams.",
    endpoint: "https://mcp.mermaid.ai/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/mermaid-chart",
    logo: "https://svgl.app/library/mermaid-logo-light.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "metaview",
    name: "Metaview",
    description: "The AI platform for recruiting.",
    endpoint: "https://mcp.metaview.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/metaview",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69b3253475eefcc4bf8f3351_Metaview%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "midpage",
    name: "Midpage Legal Research",
    description: "Search legal sources and case law.",
    endpoint: "https://app.midpage.ai/mcp",
    auth: "oauth",
    docs: "https://docs.midpage.ai/documentation/integration/mcp-tools",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/699a550b5cce23be4022d0ab_midpage.svg",
    requirements: "Requires a Midpage account.",
  },
  {
    id: "mintlify",
    name: "Mintlify",
    description: "Search, read, and edit your documentation",
    endpoint: "https://mcp.mintlify.com",
    auth: "oauth",
    docs: "https://claude.com/connectors/mintlify",
    logo: "https://svgl.app/library/mintlify.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "miro",
    name: "Miro",
    description: "Access and create new content on Miro boards",
    endpoint: "https://mcp.miro.com/",
    auth: "oauth",
    docs: "https://claude.com/connectors/miro",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69825d400692311462b4a241_Miro_Miro_Icon_0.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Analyze, query, and manage your Mixpanel data",
    endpoint: "https://mcp.mixpanel.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/mixpanel",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69b842de13c16936e674bff7_Mixpanel%20Logomark%20Purple%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "monday",
    name: "Monday",
    description: "Manage projects, boards, and workflows in monday.com",
    endpoint: "https://mcp.monday.com/mcp",
    auth: "bearer",
    docs: "https://developer.monday.com/api-reference/docs/mcp-api-token",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6921e782b78ebbcbede151d0_monday.jpg",
    requirements:
      "Supply a monday.com personal API token for your own account. Shared integrations require a registered OAuth app and the provider's distribution process.",
  },
  {
    id: "monte-carlo",
    name: "Monte Carlo",
    description: "Data & AI observability",
    endpoint: "https://integrations.getmontecarlo.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/monte-carlo",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a04e495087e98bd9e279ba8_monte_carlo.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "moodys",
    name: "Moody's",
    description: "Credit ratings and risk data",
    endpoint: "https://api.moodys.com/genai-ready-data/m1/mcp",
    auth: "oauth",
    docs: "https://www.moodys.com/web/en/us/genai/model-context-protocol.html",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "morningstar",
    name: "Morningstar",
    description: "Investment research and data",
    endpoint: "https://mcp.morningstar.com/mcp",
    auth: "bearer",
    docs: "https://developer.morningstar.com/direct-web-services/documentation/morningstar-ai-integrations/morningstar-mcp-server/overview#programmatic-access",
    logo: "https://developer.morningstar.com/favicon-32x32.png",
    requirements:
      "Requires licensed Morningstar access. Obtain a bearer token through its Authentication API and replace it when it expires.",
  },
  {
    id: "mospi",
    name: "MoSPI",
    description: "India's official statistics in natural language",
    endpoint: "https://mcp.mospi.gov.in/",
    auth: "none",
    docs: "https://www.datainnovation.mospi.gov.in/mospi-mcp",
    logo: "https://integrations.sh/logo/mospi.gov.in",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "motherduck",
    name: "MotherDuck",
    description: "DuckDB cloud warehouse, SQL",
    endpoint: "https://api.motherduck.com/mcp",
    auth: "oauth",
    docs: "https://motherduck.com/docs/sql-reference/mcp/",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "motion",
    name: "Motion Creative Analytics",
    description: "Analyze creative advertising performance.",
    endpoint: "https://projects.motionapp.com/mcp",
    auth: "oauth",
    docs: "https://help.motionapp.com/en/articles/14315735-motion-mcp",
    logo: "https://cdn.prod.website-files.com/61ba3b439a672312697272c7/62193dfca2d19738b5c6da9d_motion-favicon-256x256.png",
    requirements:
      "Requires an eligible Motion Creative Analytics account and Owner, Admin, or Collaborator role. Performance data currently covers Meta.",
  },
  {
    id: "msci",
    name: "MSCI",
    description: "Indexes, private-markets analytics",
    endpoint: "https://mcp.msci.com/mcp/v1.0/mcp",
    auth: "oauth",
    docs: "https://www.msci.com/downloads/web/msci-com/data-and-analytics/private-asset-solutions/ai-for-private-markets/msci-mcp-msci-connector-user-guide.pdf",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "mt-newswires",
    name: "MT Newswires",
    description: "Real-time financial news",
    endpoint: "https://mcp.mtnewswires.com/mcp",
    auth: "oauth",
    docs: "https://console.blueskyapi.com/docs/EDGE/news/MT_NEWSWIRES_Global",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "navan",
    name: "Navan",
    description: "Travel, expenses, transactions, policy data",
    endpoint: "https://mcp.navan.com/mcp",
    auth: "oauth",
    docs: "https://navan.com/blog/navan-mcp-powering-agentic-ai",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "neon",
    name: "Neon",
    description: "Postgres projects, branches, SQL, docs",
    endpoint: "https://mcp.neon.tech/mcp",
    auth: "oauth",
    docs: "https://neon.com/docs/ai/neon-mcp-server",
    logo: "https://svgl.app/library/neon.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "netdocuments",
    name: "NetDocuments (US)",
    description: "Securely access your documents in NetDocuments",
    endpoint: "https://web-api.us.netdocuments.app/connect/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/netdocuments",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b3f6ad61021be70a3c8f_netdocuments.png",
    requirements:
      "Requires NetDocuments account access. This preset uses the United States endpoint; use your regional endpoint for other accounts.",
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Create, deploy, manage, and secure websites on Netlify",
    endpoint: "https://netlify-mcp.netlify.app/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/netlify",
    logo: "https://svgl.app/library/netlify.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Search and work with pages and databases.",
    endpoint: "https://mcp.notion.com/mcp",
    auth: "oauth",
    docs: "https://developers.notion.com/guides/mcp/get-started-with-mcp",
    logo: "https://svgl.app/library/notion.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "omni-analytics",
    name: "Omni Analytics",
    description:
      "Query your data using natural language through Omni's semantic model",
    endpoint: "https://callbacks.omniapp.co/callback/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/omni-analytics",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69adea9f99911673406e9166_omni.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    description: "Models, pricing, credits, test prompts",
    endpoint: "https://mcp.openrouter.ai/mcp",
    auth: "oauth",
    docs: "https://openrouter.ai/docs/mcp-server",
    logo: "https://cdn.simpleicons.org/openrouter",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "orion",
    name: "Orion by Gravity",
    description: "Get insights from your autonomous AI analyst",
    endpoint: "https://g.runorion.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/orion",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f15c544eecf5b84d8bf776_orion-icon-512%20-%20Drew%20Gillson.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    description: "Meeting transcripts, conversations, and insights",
    endpoint: "https://mcp.otter.ai/mcp",
    auth: "oauth",
    docs: "https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f51c99b93cabe07b652604_otter.ai.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "parallel",
    name: "Parallel Search",
    description: "Real-time web search and content extraction",
    endpoint: "https://search.parallel.ai/mcp",
    auth: "none",
    docs: "https://docs.parallel.ai/integrations/mcp/search-mcp",
    logo: "https://mcpservers.org/logos/parallel.svg",
    requirements:
      "Public web search with anonymous limits. A Parallel bearer API key enables higher limits.",
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Access PayPal payments platform",
    endpoint: "https://mcp.paypal.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/paypal",
    logo: "https://svgl.app/library/paypal.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "peec-ai",
    name: "Peec AI",
    description: "Analyze your brand's visibility across LLMs",
    endpoint: "https://api.peec.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/peec-ai",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f15198d7e7e13b4c1ec865_peec_ai.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "pendo",
    name: "Pendo (US)",
    description: "Product analytics, guides, feedback",
    endpoint: "https://app.pendo.io/mcp/v0/shttp",
    auth: "oauth",
    docs: "https://support.pendo.io/hc/en-us/articles/41102236924955-Connect-to-the-Pendo-MCP-server",
    logo: "https://www.pendo.io/icon.svg",
    requirements:
      "US subscription endpoint. An administrator must enable AI access; use your regional endpoint for other subscriptions.",
  },
  {
    id: "pg-aiguide",
    name: "pg-aiguide",
    description: "Search pg and Tiger docs, learn database skills",
    endpoint: "https://mcp.tigerdata.com/docs",
    auth: "none",
    docs: "https://claude.com/connectors/pg-aiguide",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69c4735963142fd71f9f4a3a_logo-badge-yellow.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "pitchbook",
    name: "PitchBook",
    description: "Private market intelligence",
    endpoint: "https://premium.mcp.pitchbook.com/mcp",
    auth: "oauth",
    docs: "https://help.pitchbook.com/s/article/PitchBook-Premium-for-Claude-by-Anthropic",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    description: "Manage Postgres and MySQL databases.",
    endpoint: "https://mcp.pscale.dev/mcp/planetscale",
    auth: "oauth",
    docs: "https://planetscale.com/docs/mcp-server",
    logo: "https://svgl.app/library/planetscale.svg",
    requirements: "Requires access to a PlanetScale organization.",
  },
  {
    id: "play-sheet-music",
    name: "Play Sheet Music",
    description: "Generate and play interactive sheet music",
    endpoint: "https://example-server.modelcontextprotocol.io/sheet-music/mcp",
    auth: "none",
    docs: "https://github.com/modelcontextprotocol/ext-apps/tree/main/examples/sheet-music-server",
    logo: "https://integrations.sh/logo/modelcontextprotocol.io",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "playmcp",
    name: "PlayMCP",
    description: "Connect Kakao and other PlayMCP services",
    endpoint: "https://playmcp.kakao.com/mcp",
    auth: "oauth",
    docs: "https://www.notion.so/2189b97b4888803dbbdcef264e7eff58",
    logo: "https://integrations.sh/logo/kakao.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "posthog",
    name: "PostHog",
    description: "Product analytics, flags, insights",
    endpoint: "https://mcp.posthog.com/mcp",
    auth: "oauth",
    docs: "https://posthog.com/docs/model-context-protocol",
    logo: "https://svgl.app/library/posthog.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "postman",
    name: "Postman",
    description: "Give API context to your coding agents",
    endpoint: "https://mcp.postman.com/minimal",
    auth: "oauth",
    docs: "https://claude.com/connectors/postman",
    logo: "https://svgl.app/library/postman.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "privacy",
    name: "Privacy.com",
    description: "Manage virtual cards and track your spending patterns",
    endpoint: "https://mcp.privacy.com",
    auth: "oauth",
    docs: "https://claude.com/connectors/privacy",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a04e56fba746672e2a6a28d_privacy-logo%20-%20Johnie%20Lee.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "process-street",
    name: "Process Street",
    description: "Explore and update workflow operations",
    endpoint: "https://mcp.process.st",
    auth: "oauth",
    docs: "https://www.process.st/help/docs/mcp-server/",
    logo: "https://integrations.sh/logo/process.st",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "quartr",
    name: "Quartr",
    description: "Financial data and AI infrastructure for company research.",
    endpoint: "https://mcp.quartr.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/quartr",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69c16ea64d0fb4d397f39e16_quarter-black.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "quo",
    name: "Quo",
    description: "Surface call insights and missed opportunities",
    endpoint: "https://mcp.quo.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/quo",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f2db59ad97fe0b154a1178_quo-logo%20-%20Juraj%20Pal.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "railway",
    name: "Railway",
    description: "Projects, services, environments, deployments",
    endpoint: "https://mcp.railway.com",
    auth: "oauth",
    docs: "https://docs.railway.com/ai/remote-mcp-server",
    logo: "https://svgl.app/library/railway.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "ramp",
    name: "Ramp",
    description: "Search, access, and analyze your Ramp financial data",
    endpoint: "https://ramp-mcp-remote.ramp.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/ramp",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0e242323897e8eeb479_Ramp.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "ramp-data",
    name: "Ramp Data",
    description: "Search and analyze Ramp spend across 50,000+ businesses",
    endpoint: "https://mcp.ramp.com/ramp-data/anthropic/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/ramp-data",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0e242323897e8eeb479_Ramp.jpg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "razorpay",
    name: "Razorpay",
    description: "Payments, orders, and settlements",
    endpoint: "https://mcp.razorpay.com/mcp",
    auth: "oauth",
    docs: "https://razorpay.com/docs/mcp-server/",
    logo: "https://cdn.simpleicons.org/razorpay",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "readwise",
    name: "Readwise",
    description: "Highlights, Reader documents, reading library",
    endpoint: "https://mcp2.readwise.io/mcp",
    auth: "oauth",
    docs: "https://readwise.io/mcp",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "resend",
    name: "Resend",
    description: "Emails, templates, contacts, broadcasts, and domains",
    endpoint: "https://mcp.resend.com/mcp",
    auth: "oauth",
    docs: "https://resend.com/docs/mcp-server",
    logo: "https://cdn.simpleicons.org/resend",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "sp-global",
    name: "S&P Global",
    description: "Capital IQ financials, market data",
    endpoint: "https://kfinance.kensho.com/integrations/mcp",
    auth: "oauth",
    docs: "https://docs.kensho.com/llmreadyapi/mcp",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "sanity",
    name: "Sanity",
    description: "Create, query, and manage structured content in Sanity",
    endpoint: "https://mcp.sanity.io",
    auth: "oauth",
    docs: "https://claude.com/connectors/sanity",
    logo: "https://svgl.app/library/sanity-light.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "scholar-gateway",
    name: "Scholar Gateway",
    description: "Peer-reviewed research, citations",
    endpoint: "https://connector.scholargateway.ai/mcp",
    auth: "oauth",
    docs: "https://docs.scholargateway.ai/",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "scite",
    name: "Scite",
    description: "Evidence-based answers grounded in research",
    endpoint: "https://api.scite.ai/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/scite",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f14fa63e5cc00c8c2fe439_scite.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "send",
    name: "Send",
    description: "Create shareable documents, one-pagers, and decks",
    endpoint: "https://www.send.co/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/send",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f14afcfae4b6a0b0d56710_send-icon-square%20-%20Neil%20Gandhi.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Investigate application errors and performance.",
    endpoint: "https://mcp.sentry.dev/mcp",
    auth: "oauth",
    docs: "https://mcp.sentry.dev/",
    logo: "https://svgl.app/library/sentry.svg",
    requirements: "Requires access to a Sentry organization.",
  },
  {
    id: "signnow",
    name: "SignNow",
    description: "E-signatures and documents",
    endpoint: "https://mcp-server.signnow.com/mcp",
    auth: "oauth",
    docs: "https://docs.signnow.com/docs/signnow/mcp-server",
    logo: "https://mcpservers.org/icon.png",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "splice",
    name: "Splice",
    description: "Search Splice's sounds catalog, build stacks & more!",
    endpoint: "https://mcp.splice.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/splice",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f22435597957163fe5646c_SpliceGlyph-Black%20-%20Kevin%20Stewart.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "sprouts",
    name: "Sprouts Data Intelligence",
    description: "Find and qualify sales leads.",
    endpoint: "https://sprouts-mcp-server.kartikay-dhar.workers.dev",
    auth: "none",
    docs: "https://claude.com/connectors/sprouts",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69974168446d1f867d04722e_sprouts.ai%20logo.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "square",
    name: "Square",
    description: "Search and manage transaction, merchant, and payment data",
    endpoint: "https://mcp.squareup.com/sse",
    auth: "oauth",
    docs: "https://claude.com/connectors/square",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac122efac2533660b7814_Square%20MCP.jpg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Work with your Stripe account and payments.",
    endpoint: "https://mcp.stripe.com",
    auth: "oauth",
    docs: "https://docs.stripe.com/mcp",
    logo: "https://svgl.app/library/stripe.svg",
    requirements:
      "Authorize the intended Stripe account and sandbox or live environment. A restricted API key can also be used in Bearer token mode.",
  },
  {
    id: "stytch",
    name: "Stytch",
    description: "Manage authentication project settings",
    endpoint: "https://mcp.stytch.dev/mcp",
    auth: "oauth",
    docs: "https://stytch.com/docs/workspace-management/stytch-mcp",
    logo: "https://integrations.sh/logo/stytch.dev",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Projects, database, docs",
    endpoint: "https://mcp.supabase.com/mcp",
    auth: "oauth",
    docs: "https://supabase.com/docs/guides/ai-tools/mcp",
    logo: "https://svgl.app/library/supabase.svg",
    requirements:
      "Authorize a Supabase organization. Use a project-scoped endpoint and read-only mode when appropriate for your task.",
  },
  {
    id: "superhuman-mail",
    name: "Superhuman Mail",
    description: "Manage email and calendar.",
    endpoint: "https://mcp.mail.superhuman.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/superhuman-mail",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f15c0204bf266a152583ce_superhuman.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "supermetrics",
    name: "Supermetrics",
    description: "Marketing data, analytics, and reporting",
    endpoint: "https://mcp.supermetrics.com/mcp",
    auth: "oauth",
    docs: "https://docs.supermetrics.com/docs/supermetrics-mcp-server",
    logo: "https://integrations.sh/logo/supermetrics.com",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "sybill",
    name: "Sybill",
    description: "Sales calls, deals, and pipeline intelligence",
    endpoint: "https://mcp.sybill.ai/mcp",
    auth: "oauth",
    docs: "https://api.sybill.ai/docs/mcp.html",
    logo: "https://integrations.sh/logo/sybill.ai",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "synapse-org",
    name: "Synapse.org",
    description: "Search collaborative scientific datasets",
    endpoint: "https://mcp.synapse.org/mcp",
    auth: "oauth",
    docs: "https://github.com/susheel/synapse-mcp?tab=readme-ov-file",
    logo: "https://integrations.sh/logo/synapse.org",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "synthesize-bio",
    name: "Synthesize Bio",
    description: "Generate gene expression from a virtual human",
    endpoint: "https://app.synthesize.bio/api/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/synthesize-bio",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f81c99cf86df125c6570a3_synthesize_bio_logo.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "tango-government-contracting",
    name: "Tango",
    description: "Search U.S. government contracting data",
    endpoint: "https://govcon.dev/mcp",
    auth: "oauth",
    docs: "https://tango.makegov.com/docs/mcp/",
    logo: "https://integrations.sh/logo/govcon.dev",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "taskrabbit",
    name: "Taskrabbit Booking Assistance",
    description: "Find & book local Taskrabbit services near you",
    endpoint: "https://mcp.taskrabbit.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/taskrabbit",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f5218067608fa156b6897a_taskrabbit_logo%20-%20George%20Yu%20Jiang%20%281%29.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "tavily",
    name: "Tavily",
    description: "Connect your AI agents to the web",
    endpoint: "https://mcp.tavily.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/tavily",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69b32f5381aaa44510d50288_tavily.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "three-js-3d-viewer",
    name: "Three.js 3D Viewer",
    description: "Render interactive 3D scenes and models",
    endpoint: "https://example-server.modelcontextprotocol.io/threejs/mcp",
    auth: "none",
    docs: "https://github.com/modelcontextprotocol/ext-apps/tree/main/examples/threejs-server",
    logo: "https://integrations.sh/logo/modelcontextprotocol.io",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "tldraw",
    name: "tldraw",
    description: "Diagrams and whiteboards",
    endpoint: "https://tldraw-mcp-app.tldraw.workers.dev/mcp",
    auth: "none",
    docs: "https://tldraw.notion.site/tldraw-mcp-app",
    logo: "https://cdn.simpleicons.org/tldraw",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Search, complete, and manage your tasks in Todoist",
    endpoint: "https://ai.todoist.net/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/todoist",
    logo: "https://svgl.app/library/todoist.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "trellis",
    name: "Trellis",
    description: "Research trial court litigation.",
    endpoint: "https://mcp.trellis.law/anthropic",
    auth: "oauth",
    docs: "https://claude.com/connectors/trellis",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6a02b79fc767d70218166a22_trellis%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "trivago",
    name: "Trivago",
    description: "Find your ideal hotel at the best price.",
    endpoint: "https://mcp.trivago.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/trivago",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6913f573b5cf9a67fff78b2a_logo_trivago.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "Build powerful communications and customer engagement",
    endpoint: "https://mcp.twilio.com/docs",
    auth: "none",
    docs: "https://claude.com/connectors/twilio",
    logo: "https://svgl.app/library/twilio.svg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "unthread",
    name: "Unthread",
    description: "Manage customer support tickets.",
    endpoint: "https://app.unthread.io/api/mcp",
    auth: "oauth",
    docs: "https://docs.unthread.io/docs/unthread-ai/unthread-mcp",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f527771c5044192f705995_unthread-icon.svg",
    requirements: "Requires an active Unthread account and workspace access.",
  },
  {
    id: "verisk-xactrestore",
    name: "Verisk XactRestore",
    description: "Natural-language estimating for XactRestore",
    endpoint: "https://xactrestore-xactremodelserver-usw2-prod.propsol.io/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/verisk-xactrestore",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69fa17a6c74040f2aa5669fd_verisk.jpeg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "viator",
    name: "Viator",
    description: "Book travel experiences around the world",
    endpoint: "https://exp-app-mcp.prod.ep.viator.com/mcp",
    auth: "none",
    docs: "https://claude.com/connectors/viator",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f5282bfd6b1696c623e9da_viator.jpg",
    requirements: PUBLIC_ACCESS,
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Sites, CMS, publishing",
    endpoint: "https://mcp.webflow.com/mcp",
    auth: "oauth",
    docs: "https://developers.webflow.com/mcp/v1.0.0/reference/overview",
    logo: "https://cdn.simpleicons.org/webflow",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "windsor-ai",
    name: "Windsor.ai",
    description: "Marketing data connectors and attribution",
    endpoint: "https://mcp.windsor.ai",
    auth: "oauth",
    docs: "https://windsor.ai/introducing-windsor-mcp/",
    logo: "https://integrations.sh/logo/windsor.ai",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "wix",
    name: "Wix",
    description: "Sites, stores, bookings",
    endpoint: "https://mcp.wix.com/mcp",
    auth: "oauth",
    docs: "https://dev.wix.com/docs/sdk/articles/use-the-wix-mcp/about-the-wix-mcp",
    logo: "https://cdn.simpleicons.org/wix",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "wordpress-com",
    name: "WordPress.com",
    description: "Secure AI access to manage your WordPress.com sites",
    endpoint: "https://public-api.wordpress.com/wpcom/v2/mcp/v1",
    auth: "oauth",
    docs: "https://claude.com/connectors/wordpress-com",
    logo: "https://svgl.app/library/wordpress.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "workable",
    name: "Workable",
    description: "Manage hiring and HR.",
    endpoint: "https://mcp.workable.com/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/workable",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f81cf5d6ed1685ed513d65_workable%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    description: "Market data through the mcpservers.org community gateway.",
    endpoint: "https://gateway.mcpservers.org/yahoo-finance/mcp",
    auth: "none",
    docs: "https://mcpservers.org/remote-mcp-servers/yahoo-finance",
    logo: "https://mcpservers.org/logos/yahoo-finance.svg",
    requirements:
      "Public market data through the mcpservers.org community gateway; provider usage limits apply.",
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "Actions across 8,000+ apps",
    endpoint: "https://mcp.zapier.com/api/v1/connect",
    auth: "oauth",
    docs: "https://docs.zapier.com/mcp/home",
    logo: "https://cdn.simpleicons.org/zapier",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "zocks",
    name: "Zocks",
    description: "Analyze client conversations, patterns, and insights.",
    endpoint: "https://mcp.zocks.io/v1/mcp",
    auth: "oauth",
    docs: "https://claude.com/connectors/zocks",
    logo: "https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69f18e4c5285238a12ca92e0_zocks%20icon%20-%20Vikto%CC%81ria%20Paro%CC%81czi%20%281%29.svg",
    requirements: ACCOUNT_ACCESS,
  },
  {
    id: "zoom",
    name: "Zoom",
    description: "Meetings, recordings, summaries",
    endpoint: "https://mcp.zoom.us/mcp/zoom/streamable",
    auth: "oauth",
    docs: "https://developers.zoom.us/docs/mcp/servers/connect-to-zoom-mcp-servers/",
    logo: "https://cdn.simpleicons.org/zoom",
    requirements:
      "Create a Zoom General app with the displayed redirect URI, product licenses, and tool scopes. Select client secret in Basic header; administrator or developer access is required.",
    oauthClient: "preregistered",
  },
];
