# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal

from .models import (
    EnvironmentDescribeParams,
    EnvironmentDescribeResult,
    FileCopyParams,
    FileCopyResult,
    FileFindParams,
    FileFindResult,
    FileListParams,
    FileListResult,
    FileMkdirParams,
    FileMkdirResult,
    FileMoveParams,
    FileMoveResult,
    FilePatchTextParams,
    FilePatchTextResult,
    FileReaderCloseParams,
    FileReaderCloseResult,
    FileReaderOpenParams,
    FileReaderOpenResult,
    FileReadTextParams,
    FileReadTextResult,
    FileRemoveParams,
    FileRemoveResult,
    FileSearchParams,
    FileSearchResult,
    FileStatParams,
    FileStatResult,
    FileWriterAbortParams,
    FileWriterAbortResult,
    FileWriterCommitParams,
    FileWriterCommitResult,
    FileWriterOpenParams,
    FileWriterOpenResult,
    FileWriteTextParams,
    FileWriteTextResult,
    InitializeParams,
    InitializeResult,
    OperationCancelParams,
    OperationCancelResult,
    OutputReadParams,
    OutputReadResult,
    OutputReleaseParams,
    OutputReleaseResult,
    PortInspectParams,
    PortInspectResult,
    PortWaitParams,
    PortWaitResult,
    ProcessCloseStdinParams,
    ProcessCloseStdinResult,
    ProcessInspectParams,
    ProcessInspectResult,
    ProcessKillParams,
    ProcessKillResult,
    ProcessReleaseParams,
    ProcessReleaseResult,
    ProcessSignalParams,
    ProcessSignalResult,
    ProcessStartParams,
    ProcessStartResult,
    ProcessWaitParams,
    ProcessWaitResult,
    ProcessWriteStdinParams,
    ProcessWriteStdinResult,
    ReceiptGetParams,
    ReceiptGetResult,
    SessionCloseParams,
    SessionCloseResult,
    ShellExecParams,
    ShellExecResult,
)


@dataclass(frozen=True, slots=True)
class MethodSpec[P, R]:
    name: str
    kind: Literal["request_response"]
    replay_class: str
    introduced: str
    error_family: str
    params_type: type[P]
    result_type: type[R]
    transfer_action: Literal["open", "close", "commit", "abort"] | None = None
    transfer_direction: Literal["server_to_client", "client_to_server"] | None = None


ENVIRONMENT_DESCRIBE = MethodSpec(
    name="environment.describe",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="common",
    transfer_action=None,
    transfer_direction=None,
    params_type=EnvironmentDescribeParams,
    result_type=EnvironmentDescribeResult,
)

FILE_ABORT_WRITER = MethodSpec(
    name="file.abort_writer",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action="abort",
    transfer_direction="client_to_server",
    params_type=FileWriterAbortParams,
    result_type=FileWriterAbortResult,
)

FILE_CLOSE_READER = MethodSpec(
    name="file.close_reader",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action="close",
    transfer_direction="server_to_client",
    params_type=FileReaderCloseParams,
    result_type=FileReaderCloseResult,
)

FILE_COMMIT_WRITER = MethodSpec(
    name="file.commit_writer",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action="commit",
    transfer_direction="client_to_server",
    params_type=FileWriterCommitParams,
    result_type=FileWriterCommitResult,
)

FILE_COPY = MethodSpec(
    name="file.copy",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileCopyParams,
    result_type=FileCopyResult,
)

FILE_FIND = MethodSpec(
    name="file.find",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileFindParams,
    result_type=FileFindResult,
)

FILE_LIST = MethodSpec(
    name="file.list",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileListParams,
    result_type=FileListResult,
)

FILE_MKDIR = MethodSpec(
    name="file.mkdir",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileMkdirParams,
    result_type=FileMkdirResult,
)

FILE_MOVE = MethodSpec(
    name="file.move",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileMoveParams,
    result_type=FileMoveResult,
)

FILE_OPEN_READER = MethodSpec(
    name="file.open_reader",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action="open",
    transfer_direction="server_to_client",
    params_type=FileReaderOpenParams,
    result_type=FileReaderOpenResult,
)

FILE_OPEN_WRITER = MethodSpec(
    name="file.open_writer",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action="open",
    transfer_direction="client_to_server",
    params_type=FileWriterOpenParams,
    result_type=FileWriterOpenResult,
)

FILE_PATCH_TEXT = MethodSpec(
    name="file.patch_text",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FilePatchTextParams,
    result_type=FilePatchTextResult,
)

FILE_READ_TEXT = MethodSpec(
    name="file.read_text",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileReadTextParams,
    result_type=FileReadTextResult,
)

FILE_REMOVE = MethodSpec(
    name="file.remove",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileRemoveParams,
    result_type=FileRemoveResult,
)

FILE_SEARCH = MethodSpec(
    name="file.search",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileSearchParams,
    result_type=FileSearchResult,
)

FILE_STAT = MethodSpec(
    name="file.stat",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileStatParams,
    result_type=FileStatResult,
)

FILE_WRITE_TEXT = MethodSpec(
    name="file.write_text",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=FileWriteTextParams,
    result_type=FileWriteTextResult,
)

INITIALIZE = MethodSpec(
    name="initialize",
    kind="request_response",
    replay_class="ledger_external",
    introduced="1.0",
    error_family="initialization",
    transfer_action=None,
    transfer_direction=None,
    params_type=InitializeParams,
    result_type=InitializeResult,
)

OPERATION_CANCEL = MethodSpec(
    name="operation.cancel",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="common",
    transfer_action=None,
    transfer_direction=None,
    params_type=OperationCancelParams,
    result_type=OperationCancelResult,
)

OUTPUT_READ = MethodSpec(
    name="output.read",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="output",
    transfer_action=None,
    transfer_direction=None,
    params_type=OutputReadParams,
    result_type=OutputReadResult,
)

OUTPUT_RELEASE = MethodSpec(
    name="output.release",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="output",
    transfer_action=None,
    transfer_direction=None,
    params_type=OutputReleaseParams,
    result_type=OutputReleaseResult,
)

PORT_INSPECT = MethodSpec(
    name="port.inspect",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=PortInspectParams,
    result_type=PortInspectResult,
)

PORT_WAIT = MethodSpec(
    name="port.wait",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="resource",
    transfer_action=None,
    transfer_direction=None,
    params_type=PortWaitParams,
    result_type=PortWaitResult,
)

PROCESS_CLOSE_STDIN = MethodSpec(
    name="process.close_stdin",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessCloseStdinParams,
    result_type=ProcessCloseStdinResult,
)

PROCESS_INSPECT = MethodSpec(
    name="process.inspect",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessInspectParams,
    result_type=ProcessInspectResult,
)

PROCESS_KILL = MethodSpec(
    name="process.kill",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessKillParams,
    result_type=ProcessKillResult,
)

PROCESS_RELEASE = MethodSpec(
    name="process.release",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessReleaseParams,
    result_type=ProcessReleaseResult,
)

PROCESS_SIGNAL = MethodSpec(
    name="process.signal",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessSignalParams,
    result_type=ProcessSignalResult,
)

PROCESS_START = MethodSpec(
    name="process.start",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessStartParams,
    result_type=ProcessStartResult,
)

PROCESS_WAIT = MethodSpec(
    name="process.wait",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessWaitParams,
    result_type=ProcessWaitResult,
)

PROCESS_WRITE_STDIN = MethodSpec(
    name="process.write_stdin",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="process",
    transfer_action=None,
    transfer_direction=None,
    params_type=ProcessWriteStdinParams,
    result_type=ProcessWriteStdinResult,
)

RECEIPT_GET = MethodSpec(
    name="receipt.get",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="common",
    transfer_action=None,
    transfer_direction=None,
    params_type=ReceiptGetParams,
    result_type=ReceiptGetResult,
)

SESSION_CLOSE = MethodSpec(
    name="session.close",
    kind="request_response",
    replay_class="active_only",
    introduced="1.0",
    error_family="session",
    transfer_action=None,
    transfer_direction=None,
    params_type=SessionCloseParams,
    result_type=SessionCloseResult,
)

SHELL_EXEC = MethodSpec(
    name="shell.exec",
    kind="request_response",
    replay_class="terminal_evidence",
    introduced="1.0",
    error_family="command",
    transfer_action=None,
    transfer_direction=None,
    params_type=ShellExecParams,
    result_type=ShellExecResult,
)

METHODS = MappingProxyType(
    {
        ENVIRONMENT_DESCRIBE.name: ENVIRONMENT_DESCRIBE,
        FILE_ABORT_WRITER.name: FILE_ABORT_WRITER,
        FILE_CLOSE_READER.name: FILE_CLOSE_READER,
        FILE_COMMIT_WRITER.name: FILE_COMMIT_WRITER,
        FILE_COPY.name: FILE_COPY,
        FILE_FIND.name: FILE_FIND,
        FILE_LIST.name: FILE_LIST,
        FILE_MKDIR.name: FILE_MKDIR,
        FILE_MOVE.name: FILE_MOVE,
        FILE_OPEN_READER.name: FILE_OPEN_READER,
        FILE_OPEN_WRITER.name: FILE_OPEN_WRITER,
        FILE_PATCH_TEXT.name: FILE_PATCH_TEXT,
        FILE_READ_TEXT.name: FILE_READ_TEXT,
        FILE_REMOVE.name: FILE_REMOVE,
        FILE_SEARCH.name: FILE_SEARCH,
        FILE_STAT.name: FILE_STAT,
        FILE_WRITE_TEXT.name: FILE_WRITE_TEXT,
        INITIALIZE.name: INITIALIZE,
        OPERATION_CANCEL.name: OPERATION_CANCEL,
        OUTPUT_READ.name: OUTPUT_READ,
        OUTPUT_RELEASE.name: OUTPUT_RELEASE,
        PORT_INSPECT.name: PORT_INSPECT,
        PORT_WAIT.name: PORT_WAIT,
        PROCESS_CLOSE_STDIN.name: PROCESS_CLOSE_STDIN,
        PROCESS_INSPECT.name: PROCESS_INSPECT,
        PROCESS_KILL.name: PROCESS_KILL,
        PROCESS_RELEASE.name: PROCESS_RELEASE,
        PROCESS_SIGNAL.name: PROCESS_SIGNAL,
        PROCESS_START.name: PROCESS_START,
        PROCESS_WAIT.name: PROCESS_WAIT,
        PROCESS_WRITE_STDIN.name: PROCESS_WRITE_STDIN,
        RECEIPT_GET.name: RECEIPT_GET,
        SESSION_CLOSE.name: SESSION_CLOSE,
        SHELL_EXEC.name: SHELL_EXEC,
    }
)
