"""persist accepted environment directories.

Revision ID: 372b80e475fd
Revises: ad89162346c1
Create Date: 2026-09-19 04:03:10.514865+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "372b80e475fd"
down_revision: str | Sequence[str] | None = "ad89162346c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_environment_mounts", sa.Column("working_directory", sa.String(length=4096), nullable=True))
    op.add_column("runs", sa.Column("environment_working_directory", sa.String(length=4096), nullable=True))
    op.add_column("threads", sa.Column("default_environment_working_directory", sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "default_environment_working_directory")
    op.drop_column("runs", "environment_working_directory")
    op.drop_column("run_environment_mounts", "working_directory")
    # ### end Alembic commands ###
