"""Add durable envd device pairing.

Revision ID: 231ed10943c1
Revises: 372b80e475fd
Create Date: 2026-09-19 11:39:39.315042+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "231ed10943c1"
down_revision: str | Sequence[str] | None = "372b80e475fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environment_device_pairings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("credential_digest", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rejected", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_device_pairings")),
        sa.UniqueConstraint("credential_digest", name=op.f("uq_environment_device_pairings_credential_digest")),
    )
    op.create_index(
        op.f("ix_environment_device_pairings_expires_at"), "environment_device_pairings", ["expires_at"], unique=False
    )
    op.add_column("environments", sa.Column("device_credential_digest", sa.String(length=64), nullable=True))
    op.add_column("environments", sa.Column("device_revoked_at", sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(
        op.f("uq_environments_device_credential_digest"), "environments", ["device_credential_digest"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_environments_device_credential_digest"), "environments", type_="unique")
    op.drop_column("environments", "device_revoked_at")
    op.drop_column("environments", "device_credential_digest")
    op.drop_index(op.f("ix_environment_device_pairings_expires_at"), table_name="environment_device_pairings")
    op.drop_table("environment_device_pairings")
    # ### end Alembic commands ###
