"""add file memory storage and organization metadata.

Revision ID: ad89162346c1
Revises: 168989a922a6
Create Date: 2026-09-18 12:22:43.890192+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ad89162346c1"
down_revision: str | Sequence[str] | None = "168989a922a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_storage_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("target_digest", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("provider_identity", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("scope_kind", sa.String(length=32), nullable=True),
        sa.Column("subject_id", sa.String(length=72), nullable=True),
        sa.Column("environment_id", sa.String(length=72), nullable=False),
        sa.Column("root", sa.Text(), nullable=False),
        sa.Column("backing_identity", sa.String(length=256), nullable=False),
        sa.Column("initialized", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_memory_storage_bindings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_storage_bindings")),
    )
    op.create_index("uq_memory_storage_target", "memory_storage_bindings", ["target_digest"], unique=True)
    op.create_table(
        "environment_file_uses",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("environment_id", sa.String(length=72), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
            name=op.f("fk_environment_file_uses_environment_id_environments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_file_uses")),
    )
    op.create_index(
        op.f("ix_environment_file_uses_environment_id"), "environment_file_uses", ["environment_id"], unique=False
    )
    op.create_table(
        "memory_organization_work",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("storage_id", sa.String(length=72), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("plan_digest", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("owner", sa.String(length=72), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_memory_organization_work_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["memory_storage_bindings.id"],
            name=op.f("fk_memory_organization_work_storage_id_memory_storage_bindings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_organization_work")),
    )
    op.create_index(
        "ix_memory_organization_pending", "memory_organization_work", ["status", "available_at"], unique=False
    )
    op.create_table(
        "run_memory_storage_bindings",
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("selection_digest", sa.String(length=64), nullable=False),
        sa.Column("organization_policy", sa.JSON(), nullable=True),
        sa.Column("storage_id", sa.String(length=72), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_memory_storage_bindings_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["memory_storage_bindings.id"],
            name=op.f("fk_run_memory_storage_bindings_storage_id_memory_storage_bindings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", "selection_digest", name=op.f("pk_run_memory_storage_bindings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_memory_storage_bindings")
    op.drop_index("ix_memory_organization_pending", table_name="memory_organization_work")
    op.drop_table("memory_organization_work")
    op.drop_index(op.f("ix_environment_file_uses_environment_id"), table_name="environment_file_uses")
    op.drop_table("environment_file_uses")
    op.drop_index("uq_memory_storage_target", table_name="memory_storage_bindings")
    op.drop_table("memory_storage_bindings")
    # ### end Alembic commands ###
