"""add GitHub notification polling.

Revision ID: 4a9959a58c31
Revises: 47f1fc14608c
Create Date: 2026-09-17 04:49:44.389335+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a9959a58c31"
down_revision: str | Sequence[str] | None = "47f1fc14608c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_notification_polls",
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("cursor_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("has_history", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claim_generation", sa.Integer(), server_default="0", nullable=False),
        sa.Column("claim_owner", sa.String(length=72), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.CheckConstraint("claim_generation >= 0", name=op.f("ck_github_notification_polls_generation_nonnegative")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["application_accounts.id"],
            name=op.f("fk_github_notification_polls_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("pk_github_notification_polls")),
    )
    op.create_index(
        op.f("ix_github_notification_polls_available_at"), "github_notification_polls", ["available_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_github_notification_polls_available_at"), table_name="github_notification_polls")
    op.drop_table("github_notification_polls")
    # ### end Alembic commands ###
