"""add lifecycle hook dispatch progress.

Revision ID: a839cb6a7291
Revises: 4f13d47dda74
Create Date: 2026-09-20 08:42:50.426698+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a839cb6a7291"
down_revision: str | Sequence[str] | None = "4f13d47dda74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lifecycle_events",
        sa.Column("hook_dispatch_state", sa.String(length=32), server_default="pending", nullable=False),
    )
    op.add_column(
        "lifecycle_events", sa.Column("hook_dispatch_attempts", sa.BigInteger(), server_default="0", nullable=False)
    )
    op.add_column(
        "lifecycle_events",
        sa.Column(
            "hook_dispatch_next_attempt_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("lifecycle_events", sa.Column("hook_dispatched_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("lifecycle_events", sa.Column("hook_dispatch_error_json", sa.JSON(none_as_null=True), nullable=True))
    op.create_index(
        "ix_lifecycle_events_hook_dispatch_due",
        "lifecycle_events",
        ["hook_dispatch_next_attempt_at", "seq"],
        unique=False,
        postgresql_where=sa.text("hook_dispatch_state = 'pending'"),
    )
    op.create_check_constraint(
        op.f("ck_lifecycle_events_hook_dispatch_attempts_non_negative"),
        "lifecycle_events",
        "hook_dispatch_attempts >= 0",
    )
    op.create_check_constraint(
        op.f("ck_lifecycle_events_hook_dispatch_shape_valid"),
        "lifecycle_events",
        "(hook_dispatch_state = 'pending' AND hook_dispatch_next_attempt_at IS NOT NULL AND hook_dispatched_at IS NULL) OR (hook_dispatch_state = 'done' AND hook_dispatch_next_attempt_at IS NULL AND hook_dispatched_at IS NOT NULL AND hook_dispatch_error_json IS NULL) OR (hook_dispatch_state = 'failed' AND hook_dispatch_next_attempt_at IS NULL AND hook_dispatched_at IS NULL AND hook_dispatch_error_json IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_lifecycle_events_hook_dispatch_shape_valid"), "lifecycle_events", type_="check")
    op.drop_constraint(
        op.f("ck_lifecycle_events_hook_dispatch_attempts_non_negative"), "lifecycle_events", type_="check"
    )
    op.drop_index(
        "ix_lifecycle_events_hook_dispatch_due",
        table_name="lifecycle_events",
        postgresql_where=sa.text("hook_dispatch_state = 'pending'"),
    )
    op.drop_column("lifecycle_events", "hook_dispatch_error_json")
    op.drop_column("lifecycle_events", "hook_dispatched_at")
    op.drop_column("lifecycle_events", "hook_dispatch_next_attempt_at")
    op.drop_column("lifecycle_events", "hook_dispatch_attempts")
    op.drop_column("lifecycle_events", "hook_dispatch_state")
    # ### end Alembic commands ###
