"""Provider-neutral run-scoped Environment API."""

from typing import TYPE_CHECKING, Any

from .attachments import create_environment_provider_binding
from .commands import (
    ArgvCommand,
    BoundProcessHandle,
    CommandEnvironment,
    CommandLimits,
    CommandRequest,
    PortObservation,
    PortTarget,
    ProcessControlResult,
    ProcessInfo,
    ProcessOutputSnapshot,
    ProcessReadOutputResult,
    ProcessSignalResult,
    ProcessStartResult,
    ProcessStatus,
    ProcessStreamRead,
    ProcessWriteStdinResult,
    ShellCommand,
    ShellExecResult,
)
from .coordinator import (
    CompositeBoundEnvironment,
    CompositeEnvironmentRunBinding,
    NoopBoundEnvironment,
    NoopEnvironmentRunBinding,
    create_environment_run_binding,
    create_noop_environment_run_binding,
)
from .extension_factories import (
    ENVIRONMENT_RUN_EXTENSION_ENTRY_POINT_GROUP,
    EnvironmentRunExtensionFactory,
    EnvironmentRunExtensionFactoryCatalog,
    EnvironmentRunExtensionFactoryContext,
    EnvironmentRunExtensionFactoryReference,
    EnvironmentRunExtensionFactoryRegistration,
    build_environment_run_extension_factory_catalog,
    discover_environment_run_extension_factory_references,
)
from .extensions import EnvironmentRunExtension, EnvironmentRunExtensionContext
from .files import (
    FileCopyResult,
    FileEntriesResult,
    FileMetadata,
    FileMutationResult,
    FileOperator,
    FilePatchResult,
    FileQueryRequest,
    FileTextMatch,
    FileTextResult,
    FileTextSearchRequest,
    FileTextSearchResult,
    FileWriteMode,
    FileWriteResult,
)
from .models import (
    DEFAULT_ENVIRONMENT_OPERATION_TIMEOUT_SECONDS,
    ENVIRONMENT_ACTION_CATALOG_VERSION,
    ENVIRONMENT_ACTION_DISPATCH,
    EnvironmentAction,
    EnvironmentActionDispatch,
    EnvironmentAvailability,
    EnvironmentBinding,
    EnvironmentBindingObservation,
    EnvironmentBindingRequest,
    EnvironmentBindingState,
    EnvironmentDescriptor,
    EnvironmentError,
    EnvironmentMountDescriptor,
    EnvironmentOperationFamily,
    EnvironmentPath,
    EnvironmentPermissionSet,
    EnvironmentReadinessRequirement,
    EnvironmentState,
    EnvironmentStateLimits,
    EnvironmentTopology,
    EnvironmentTopologyBindingChange,
    EnvironmentTopologyChange,
    EnvironmentTopologyLimits,
    EnvironmentTopologyRequest,
)
from .providers import (
    BoundEnvironment,
    BoundEnvironmentProvider,
    EnvironmentProviderBinding,
    EnvironmentProviderOperations,
    EnvironmentRunBinding,
    EnvironmentTopologyController,
    EnvironmentTopologyObserver,
    FileScopeProvider,
    FileScopeSelection,
)
from .retention import (
    BoundOutputCursor,
    BoundOutputReference,
    EnvironmentOutputCapture,
    EnvironmentOutputPolicy,
    EnvironmentOutputReadResult,
    EnvironmentOutputSegment,
    OpaqueOutputCursor,
    OpaqueOutputReference,
    OpaqueProcessHandle,
)
from .virtual_files import VirtualFileOperator

if TYPE_CHECKING:
    from .configuration import DynamicEnvironmentConfiguration
    from .dynamic import DynamicEnvironmentCapability


def __getattr__(name: str) -> Any:
    if name in {"DynamicEnvironmentCapability", "DynamicEnvironmentConfiguration"}:
        from .configuration import DynamicEnvironmentConfiguration
        from .dynamic import DynamicEnvironmentCapability

        return {
            "DynamicEnvironmentCapability": DynamicEnvironmentCapability,
            "DynamicEnvironmentConfiguration": DynamicEnvironmentConfiguration,
        }[name]
    raise AttributeError(name)


__all__ = [
    "DEFAULT_ENVIRONMENT_OPERATION_TIMEOUT_SECONDS",
    "ENVIRONMENT_ACTION_CATALOG_VERSION",
    "ENVIRONMENT_ACTION_DISPATCH",
    "ENVIRONMENT_RUN_EXTENSION_ENTRY_POINT_GROUP",
    "ArgvCommand",
    "BoundEnvironment",
    "BoundEnvironmentProvider",
    "BoundOutputCursor",
    "BoundOutputReference",
    "BoundProcessHandle",
    "CommandEnvironment",
    "CommandLimits",
    "CommandRequest",
    "CompositeBoundEnvironment",
    "CompositeEnvironmentRunBinding",
    "DynamicEnvironmentCapability",
    "DynamicEnvironmentConfiguration",
    "EnvironmentAction",
    "EnvironmentActionDispatch",
    "EnvironmentAvailability",
    "EnvironmentBinding",
    "EnvironmentBindingObservation",
    "EnvironmentBindingRequest",
    "EnvironmentBindingState",
    "EnvironmentDescriptor",
    "EnvironmentError",
    "EnvironmentMountDescriptor",
    "EnvironmentOperationFamily",
    "EnvironmentOutputCapture",
    "EnvironmentOutputPolicy",
    "EnvironmentOutputReadResult",
    "EnvironmentOutputSegment",
    "EnvironmentPath",
    "EnvironmentPermissionSet",
    "EnvironmentProviderBinding",
    "EnvironmentProviderOperations",
    "EnvironmentReadinessRequirement",
    "EnvironmentRunBinding",
    "EnvironmentRunExtension",
    "EnvironmentRunExtensionContext",
    "EnvironmentRunExtensionFactory",
    "EnvironmentRunExtensionFactoryCatalog",
    "EnvironmentRunExtensionFactoryContext",
    "EnvironmentRunExtensionFactoryReference",
    "EnvironmentRunExtensionFactoryRegistration",
    "EnvironmentState",
    "EnvironmentStateLimits",
    "EnvironmentTopology",
    "EnvironmentTopologyBindingChange",
    "EnvironmentTopologyChange",
    "EnvironmentTopologyController",
    "EnvironmentTopologyLimits",
    "EnvironmentTopologyObserver",
    "EnvironmentTopologyRequest",
    "FileCopyResult",
    "FileEntriesResult",
    "FileMetadata",
    "FileMutationResult",
    "FileOperator",
    "FilePatchResult",
    "FileQueryRequest",
    "FileScopeProvider",
    "FileScopeSelection",
    "FileTextMatch",
    "FileTextResult",
    "FileTextSearchRequest",
    "FileTextSearchResult",
    "FileWriteMode",
    "FileWriteResult",
    "NoopBoundEnvironment",
    "NoopEnvironmentRunBinding",
    "OpaqueOutputCursor",
    "OpaqueOutputReference",
    "OpaqueProcessHandle",
    "PortObservation",
    "PortTarget",
    "ProcessControlResult",
    "ProcessInfo",
    "ProcessOutputSnapshot",
    "ProcessReadOutputResult",
    "ProcessSignalResult",
    "ProcessStartResult",
    "ProcessStatus",
    "ProcessStreamRead",
    "ProcessWriteStdinResult",
    "ShellCommand",
    "ShellExecResult",
    "VirtualFileOperator",
    "build_environment_run_extension_factory_catalog",
    "create_environment_provider_binding",
    "create_environment_run_binding",
    "create_noop_environment_run_binding",
    "discover_environment_run_extension_factory_references",
]
