"""Shared environment-provider boundary for Agent Foundation agents."""

from importlib.metadata import PackageNotFoundError, version

from .attachments import (
    AcceptedWebSocketEIPSessionSource,
    DirectLocalEnvironmentAttachment,
    EIPEnvironmentAttachment,
    EIPSessionSource,
    EnvironmentRuntimeAttachment,
    HttpEIPSessionSource,
    StdioEIPCarrier,
    StdioEIPSessionSource,
)
from .direct_local.configuration import (
    DirectLocalProviderConfiguration,
    DirectLocalProviderStateData,
    DirectLocalRootConfiguration,
    DirectLocalShellProfile,
)
from .direct_local.provider import (
    DirectLocalEnvironmentProvider,
    DirectLocalEnvironmentProviderFactory,
    DirectLocalEnvironmentResource,
    DirectLocalProviderRuntime,
)
from .docker import (
    DEFAULT_DOCKER_IMAGE,
    DirectoryDockerBootstrapStore,
    DockerBindMountSource,
    DockerBootstrapAllocation,
    DockerBootstrapMaterial,
    DockerBootstrapStore,
    DockerBootstrapStoreError,
    DockerContainerInspection,
    DockerContainerSpec,
    DockerEngine,
    DockerEngineError,
    DockerEngineMount,
    DockerEnvironmentProvider,
    DockerEnvironmentProviderFactory,
    DockerEnvironmentResource,
    DockerImageInspection,
    DockerImagePullPolicy,
    DockerMountConfiguration,
    DockerMountSource,
    DockerProviderConfiguration,
    DockerProviderRuntime,
    DockerProviderStateData,
    DockerResourcePhase,
    DockerSDKEngine,
    DockerShellProfile,
    DockerVolumeMountSource,
)
from .errors import (
    EnvironmentProviderError,
    EnvironmentProviderErrorCategory,
    EnvironmentProviderErrorContext,
    EnvironmentProviderOutcomeCertainty,
    EnvironmentProviderRecoveryHint,
    EnvironmentProviderSafeError,
)
from .factories import (
    ENVIRONMENT_PROVIDER_ENTRY_POINT_GROUP,
    EnvironmentProviderFactory,
    EnvironmentProviderFactoryCatalog,
    EnvironmentProviderFactoryReference,
    EnvironmentProviderFactoryRegistration,
    ResolvedEnvironmentProviderSpec,
    build_environment_provider_factory_catalog,
    discover_environment_provider_factory_references,
)
from .local_envd import (
    A13N_AGENT_ENVD_EXECUTABLE,
    LocalEnvdEnvironmentProvider,
    LocalEnvdEnvironmentProviderFactory,
    LocalEnvdEnvironmentResource,
    LocalEnvdNetworkMode,
    LocalEnvdProviderConfiguration,
    LocalEnvdProviderRuntime,
    LocalEnvdProviderStateData,
    LocalEnvdResourcePhase,
    LocalEnvdRuntimeAllocator,
    LocalEnvdShellProfile,
    LocalEnvdWorkspaceConfiguration,
    TemporaryLocalEnvdRuntimeAllocator,
    resolve_agent_envd_executable,
)
from .management import EnvironmentProvider, EnvironmentProviderRuntime, EnvironmentResource
from .models import (
    EnvironmentAttachmentConcurrency,
    EnvironmentLifecycleCapabilities,
    EnvironmentManagementAction,
    EnvironmentOperationContext,
    EnvironmentPauseMode,
    EnvironmentProviderResourceState,
    EnvironmentProviderSpec,
    EnvironmentReconciliationPhase,
    EnvironmentReconciliationResult,
    EnvironmentResourceAllocation,
)

try:
    __version__ = version("a13n-environment-provider")
except PackageNotFoundError:  # pragma: no cover - source-tree imports without installation
    __version__ = "0.0.0"

__all__ = [
    "A13N_AGENT_ENVD_EXECUTABLE",
    "DEFAULT_DOCKER_IMAGE",
    "ENVIRONMENT_PROVIDER_ENTRY_POINT_GROUP",
    "AcceptedWebSocketEIPSessionSource",
    "DirectLocalEnvironmentAttachment",
    "DirectLocalEnvironmentProvider",
    "DirectLocalEnvironmentProviderFactory",
    "DirectLocalEnvironmentResource",
    "DirectLocalProviderConfiguration",
    "DirectLocalProviderRuntime",
    "DirectLocalProviderStateData",
    "DirectLocalRootConfiguration",
    "DirectLocalShellProfile",
    "DirectoryDockerBootstrapStore",
    "DockerBindMountSource",
    "DockerBootstrapAllocation",
    "DockerBootstrapMaterial",
    "DockerBootstrapStore",
    "DockerBootstrapStoreError",
    "DockerContainerInspection",
    "DockerContainerSpec",
    "DockerEngine",
    "DockerEngineError",
    "DockerEngineMount",
    "DockerEnvironmentProvider",
    "DockerEnvironmentProviderFactory",
    "DockerEnvironmentResource",
    "DockerImageInspection",
    "DockerImagePullPolicy",
    "DockerMountConfiguration",
    "DockerMountSource",
    "DockerProviderConfiguration",
    "DockerProviderRuntime",
    "DockerProviderStateData",
    "DockerResourcePhase",
    "DockerSDKEngine",
    "DockerShellProfile",
    "DockerVolumeMountSource",
    "EIPEnvironmentAttachment",
    "EIPSessionSource",
    "EnvironmentAttachmentConcurrency",
    "EnvironmentLifecycleCapabilities",
    "EnvironmentManagementAction",
    "EnvironmentOperationContext",
    "EnvironmentPauseMode",
    "EnvironmentProvider",
    "EnvironmentProviderError",
    "EnvironmentProviderErrorCategory",
    "EnvironmentProviderErrorContext",
    "EnvironmentProviderFactory",
    "EnvironmentProviderFactoryCatalog",
    "EnvironmentProviderFactoryReference",
    "EnvironmentProviderFactoryRegistration",
    "EnvironmentProviderOutcomeCertainty",
    "EnvironmentProviderRecoveryHint",
    "EnvironmentProviderResourceState",
    "EnvironmentProviderRuntime",
    "EnvironmentProviderSafeError",
    "EnvironmentProviderSpec",
    "EnvironmentReconciliationPhase",
    "EnvironmentReconciliationResult",
    "EnvironmentResource",
    "EnvironmentResourceAllocation",
    "EnvironmentRuntimeAttachment",
    "HttpEIPSessionSource",
    "LocalEnvdEnvironmentProvider",
    "LocalEnvdEnvironmentProviderFactory",
    "LocalEnvdEnvironmentResource",
    "LocalEnvdNetworkMode",
    "LocalEnvdProviderConfiguration",
    "LocalEnvdProviderRuntime",
    "LocalEnvdProviderStateData",
    "LocalEnvdResourcePhase",
    "LocalEnvdRuntimeAllocator",
    "LocalEnvdShellProfile",
    "LocalEnvdWorkspaceConfiguration",
    "ResolvedEnvironmentProviderSpec",
    "StdioEIPCarrier",
    "StdioEIPSessionSource",
    "TemporaryLocalEnvdRuntimeAllocator",
    "__version__",
    "build_environment_provider_factory_catalog",
    "discover_environment_provider_factory_references",
    "resolve_agent_envd_executable",
]
