"""Model heads, immutable revisions, provider discovery, and execution snapshots."""

from .domain import (
    CapabilitySource,
    CreateModelRequest,
    CreateModelRevisionRequest,
    InvokingUserSecretCredential,
    Model,
    ModelCapabilities,
    ModelCollection,
    ModelConnectionTestResult,
    ModelCredential,
    ModelExecutionObservation,
    ModelExecutionSnapshot,
    ModelRevision,
    ModelRevisionCreateResult,
    ModelRevisionInput,
    NoCredential,
    PrincipalRef,
    UpdateModelRequest,
    WorkspaceSecretCredential,
    new_model_id,
    new_model_revision_id,
)
from .providers import ProviderDefinition, ProviderRegistry, built_in_provider_registry

__all__ = [
    "CapabilitySource",
    "CreateModelRequest",
    "CreateModelRevisionRequest",
    "InvokingUserSecretCredential",
    "Model",
    "ModelCapabilities",
    "ModelCollection",
    "ModelConnectionTestResult",
    "ModelCredential",
    "ModelExecutionObservation",
    "ModelExecutionSnapshot",
    "ModelRevision",
    "ModelRevisionCreateResult",
    "ModelRevisionInput",
    "NoCredential",
    "PrincipalRef",
    "ProviderDefinition",
    "ProviderRegistry",
    "UpdateModelRequest",
    "WorkspaceSecretCredential",
    "built_in_provider_registry",
    "new_model_id",
    "new_model_revision_id",
]
