"""align run connector connection selections.

Revision ID: ed8e43676759
Revises: 93062df87c6a
Create Date: 2026-09-03 04:14:10.915079+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ed8e43676759"
down_revision: str | Sequence[str] | None = "93062df87c6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "runs",
        "connection_selections_json",
        new_column_name="connector_connection_selections_json",
        existing_type=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "runs",
        "connector_connection_selections_json",
        new_column_name="connection_selections_json",
        existing_type=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
