"""extend managed secret owners.

Revision ID: 78dafda55dd5
Revises: ed8e43676759
Create Date: 2026-09-03 04:23:32.142323+00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "78dafda55dd5"
down_revision: str | Sequence[str] | None = "ed8e43676759"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets") as batch_op:
        batch_op.drop_constraint(op.f("ck_secrets_owner_type_valid"), type_="check")
        batch_op.create_check_constraint(
            op.f("ck_secrets_owner_type_valid"),
            "owner_type IN ('workspace', 'user', 'ingress', 'connector', 'mcp_connection', 'a2a_push_configuration')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets") as batch_op:
        batch_op.drop_constraint(op.f("ck_secrets_owner_type_valid"), type_="check")
        batch_op.create_check_constraint(
            op.f("ck_secrets_owner_type_valid"),
            "owner_type IN ('workspace', 'user')",
        )
    # ### end Alembic commands ###
