"""add plugin runtime locks.

Revision ID: 4d180002f87e
Revises: 43f21e937953
Create Date: 2026-09-02 02:47:43.872385+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4d180002f87e"
down_revision: str | Sequence[str] | None = "43f21e937953"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_runtime_locks",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mode IN ('on_demand', 'runner')", name=op.f("ck_plugin_runtime_locks_mode_valid")),
        sa.CheckConstraint("schema_version = '1'", name=op.f("ck_plugin_runtime_locks_schema_version_v1")),
        sa.CheckConstraint("length(digest) = 64", name=op.f("ck_plugin_runtime_locks_digest_sha256")),
        sa.PrimaryKeyConstraint("digest", name=op.f("pk_plugin_runtime_locks")),
    )
    op.create_index("ix_plugin_runtime_locks_created", "plugin_runtime_locks", ["created_at", "digest"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plugin_runtime_locks_created", table_name="plugin_runtime_locks")
    op.drop_table("plugin_runtime_locks")
    # ### end Alembic commands ###
