"""add connectivity subsystem.

Revision ID: c2b68dc827b5
Revises: 93f7e255236d
Create Date: 2026-09-03 13:38:32.998224+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c2b68dc827b5"
down_revision: str | Sequence[str] | None = "93f7e255236d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets") as batch_op:
        batch_op.drop_constraint(op.f("ck_secrets_owner_type_valid"), type_="check")
        batch_op.create_check_constraint(
            op.f("ck_secrets_owner_type_valid"),
            "owner_type IN ('workspace', 'user', 'ingress', 'connector', 'mcp_connection', 'a2a_push_configuration')",
        )
    op.create_table(
        "connectivity_commands",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=72), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("scope_id", sa.String(length=72), nullable=False),
        sa.Column("idempotency_key_digest", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=72), nullable=False),
        sa.Column("result_version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'service_account')", name=op.f("ck_connectivity_commands_actor_type_valid")
        ),
        sa.CheckConstraint("result_version >= 1", name=op.f("ck_connectivity_commands_result_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectivity_commands")),
    )
    op.create_index(
        "ix_connectivity_commands_resource",
        "connectivity_commands",
        ["resource_type", "resource_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_connectivity_commands_request",
        "connectivity_commands",
        ["workspace_id", "actor_type", "actor_id", "operation", "scope_id", "idempotency_key_digest"],
        unique=True,
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("driver_key", sa.String(length=64), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=2048), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("credential_secret_id", sa.String(length=72), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_connectors_created_by_type_valid")
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_connectors_status_valid")),
        sa.CheckConstraint("credential_generation >= 1", name=op.f("ck_connectors_credential_generation_positive")),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_connectors_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_connectors_version_positive")),
        sa.ForeignKeyConstraint(
            ["credential_secret_id"],
            ["secrets.id"],
            name=op.f("fk_connectors_credential_secret_id_secrets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_connectors_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
    )
    op.create_index("ix_connectors_driver_status", "connectors", ["driver_key", "status", "id"], unique=False)
    op.create_index("ix_connectors_workspace_updated", "connectors", ["workspace_id", "updated_at", "id"], unique=False)
    op.create_index("uq_connectors_id_tenant", "connectors", ["id", "organization_id", "workspace_id"], unique=True)
    op.create_index("uq_connectors_workspace_name", "connectors", ["workspace_id", "normalized_name"], unique=True)
    op.create_table(
        "ingresses",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("provider_config_json", sa.JSON(), nullable=False),
        sa.Column("execution_service_account_id", sa.String(length=72), nullable=False),
        sa.Column("default_agent_id", sa.String(length=72), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("credential_secret_id", sa.String(length=72), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_ingresses_created_by_type_valid")
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_ingresses_status_valid")),
        sa.CheckConstraint("credential_generation >= 1", name=op.f("ck_ingresses_credential_generation_positive")),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_ingresses_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ingresses_version_positive")),
        sa.ForeignKeyConstraint(
            ["credential_secret_id"],
            ["secrets.id"],
            name=op.f("fk_ingresses_credential_secret_id_secrets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["default_agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingresses_default_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_service_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_ingresses_execution_service_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_ingresses_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingresses")),
    )
    op.create_index("ix_ingresses_provider_status", "ingresses", ["provider_key", "status", "id"], unique=False)
    op.create_index("ix_ingresses_workspace_updated", "ingresses", ["workspace_id", "updated_at", "id"], unique=False)
    op.create_index("uq_ingresses_id_tenant", "ingresses", ["id", "organization_id", "workspace_id"], unique=True)
    op.create_index("uq_ingresses_workspace_name", "ingresses", ["workspace_id", "normalized_name"], unique=True)
    op.create_table(
        "mcp_connections",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("owner_user_id", sa.String(length=72), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2048), nullable=False),
        sa.Column("auth_mode", sa.String(length=32), nullable=False),
        sa.Column("static_header_names_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.String(length=32), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("credential_secret_id", sa.String(length=72), nullable=True),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("catalog_generation", sa.BigInteger(), nullable=False),
        sa.Column("current_catalog_digest", sa.String(length=64), nullable=True),
        sa.Column("catalog_claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("catalog_claim_owner", sa.String(length=128), nullable=True),
        sa.Column("catalog_claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("catalog_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("catalog_last_error_code", sa.String(length=128), nullable=True),
        sa.Column("cleanup_pending", sa.Boolean(), nullable=False),
        sa.Column("cleanup_attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("cleanup_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleanup_last_error_code", sa.String(length=128), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'action_required') = (status_reason IS NOT NULL)",
            name=op.f("ck_mcp_connections_status_reason_valid"),
        ),
        sa.CheckConstraint(
            "auth_mode IN ('none', 'bearer', 'oauth', 'static_headers')",
            name=op.f("ck_mcp_connections_auth_mode_valid"),
        ),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_mcp_connections_created_by_type_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'action_required', 'disabled')",
            name=op.f("ck_mcp_connections_status_valid"),
        ),
        sa.CheckConstraint(
            "status_reason IS NULL OR status_reason IN ('reauthorization_required', 'incompatible')",
            name=op.f("ck_mcp_connections_status_reason_value_valid"),
        ),
        sa.CheckConstraint(
            "catalog_claim_generation >= 0", name=op.f("ck_mcp_connections_catalog_claim_generation_non_negative")
        ),
        sa.CheckConstraint("catalog_generation >= 0", name=op.f("ck_mcp_connections_catalog_generation_non_negative")),
        sa.CheckConstraint(
            "cleanup_attempt_count >= 0", name=op.f("ck_mcp_connections_cleanup_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "credential_generation >= 0", name=op.f("ck_mcp_connections_credential_generation_non_negative")
        ),
        sa.CheckConstraint(
            "current_catalog_digest IS NULL OR length(current_catalog_digest) = 64",
            name=op.f("ck_mcp_connections_current_catalog_digest_valid"),
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_mcp_connections_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_mcp_connections_version_positive")),
        sa.ForeignKeyConstraint(
            ["credential_secret_id"],
            ["secrets.id"],
            name=op.f("fk_mcp_connections_credential_secret_id_secrets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_mcp_connections_owner_user_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_mcp_connections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_connections")),
    )
    op.create_index(
        "ix_mcp_connections_catalog_reconcile",
        "mcp_connections",
        ["status", "catalog_available_at", "catalog_claim_expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_connections_cleanup", "mcp_connections", ["cleanup_pending", "cleanup_available_at", "id"], unique=False
    )
    op.create_index(
        "ix_mcp_connections_owner", "mcp_connections", ["workspace_id", "owner_user_id", "status", "id"], unique=False
    )
    op.create_index(
        "ix_mcp_connections_workspace_updated", "mcp_connections", ["workspace_id", "updated_at", "id"], unique=False
    )
    op.create_index(
        "uq_mcp_connections_id_tenant", "mcp_connections", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_index(
        "uq_mcp_connections_workspace_name", "mcp_connections", ["workspace_id", "normalized_name"], unique=True
    )
    op.create_table(
        "agent_thread_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("external_ref_kind", sa.String(length=128), nullable=False),
        sa.Column("external_ref_id", sa.String(length=2048), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("thread_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_agent_thread_bindings_version_positive")),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_agent_thread_bindings_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_agent_thread_bindings_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "thread_id"],
            ["threads.tenant_id", "threads.id"],
            name=op.f("fk_agent_thread_bindings_organization_id_threads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_thread_bindings")),
        sa.UniqueConstraint(
            "ingress_id", "external_ref_kind", "external_ref_id", name="uq_agent_thread_bindings_external_ref"
        ),
    )
    op.create_index(
        "ix_agent_thread_bindings_thread", "agent_thread_bindings", ["organization_id", "thread_id", "id"], unique=False
    )
    op.create_index(
        "uq_agent_thread_bindings_id_tenant",
        "agent_thread_bindings",
        ["id", "organization_id", "workspace_id"],
        unique=True,
    )
    op.create_table(
        "connector_connections",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_id", sa.String(length=72), nullable=False),
        sa.Column("owner_type", sa.String(length=32), nullable=True),
        sa.Column("owner_id", sa.String(length=72), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("provider_key", sa.String(length=128), nullable=False),
        sa.Column("external_ref", sa.String(length=2048), nullable=True),
        sa.Column("safe_metadata_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.String(length=32), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("setup_generation", sa.BigInteger(), nullable=False),
        sa.Column("revoke_generation", sa.BigInteger(), nullable=False),
        sa.Column("catalog_generation", sa.BigInteger(), nullable=False),
        sa.Column("current_catalog_digest", sa.String(length=64), nullable=True),
        sa.Column("catalog_attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("catalog_claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("catalog_claim_owner", sa.String(length=128), nullable=True),
        sa.Column("catalog_claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("catalog_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("catalog_last_error_code", sa.String(length=128), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'action_required') = (status_reason IS NOT NULL)",
            name=op.f("ck_connector_connections_status_reason_valid"),
        ),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')",
            name=op.f("ck_connector_connections_created_by_type_valid"),
        ),
        sa.CheckConstraint(
            "owner_type IS NULL OR owner_type IN ('user', 'service_account')",
            name=op.f("ck_connector_connections_owner_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'disabled') OR external_ref IS NOT NULL",
            name=op.f("ck_connector_connections_external_ref_required_when_bound"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'action_required', 'disabled')",
            name=op.f("ck_connector_connections_status_valid"),
        ),
        sa.CheckConstraint(
            "(owner_type IS NULL) = (owner_id IS NULL)", name=op.f("ck_connector_connections_owner_complete")
        ),
        sa.CheckConstraint(
            "catalog_attempt_count >= 0", name=op.f("ck_connector_connections_catalog_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "catalog_claim_generation >= 0", name=op.f("ck_connector_connections_catalog_claim_generation_non_negative")
        ),
        sa.CheckConstraint(
            "catalog_generation >= 0", name=op.f("ck_connector_connections_catalog_generation_non_negative")
        ),
        sa.CheckConstraint(
            "current_catalog_digest IS NULL OR length(current_catalog_digest) = 64",
            name=op.f("ck_connector_connections_current_catalog_digest_valid"),
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_connector_connections_name_bounded")),
        sa.CheckConstraint(
            "revoke_generation >= 0", name=op.f("ck_connector_connections_revoke_generation_non_negative")
        ),
        sa.CheckConstraint("setup_generation >= 1", name=op.f("ck_connector_connections_setup_generation_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_connector_connections_version_positive")),
        sa.ForeignKeyConstraint(
            ["connector_id", "organization_id", "workspace_id"],
            ["connectors.id", "connectors.organization_id", "connectors.workspace_id"],
            name=op.f("fk_connector_connections_connector_id_connectors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_connections")),
    )
    op.create_index(
        "ix_connector_connections_connector_status",
        "connector_connections",
        ["connector_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "ix_connector_connections_owner",
        "connector_connections",
        ["workspace_id", "owner_type", "owner_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "ix_connector_connections_workspace_updated",
        "connector_connections",
        ["workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_connector_connections_external_ref", "connector_connections", ["connector_id", "external_ref"], unique=True
    )
    op.create_index(
        "uq_connector_connections_id_tenant",
        "connector_connections",
        ["id", "organization_id", "workspace_id"],
        unique=True,
    )
    op.create_index(
        "uq_connector_connections_workspace_name",
        "connector_connections",
        ["workspace_id", "normalized_name"],
        unique=True,
    )
    op.create_table(
        "ingress_agents",
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingress_agents_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_ingress_agents_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ingress_id", "agent_id", name=op.f("pk_ingress_agents")),
    )
    op.create_index(
        "ix_ingress_agents_agent", "ingress_agents", ["workspace_id", "agent_id", "ingress_id"], unique=False
    )
    op.create_table(
        "ingress_batches",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("compatibility_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("event_count", sa.BigInteger(), nullable=False),
        sa.Column("event_bytes", sa.BigInteger(), nullable=False),
        sa.Column("append_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_kind", sa.String(length=32), nullable=True),
        sa.Column("result_id", sa.String(length=72), nullable=True),
        sa.Column("rejection_reason", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')", name=op.f("ck_ingress_batches_status_valid")
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_ingress_batches_attempt_count_non_negative")),
        sa.CheckConstraint("claim_generation >= 0", name=op.f("ck_ingress_batches_claim_generation_non_negative")),
        sa.CheckConstraint("event_bytes >= 0", name=op.f("ck_ingress_batches_event_bytes_non_negative")),
        sa.CheckConstraint("event_count >= 1", name=op.f("ck_ingress_batches_event_count_positive")),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_ingress_batches_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_batches")),
    )
    op.create_index(
        "ix_ingress_batches_claim",
        "ingress_batches",
        ["status", "available_at", "claim_expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_ingress_batches_compatible",
        "ingress_batches",
        ["ingress_id", "compatibility_digest", "status", "created_at", "id"],
        unique=False,
    )
    op.create_index("ix_ingress_batches_retention", "ingress_batches", ["status", "terminal_at", "id"], unique=False)
    op.create_index(
        "uq_ingress_batches_id_tenant", "ingress_batches", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_table(
        "ingress_routes",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("match_json", sa.JSON(), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=True),
        sa.Column("input_mapping_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("min_interval_ms", sa.BigInteger(), nullable=False),
        sa.Column("max_batch_events", sa.BigInteger(), nullable=False),
        sa.Column("capability_overlays_json", sa.JSON(), nullable=False),
        sa.Column("provider_policy_json", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_ingress_routes_created_by_type_valid")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_ingress_routes_name_bounded")),
        sa.CheckConstraint("max_batch_events >= 1", name=op.f("ck_ingress_routes_max_batch_events_positive")),
        sa.CheckConstraint("min_interval_ms >= 1", name=op.f("ck_ingress_routes_min_interval_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ingress_routes_version_positive")),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingress_routes_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_ingress_routes_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_routes")),
        sa.UniqueConstraint("ingress_id", "normalized_name", name="uq_ingress_routes_ingress_name"),
    )
    op.create_index(
        "ix_ingress_routes_listing", "ingress_routes", ["ingress_id", "enabled", "updated_at", "id"], unique=False
    )
    op.create_index(
        "uq_ingress_routes_id_tenant", "ingress_routes", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_table(
        "mcp_oauth_sessions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("mcp_connection_id", sa.String(length=72), nullable=False),
        sa.Column("initiating_user_id", sa.String(length=72), nullable=False),
        sa.Column("state_digest", sa.String(length=64), nullable=False),
        sa.Column("resource_url", sa.String(length=2048), nullable=False),
        sa.Column("issuer_url", sa.String(length=2048), nullable=False),
        sa.Column("authorization_endpoint", sa.String(length=2048), nullable=False),
        sa.Column("token_endpoint", sa.String(length=2048), nullable=False),
        sa.Column("registration_endpoint", sa.String(length=2048), nullable=True),
        sa.Column("client_id", sa.String(length=2048), nullable=True),
        sa.Column("scope", sa.String(length=2048), nullable=True),
        sa.Column("setup_secret_id", sa.String(length=72), nullable=False),
        sa.Column("setup_secret_generation", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'exchanging', 'completed', 'failed', 'expired')",
            name=op.f("ck_mcp_oauth_sessions_status_valid"),
        ),
        sa.CheckConstraint("claim_generation >= 0", name=op.f("ck_mcp_oauth_sessions_claim_generation_non_negative")),
        sa.ForeignKeyConstraint(
            ["initiating_user_id"],
            ["users.id"],
            name=op.f("fk_mcp_oauth_sessions_initiating_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mcp_connection_id", "organization_id", "workspace_id"],
            ["mcp_connections.id", "mcp_connections.organization_id", "mcp_connections.workspace_id"],
            name=op.f("fk_mcp_oauth_sessions_mcp_connection_id_mcp_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["setup_secret_id"],
            ["secrets.id"],
            name=op.f("fk_mcp_oauth_sessions_setup_secret_id_secrets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_oauth_sessions")),
    )
    op.create_index(
        "ix_mcp_oauth_sessions_connection",
        "mcp_oauth_sessions",
        ["mcp_connection_id", "status", "created_at", "id"],
        unique=False,
    )
    op.create_index("ix_mcp_oauth_sessions_expiry", "mcp_oauth_sessions", ["status", "expires_at", "id"], unique=False)
    op.create_index("uq_mcp_oauth_sessions_state", "mcp_oauth_sessions", ["state_digest"], unique=True)
    op.create_table(
        "mcp_tool_catalogs",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("mcp_connection_id", sa.String(length=72), nullable=False),
        sa.Column("digest_sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("tool_count", sa.BigInteger(), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("catalog_generation", sa.BigInteger(), nullable=False),
        sa.Column("protocol_revision", sa.String(length=32), nullable=False),
        sa.Column("server_name", sa.String(length=128), nullable=False),
        sa.Column("server_version", sa.String(length=128), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("catalog_generation >= 1", name=op.f("ck_mcp_tool_catalogs_catalog_generation_positive")),
        sa.CheckConstraint(
            "credential_generation >= 0", name=op.f("ck_mcp_tool_catalogs_credential_generation_non_negative")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_mcp_tool_catalogs_size_bytes_positive")),
        sa.CheckConstraint("tool_count >= 0", name=op.f("ck_mcp_tool_catalogs_tool_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["mcp_connection_id", "organization_id", "workspace_id"],
            ["mcp_connections.id", "mcp_connections.organization_id", "mcp_connections.workspace_id"],
            name=op.f("fk_mcp_tool_catalogs_mcp_connection_id_mcp_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_tool_catalogs")),
    )
    op.create_index(
        "ix_mcp_tool_catalogs_latest", "mcp_tool_catalogs", ["mcp_connection_id", "published_at", "id"], unique=False
    )
    op.create_index("ix_mcp_tool_catalogs_retention", "mcp_tool_catalogs", ["retain_until", "id"], unique=False)
    op.create_index(
        "uq_mcp_tool_catalogs_digest", "mcp_tool_catalogs", ["mcp_connection_id", "digest_sha256"], unique=True
    )
    op.create_table(
        "connector_connection_operations",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_connection_id", sa.String(length=72), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('revoke')", name=op.f("ck_connector_connection_operations_kind_valid")),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'unknown', 'failed')",
            name=op.f("ck_connector_connection_operations_status_valid"),
        ),
        sa.CheckConstraint(
            "claim_generation >= 0", name=op.f("ck_connector_connection_operations_claim_generation_valid")
        ),
        sa.CheckConstraint("generation >= 1", name=op.f("ck_connector_connection_operations_generation_positive")),
        sa.ForeignKeyConstraint(
            ["connector_connection_id", "organization_id", "workspace_id"],
            ["connector_connections.id", "connector_connections.organization_id", "connector_connections.workspace_id"],
            name=op.f("fk_connector_connection_operations_connector_connection_id_connector_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_connection_operations")),
    )
    op.create_index(
        "ix_connector_connection_operations_reconcile",
        "connector_connection_operations",
        ["status", "available_at", "claim_expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_connector_connection_operations_generation",
        "connector_connection_operations",
        ["connector_connection_id", "kind", "generation"],
        unique=True,
    )
    op.create_table(
        "connector_setup_attempts",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_connection_id", sa.String(length=72), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("initiating_principal_type", sa.String(length=32), nullable=False),
        sa.Column("initiating_principal_id", sa.String(length=72), nullable=False),
        sa.Column("owner_type", sa.String(length=32), nullable=True),
        sa.Column("owner_id", sa.String(length=72), nullable=True),
        sa.Column("driver_key", sa.String(length=64), nullable=False),
        sa.Column("provider_key", sa.String(length=128), nullable=False),
        sa.Column("external_user_correlation", sa.String(length=128), nullable=False),
        sa.Column("state_digest", sa.String(length=64), nullable=False),
        sa.Column("return_path", sa.String(length=2048), nullable=False),
        sa.Column("setup_json", sa.JSON(), nullable=False),
        sa.Column("external_ref", sa.String(length=2048), nullable=True),
        sa.Column("external_handle_digest", sa.String(length=64), nullable=True),
        sa.Column("supports_verified_callback", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "initiating_principal_type = 'user'", name=op.f("ck_connector_setup_attempts_initiating_user_required")
        ),
        sa.CheckConstraint(
            "owner_type IS NULL OR owner_type IN ('user', 'service_account')",
            name=op.f("ck_connector_setup_attempts_owner_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'attached', 'reserved', 'completed', 'failed', 'expired')",
            name=op.f("ck_connector_setup_attempts_status_valid"),
        ),
        sa.CheckConstraint(
            "(owner_type IS NULL) = (owner_id IS NULL)", name=op.f("ck_connector_setup_attempts_owner_complete")
        ),
        sa.CheckConstraint(
            "claim_generation >= 0", name=op.f("ck_connector_setup_attempts_claim_generation_non_negative")
        ),
        sa.CheckConstraint("generation >= 1", name=op.f("ck_connector_setup_attempts_generation_positive")),
        sa.ForeignKeyConstraint(
            ["connector_connection_id", "organization_id", "workspace_id"],
            ["connector_connections.id", "connector_connections.organization_id", "connector_connections.workspace_id"],
            name=op.f("fk_connector_setup_attempts_connector_connection_id_connector_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_setup_attempts")),
    )
    op.create_index(
        "ix_connector_setup_attempts_expiry", "connector_setup_attempts", ["expires_at", "status", "id"], unique=False
    )
    op.create_index(
        "ix_connector_setup_attempts_reconcile",
        "connector_setup_attempts",
        ["status", "available_at", "claim_expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_connector_setup_attempts_connection_generation",
        "connector_setup_attempts",
        ["connector_connection_id", "generation"],
        unique=True,
    )
    op.create_table(
        "connector_tool_catalogs",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_connection_id", sa.String(length=72), nullable=False),
        sa.Column("digest_sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("tool_count", sa.BigInteger(), nullable=False),
        sa.Column("connector_credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("connection_setup_generation", sa.BigInteger(), nullable=False),
        sa.Column("compatibility_profile", sa.String(length=128), nullable=False),
        sa.Column("provider_version", sa.String(length=128), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "connection_setup_generation >= 1",
            name=op.f("ck_connector_tool_catalogs_connection_setup_generation_positive"),
        ),
        sa.CheckConstraint(
            "connector_credential_generation >= 1",
            name=op.f("ck_connector_tool_catalogs_credential_generation_positive"),
        ),
        sa.CheckConstraint("length(digest_sha256) = 64", name=op.f("ck_connector_tool_catalogs_digest_bounded")),
        sa.CheckConstraint("size_bytes >= 1", name=op.f("ck_connector_tool_catalogs_size_positive")),
        sa.CheckConstraint("tool_count >= 0", name=op.f("ck_connector_tool_catalogs_tool_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["connector_connection_id", "organization_id", "workspace_id"],
            ["connector_connections.id", "connector_connections.organization_id", "connector_connections.workspace_id"],
            name=op.f("fk_connector_tool_catalogs_connector_connection_id_connector_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_tool_catalogs")),
    )
    op.create_index(
        "ix_connector_tool_catalogs_latest",
        "connector_tool_catalogs",
        ["connector_connection_id", "published_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_connector_tool_catalogs_retention", "connector_tool_catalogs", ["retain_until", "id"], unique=False
    )
    op.create_index(
        "uq_connector_tool_catalogs_digest",
        "connector_tool_catalogs",
        ["connector_connection_id", "digest_sha256"],
        unique=True,
    )
    op.create_table(
        "ingress_admissions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("ingress_version", sa.BigInteger(), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("route_id", sa.String(length=72), nullable=True),
        sa.Column("route_version", sa.BigInteger(), nullable=True),
        sa.Column("event_identity_kind", sa.String(length=128), nullable=False),
        sa.Column("event_identity_digest", sa.String(length=64), nullable=False),
        sa.Column("protected_event_identity", sa.String(length=2048), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("normalization_version", sa.String(length=128), nullable=False),
        sa.Column("event_json", sa.JSON(), nullable=False),
        sa.Column("ordering_key", sa.String(length=2048), nullable=False),
        sa.Column("raw_ref_json", sa.JSON(), nullable=True),
        sa.Column("selected_agent_id", sa.String(length=72), nullable=True),
        sa.Column("external_ref_kind", sa.String(length=128), nullable=True),
        sa.Column("external_ref_id", sa.String(length=2048), nullable=True),
        sa.Column("binding_state", sa.String(length=16), nullable=False),
        sa.Column("binding_id", sa.String(length=72), nullable=True),
        sa.Column("mapping_json", sa.JSON(), nullable=True),
        sa.Column("mapping_digest", sa.String(length=64), nullable=True),
        sa.Column("min_interval_ms", sa.BigInteger(), nullable=False),
        sa.Column("max_batch_events", sa.BigInteger(), nullable=False),
        sa.Column("provider_context_json", sa.JSON(), nullable=False),
        sa.Column("provider_policy_json", sa.JSON(), nullable=False),
        sa.Column("native_actions_json", sa.JSON(), nullable=False),
        sa.Column("capability_overlay_json", sa.JSON(), nullable=True),
        sa.Column("compatibility_digest", sa.String(length=64), nullable=False),
        sa.Column("event_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_kind", sa.String(length=32), nullable=True),
        sa.Column("result_id", sa.String(length=72), nullable=True),
        sa.Column("rejection_reason", sa.String(length=128), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedup_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "binding_state IN ('bound', 'unbound')", name=op.f("ck_ingress_admissions_binding_state_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')", name=op.f("ck_ingress_admissions_status_valid")
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_ingress_admissions_attempt_count_non_negative")),
        sa.CheckConstraint("claim_generation >= 0", name=op.f("ck_ingress_admissions_claim_generation_non_negative")),
        sa.CheckConstraint("event_size_bytes >= 0", name=op.f("ck_ingress_admissions_event_size_non_negative")),
        sa.CheckConstraint("max_batch_events >= 1", name=op.f("ck_ingress_admissions_max_batch_events_positive")),
        sa.CheckConstraint("min_interval_ms >= 1", name=op.f("ck_ingress_admissions_min_interval_positive")),
        sa.ForeignKeyConstraint(
            ["binding_id", "organization_id", "workspace_id"],
            ["agent_thread_bindings.id", "agent_thread_bindings.organization_id", "agent_thread_bindings.workspace_id"],
            name=op.f("fk_ingress_admissions_binding_id_agent_thread_bindings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_ingress_admissions_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_id", "organization_id", "workspace_id"],
            ["ingress_routes.id", "ingress_routes.organization_id", "ingress_routes.workspace_id"],
            name=op.f("fk_ingress_admissions_route_id_ingress_routes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["selected_agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingress_admissions_selected_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_admissions")),
        sa.UniqueConstraint(
            "ingress_id", "event_identity_kind", "event_identity_digest", name="uq_ingress_admissions_identity"
        ),
    )
    op.create_index(
        "ix_ingress_admissions_capacity",
        "ingress_admissions",
        ["workspace_id", "ingress_id", "status", "event_size_bytes"],
        unique=False,
    )
    op.create_index(
        "ix_ingress_admissions_pending", "ingress_admissions", ["status", "available_at", "id"], unique=False
    )
    op.create_index(
        "ix_ingress_admissions_retention", "ingress_admissions", ["status", "dedup_expires_at", "id"], unique=False
    )
    op.create_index(
        "uq_ingress_admissions_id_tenant", "ingress_admissions", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_table(
        "ingress_batch_events",
        sa.Column("batch_id", sa.String(length=72), nullable=False),
        sa.Column("admission_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("ordering_key", sa.String(length=2048), nullable=False),
        sa.ForeignKeyConstraint(
            ["admission_id", "organization_id", "workspace_id"],
            ["ingress_admissions.id", "ingress_admissions.organization_id", "ingress_admissions.workspace_id"],
            name=op.f("fk_ingress_batch_events_admission_id_ingress_admissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["batch_id", "organization_id", "workspace_id"],
            ["ingress_batches.id", "ingress_batches.organization_id", "ingress_batches.workspace_id"],
            name=op.f("fk_ingress_batch_events_batch_id_ingress_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("batch_id", "admission_id", name=op.f("pk_ingress_batch_events")),
        sa.UniqueConstraint("admission_id", name="uq_ingress_batch_events_admission"),
    )
    op.create_index(
        "ix_ingress_batch_events_order",
        "ingress_batch_events",
        ["batch_id", "ordering_key", "admission_id"],
        unique=False,
    )
    op.alter_column(
        "runs",
        "connection_selections_json",
        new_column_name="connector_connection_selections_json",
        existing_type=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "runs",
        "connector_connection_selections_json",
        new_column_name="connection_selections_json",
        existing_type=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_index("ix_ingress_batch_events_order", table_name="ingress_batch_events")
    op.drop_table("ingress_batch_events")
    op.drop_index("uq_ingress_admissions_id_tenant", table_name="ingress_admissions")
    op.drop_index("ix_ingress_admissions_retention", table_name="ingress_admissions")
    op.drop_index("ix_ingress_admissions_pending", table_name="ingress_admissions")
    op.drop_index("ix_ingress_admissions_capacity", table_name="ingress_admissions")
    op.drop_table("ingress_admissions")
    op.drop_index("uq_connector_tool_catalogs_digest", table_name="connector_tool_catalogs")
    op.drop_index("ix_connector_tool_catalogs_retention", table_name="connector_tool_catalogs")
    op.drop_index("ix_connector_tool_catalogs_latest", table_name="connector_tool_catalogs")
    op.drop_table("connector_tool_catalogs")
    op.drop_index("uq_connector_setup_attempts_connection_generation", table_name="connector_setup_attempts")
    op.drop_index("ix_connector_setup_attempts_reconcile", table_name="connector_setup_attempts")
    op.drop_index("ix_connector_setup_attempts_expiry", table_name="connector_setup_attempts")
    op.drop_table("connector_setup_attempts")
    op.drop_index("uq_connector_connection_operations_generation", table_name="connector_connection_operations")
    op.drop_index("ix_connector_connection_operations_reconcile", table_name="connector_connection_operations")
    op.drop_table("connector_connection_operations")
    op.drop_index("uq_mcp_tool_catalogs_digest", table_name="mcp_tool_catalogs")
    op.drop_index("ix_mcp_tool_catalogs_retention", table_name="mcp_tool_catalogs")
    op.drop_index("ix_mcp_tool_catalogs_latest", table_name="mcp_tool_catalogs")
    op.drop_table("mcp_tool_catalogs")
    op.drop_index("uq_mcp_oauth_sessions_state", table_name="mcp_oauth_sessions")
    op.drop_index("ix_mcp_oauth_sessions_expiry", table_name="mcp_oauth_sessions")
    op.drop_index("ix_mcp_oauth_sessions_connection", table_name="mcp_oauth_sessions")
    op.drop_table("mcp_oauth_sessions")
    op.drop_index("uq_ingress_routes_id_tenant", table_name="ingress_routes")
    op.drop_index("ix_ingress_routes_listing", table_name="ingress_routes")
    op.drop_table("ingress_routes")
    op.drop_index("uq_ingress_batches_id_tenant", table_name="ingress_batches")
    op.drop_index("ix_ingress_batches_retention", table_name="ingress_batches")
    op.drop_index("ix_ingress_batches_compatible", table_name="ingress_batches")
    op.drop_index("ix_ingress_batches_claim", table_name="ingress_batches")
    op.drop_table("ingress_batches")
    op.drop_index("ix_ingress_agents_agent", table_name="ingress_agents")
    op.drop_table("ingress_agents")
    op.drop_index("uq_connector_connections_workspace_name", table_name="connector_connections")
    op.drop_index("uq_connector_connections_id_tenant", table_name="connector_connections")
    op.drop_index("uq_connector_connections_external_ref", table_name="connector_connections")
    op.drop_index("ix_connector_connections_workspace_updated", table_name="connector_connections")
    op.drop_index("ix_connector_connections_owner", table_name="connector_connections")
    op.drop_index("ix_connector_connections_connector_status", table_name="connector_connections")
    op.drop_table("connector_connections")
    op.drop_index("uq_agent_thread_bindings_id_tenant", table_name="agent_thread_bindings")
    op.drop_index("ix_agent_thread_bindings_thread", table_name="agent_thread_bindings")
    op.drop_table("agent_thread_bindings")
    op.drop_index("uq_mcp_connections_workspace_name", table_name="mcp_connections")
    op.drop_index("uq_mcp_connections_id_tenant", table_name="mcp_connections")
    op.drop_index("ix_mcp_connections_workspace_updated", table_name="mcp_connections")
    op.drop_index("ix_mcp_connections_owner", table_name="mcp_connections")
    op.drop_index("ix_mcp_connections_cleanup", table_name="mcp_connections")
    op.drop_index("ix_mcp_connections_catalog_reconcile", table_name="mcp_connections")
    op.drop_table("mcp_connections")
    op.drop_index("uq_ingresses_workspace_name", table_name="ingresses")
    op.drop_index("uq_ingresses_id_tenant", table_name="ingresses")
    op.drop_index("ix_ingresses_workspace_updated", table_name="ingresses")
    op.drop_index("ix_ingresses_provider_status", table_name="ingresses")
    op.drop_table("ingresses")
    op.drop_index("uq_connectors_workspace_name", table_name="connectors")
    op.drop_index("uq_connectors_id_tenant", table_name="connectors")
    op.drop_index("ix_connectors_workspace_updated", table_name="connectors")
    op.drop_index("ix_connectors_driver_status", table_name="connectors")
    op.drop_table("connectors")
    op.drop_index("uq_connectivity_commands_request", table_name="connectivity_commands")
    op.drop_index("ix_connectivity_commands_resource", table_name="connectivity_commands")
    op.drop_table("connectivity_commands")
    with op.batch_alter_table("secrets") as batch_op:
        batch_op.drop_constraint(op.f("ck_secrets_owner_type_valid"), type_="check")
        batch_op.create_check_constraint(
            op.f("ck_secrets_owner_type_valid"),
            "owner_type IN ('workspace', 'user')",
        )
    # ### end Alembic commands ###
