"""replace environment configuration with attachments.

Revision ID: 18f466b3ccf1
Revises: a5dae1fc588f
Create Date: 2026-09-03 10:17:41.353241+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "18f466b3ccf1"
down_revision: str | Sequence[str] | None = "a5dae1fc588f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_environment_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("mount_name", sa.String(length=32), nullable=False),
        sa.Column("source_environment_revision_id", sa.String(length=72), nullable=True),
        sa.Column("provider_key", sa.String(length=128), nullable=False),
        sa.Column("target_key", sa.String(length=1024), nullable=False),
        sa.Column("environment_execution_config_digest_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mount_name = 'workspace'", name=op.f("ck_run_environment_bindings_mount_name_workspace")),
        sa.CheckConstraint(
            "length(environment_execution_config_digest_sha256) = 64",
            name=op.f("ck_run_environment_bindings_execution_config_digest_sha256"),
        ),
        sa.CheckConstraint(
            "length(target_key) BETWEEN 1 AND 1024", name=op.f("ck_run_environment_bindings_target_key_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["runs.tenant_id", "runs.id"],
            name=op.f("fk_run_environment_bindings_organization_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_environment_revision_id", "organization_id", "workspace_id"],
            ["environment_revisions.id", "environment_revisions.organization_id", "environment_revisions.workspace_id"],
            name=op.f("fk_run_environment_bindings_source_environment_revision_id_environment_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_run_environment_bindings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_environment_bindings")),
        sa.UniqueConstraint("organization_id", "run_id", name="uq_run_environment_bindings_run"),
    )
    op.create_index(
        "ix_run_environment_bindings_target",
        "run_environment_bindings",
        ["organization_id", "workspace_id", "provider_key", "target_key"],
        unique=False,
    )
    op.add_column("environment_revisions", sa.Column("connection", sa.JSON(), nullable=False))
    op.add_column("environment_revisions", sa.Column("target_key", sa.String(length=1024), nullable=False))
    op.drop_column("environment_revisions", "provider")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "environment_revisions",
        sa.Column("provider", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    )
    op.drop_column("environment_revisions", "target_key")
    op.drop_column("environment_revisions", "connection")
    op.drop_index("ix_run_environment_bindings_target", table_name="run_environment_bindings")
    op.drop_table("run_environment_bindings")
    # ### end Alembic commands ###
