"""add model management foundation.

Revision ID: 916295e4a4e4
Revises:
Create Date: 2026-08-30 06:21:27.156091+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "916295e4a4e4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_organizations_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "security_audit_events",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=True),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=72), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=72), nullable=True),
        sa.Column("auth_method", sa.String(length=32), nullable=False),
        sa.Column("credential_id", sa.String(length=72), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "actor_type IN ('anonymous', 'user', 'service_account', 'system')",
            name=op.f("ck_security_audit_events_actor_type_valid"),
        ),
        sa.CheckConstraint("outcome IN ('success', 'failure')", name=op.f("ck_security_audit_events_outcome_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_audit_events")),
    )
    op.create_index(
        "ix_security_audit_workspace_time",
        "security_audit_events",
        ["organization_id", "workspace_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_users_status_valid")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_users_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("normalized_email", name=op.f("uq_users_normalized_email")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workspaces_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workspaces_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(
        "uq_workspaces_active_organization_normalized_name",
        "workspaces",
        ["organization_id", "normalized_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("uq_workspaces_id_organization_id", "workspaces", ["id", "organization_id"], unique=True)
    op.create_table(
        "managed_secrets",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("owner_type", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=72), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "owner_type != 'workspace' OR owner_id = workspace_id",
            name=op.f("ck_managed_secrets_workspace_owner_consistent"),
        ),
        sa.CheckConstraint(
            "owner_type IN ('workspace', 'user')",
            name=op.f("ck_managed_secrets_owner_type_valid"),
        ),
        sa.CheckConstraint(
            "(deleted_at IS NULL AND ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL) OR (deleted_at IS NOT NULL AND ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL)",
            name=op.f("ck_managed_secrets_active_material_consistent"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_managed_secrets_version_positive")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_managed_secrets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_managed_secrets")),
    )
    op.create_index(
        "ix_managed_secrets_owner_listing",
        "managed_secrets",
        ["organization_id", "workspace_id", "owner_type", "owner_id", "key", "id"],
        unique=False,
    )
    op.create_index(
        "uq_managed_secrets_active_owner_key",
        "managed_secrets",
        ["organization_id", "workspace_id", "owner_type", "owner_id", "key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "model_configs",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("provider_type", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=256), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=True),
        sa.Column("credential", sa.JSON(), nullable=False),
        sa.Column("provider_config", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("capability_source", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_type", sa.String(length=32), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "capability_source IN ('catalog', 'manual_override')", name=op.f("ck_model_configs_capability_source_valid")
        ),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_model_configs_created_by_type_valid")
        ),
        sa.CheckConstraint(
            "updated_by_type IN ('user', 'service_account')", name=op.f("ck_model_configs_updated_by_type_valid")
        ),
        sa.CheckConstraint("length(model_name) BETWEEN 1 AND 256", name=op.f("ck_model_configs_model_name_bounded")),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_model_configs_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_model_configs_version_positive")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_model_configs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_configs")),
    )
    op.create_index(
        "ix_model_configs_workspace_provider",
        "model_configs",
        ["workspace_id", "provider_type", "updated_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_model_configs_workspace_updated", "model_configs", ["workspace_id", "updated_at", "id"], unique=False
    )
    op.create_index(
        "uq_model_configs_workspace_normalized_name", "model_configs", ["workspace_id", "normalized_name"], unique=True
    )
    op.create_table(
        "role_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=72), nullable=False),
        sa.Column("role_key", sa.String(length=32), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "principal_type IN ('user', 'service_account')", name=op.f("ck_role_bindings_principal_type_valid")
        ),
        sa.CheckConstraint(
            "resource_type IN ('organization', 'workspace', 'agent_preset')",
            name=op.f("ck_role_bindings_resource_type_valid"),
        ),
        sa.CheckConstraint(
            "role_key IN ('member', 'viewer', 'runner', 'builder', 'admin')",
            name=op.f("ck_role_bindings_role_key_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_role_bindings_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_role_bindings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_role_bindings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_bindings")),
    )
    op.create_index(
        "ix_role_bindings_authorization",
        "role_bindings",
        ["organization_id", "workspace_id", "principal_type", "principal_id"],
        unique=False,
    )
    op.create_index(
        "uq_role_bindings_principal_resource",
        "role_bindings",
        ["principal_type", "principal_id", "resource_type", "resource_id"],
        unique=True,
    )
    op.create_table(
        "service_accounts",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_service_accounts_status_valid")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_service_accounts_version_positive")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_service_accounts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_accounts")),
    )
    op.create_index(
        "uq_service_accounts_active_workspace_normalized_name",
        "service_accounts",
        ["workspace_id", "normalized_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_service_accounts_active_workspace_normalized_name",
        table_name="service_accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("service_accounts")
    op.drop_index("uq_role_bindings_principal_resource", table_name="role_bindings")
    op.drop_index("ix_role_bindings_authorization", table_name="role_bindings")
    op.drop_table("role_bindings")
    op.drop_index("uq_model_configs_workspace_normalized_name", table_name="model_configs")
    op.drop_index("ix_model_configs_workspace_updated", table_name="model_configs")
    op.drop_index("ix_model_configs_workspace_provider", table_name="model_configs")
    op.drop_table("model_configs")
    op.drop_index(
        "uq_managed_secrets_active_owner_key",
        table_name="managed_secrets",
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_managed_secrets_owner_listing", table_name="managed_secrets")
    op.drop_table("managed_secrets")
    op.drop_index("uq_workspaces_id_organization_id", table_name="workspaces")
    op.drop_index(
        "uq_workspaces_active_organization_normalized_name",
        table_name="workspaces",
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("workspaces")
    op.drop_table("users")
    op.drop_index("ix_security_audit_workspace_time", table_name="security_audit_events")
    op.drop_table("security_audit_events")
    op.drop_table("organizations")
    # ### end Alembic commands ###
