"""add hosted agui bindings.

Revision ID: c1870a69a442
Revises: 023eff74515b
Create Date: 2026-09-04 09:33:40.486173+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c1870a69a442"
down_revision: str | Sequence[str] | None = "023eff74515b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agui_thread_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("client_principal_type", sa.String(length=32), nullable=False),
        sa.Column("client_principal_id", sa.String(length=72), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("external_thread_id", sa.String(length=512), nullable=False),
        sa.Column("session_id", sa.String(length=72), nullable=False),
        sa.Column("root_thread_id", sa.String(length=72), nullable=False),
        sa.Column("active_thread_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "client_principal_type IN ('user', 'service_account')",
            name=op.f("ck_agui_thread_bindings_principal_type_valid"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_agui_thread_bindings_version_positive")),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_agui_thread_bindings_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "active_thread_id"],
            ["threads.tenant_id", "threads.id"],
            name="fk_agui_thread_bindings_active_thread",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "root_thread_id"],
            ["threads.tenant_id", "threads.id"],
            name="fk_agui_thread_bindings_root_thread",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "session_id"],
            ["sessions.tenant_id", "sessions.id"],
            name=op.f("fk_agui_thread_bindings_organization_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agui_thread_bindings")),
        sa.UniqueConstraint(
            "client_principal_type",
            "client_principal_id",
            "agent_id",
            "external_thread_id",
            name="uq_agui_thread_bindings_client_agent_thread",
        ),
    )
    op.create_index(
        "ix_agui_thread_bindings_active_thread",
        "agui_thread_bindings",
        ["organization_id", "active_thread_id", "id"],
        unique=False,
    )
    op.create_index(
        "uq_agui_thread_bindings_id_scope",
        "agui_thread_bindings",
        ["id", "organization_id", "workspace_id"],
        unique=True,
    )
    op.create_table(
        "agui_run_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("thread_binding_id", sa.String(length=72), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("agent_revision_id", sa.String(length=72), nullable=False),
        sa.Column("external_thread_id", sa.String(length=512), nullable=False),
        sa.Column("external_run_id", sa.String(length=512), nullable=False),
        sa.Column("parent_external_run_id", sa.String(length=512), nullable=True),
        sa.Column("request_digest_sha256", sa.String(length=64), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(request_digest_sha256) = 64", name=op.f("ck_agui_run_bindings_request_digest_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_agui_run_bindings_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_agui_run_bindings_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["runs.tenant_id", "runs.id"],
            name=op.f("fk_agui_run_bindings_organization_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["thread_binding_id", "organization_id", "workspace_id"],
            ["agui_thread_bindings.id", "agui_thread_bindings.organization_id", "agui_thread_bindings.workspace_id"],
            name=op.f("fk_agui_run_bindings_thread_binding_id_agui_thread_bindings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agui_run_bindings")),
        sa.UniqueConstraint("organization_id", "run_id", name="uq_agui_run_bindings_foundation_run"),
        sa.UniqueConstraint("thread_binding_id", "external_run_id", name="uq_agui_run_bindings_external_run"),
    )
    op.create_index(
        "ix_agui_run_bindings_foundation_run", "agui_run_bindings", ["organization_id", "run_id", "id"], unique=False
    )
    op.create_index(
        "uq_agui_run_bindings_id_scope", "agui_run_bindings", ["id", "organization_id", "workspace_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_agui_run_bindings_id_scope", table_name="agui_run_bindings")
    op.drop_index("ix_agui_run_bindings_foundation_run", table_name="agui_run_bindings")
    op.drop_table("agui_run_bindings")
    op.drop_index("uq_agui_thread_bindings_id_scope", table_name="agui_thread_bindings")
    op.drop_index("ix_agui_thread_bindings_active_thread", table_name="agui_thread_bindings")
    op.drop_table("agui_thread_bindings")
    # ### end Alembic commands ###
