"""add plugin management resources.

Revision ID: 290b4ef4b2a4
Revises: 336453a03bbe
Create Date: 2026-09-01 19:01:57.749726+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "290b4ef4b2a4"
down_revision: str | Sequence[str] | None = "336453a03bbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_runtime_state",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("active_lock_digest", sa.String(length=64), nullable=True),
        sa.Column("runtime_generation", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 'runtime'", name=op.f("ck_plugin_runtime_state_singleton")),
        sa.CheckConstraint("mode IN ('on_demand', 'runner')", name=op.f("ck_plugin_runtime_state_mode_valid")),
        sa.CheckConstraint("runtime_generation >= 1", name=op.f("ck_plugin_runtime_state_runtime_generation_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_runtime_state")),
    )
    op.create_table(
        "plugin_versions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("plugin_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.String(length=256), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("artifact_ref", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("requires_dist", sa.JSON(), nullable=False),
        sa.Column("requires_python", sa.String(length=1024), nullable=True),
        sa.Column("wheel_tags", sa.JSON(), nullable=False),
        sa.Column("root_is_purelib", sa.Boolean(), nullable=False),
        sa.Column("entry_point_target", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_plugin_versions_created_by_type_valid")
        ),
        sa.CheckConstraint("status = 'ready'", name=op.f("ck_plugin_versions_status_ready")),
        sa.CheckConstraint("length(content_digest) = 64", name=op.f("ck_plugin_versions_content_digest_sha256")),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_plugin_versions_size_bytes_positive")),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugins.id"],
            name=op.f("fk_plugin_versions_plugin_id_plugins"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_versions")),
        sa.UniqueConstraint("id", "plugin_id", name="uq_plugin_versions_id_plugin"),
        sa.UniqueConstraint("plugin_id", "version", name="uq_plugin_versions_plugin_version"),
    )
    op.create_index("ix_plugin_versions_digest", "plugin_versions", ["content_digest"], unique=False)
    op.create_index("ix_plugin_versions_listing", "plugin_versions", ["plugin_id", "created_at", "id"], unique=False)
    op.create_table(
        "plugins",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("plugin_key", sa.String(length=128), nullable=False),
        sa.Column("distribution_name", sa.String(length=256), nullable=False),
        sa.Column("top_level_package", sa.String(length=256), nullable=False),
        sa.Column("active_version_id", sa.String(length=72), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_plugins_created_by_type_valid")
        ),
        sa.CheckConstraint("source IN ('builtin', 'uploaded')", name=op.f("ck_plugins_source_valid")),
        sa.ForeignKeyConstraint(
            ["active_version_id", "id"],
            ["plugin_versions.id", "plugin_versions.plugin_id"],
            name="fk_plugins_active_version_plugin_versions",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugins")),
        sa.UniqueConstraint("distribution_name", name="uq_plugins_distribution_name"),
        sa.UniqueConstraint("plugin_key", name="uq_plugins_plugin_key"),
        sa.UniqueConstraint("top_level_package", name="uq_plugins_top_level_package"),
    )
    op.create_index("ix_plugins_listing", "plugins", ["updated_at", "id"], unique=False)
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key(
            op.f("fk_plugin_versions_plugin_id_plugins"),
            "plugin_versions",
            "plugins",
            ["plugin_id"],
            ["id"],
            ondelete="RESTRICT",
            use_alter=True,
        )
        op.create_foreign_key(
            "fk_plugins_active_version_plugin_versions",
            "plugins",
            "plugin_versions",
            ["active_version_id", "id"],
            ["id", "plugin_id"],
            ondelete="RESTRICT",
            use_alter=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_plugins_active_version_plugin_versions", "plugins", type_="foreignkey")
        op.drop_constraint(op.f("fk_plugin_versions_plugin_id_plugins"), "plugin_versions", type_="foreignkey")
    op.drop_index("ix_plugins_listing", table_name="plugins")
    op.drop_table("plugins")
    op.drop_index("ix_plugin_versions_listing", table_name="plugin_versions")
    op.drop_index("ix_plugin_versions_digest", table_name="plugin_versions")
    op.drop_table("plugin_versions")
    op.drop_table("plugin_runtime_state")
    # ### end Alembic commands ###
