"""add ingress and route management.

Revision ID: 56bec4f2eeec
Revises: 78dafda55dd5
Create Date: 2026-09-03 04:48:58.633515+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "56bec4f2eeec"
down_revision: str | Sequence[str] | None = "78dafda55dd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectivity_commands",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=72), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("scope_id", sa.String(length=72), nullable=False),
        sa.Column("idempotency_key_digest", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=72), nullable=False),
        sa.Column("result_version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'service_account')", name=op.f("ck_connectivity_commands_actor_type_valid")
        ),
        sa.CheckConstraint("result_version >= 1", name=op.f("ck_connectivity_commands_result_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectivity_commands")),
    )
    op.create_index(
        "ix_connectivity_commands_resource",
        "connectivity_commands",
        ["resource_type", "resource_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_connectivity_commands_request",
        "connectivity_commands",
        ["workspace_id", "actor_type", "actor_id", "operation", "scope_id", "idempotency_key_digest"],
        unique=True,
    )
    op.create_table(
        "ingresses",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("provider_config_json", sa.JSON(), nullable=False),
        sa.Column("execution_service_account_id", sa.String(length=72), nullable=False),
        sa.Column("default_agent_id", sa.String(length=72), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("credential_secret_id", sa.String(length=72), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_ingresses_created_by_type_valid")
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_ingresses_status_valid")),
        sa.CheckConstraint("credential_generation >= 1", name=op.f("ck_ingresses_credential_generation_positive")),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_ingresses_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ingresses_version_positive")),
        sa.ForeignKeyConstraint(
            ["credential_secret_id"],
            ["secrets.id"],
            name=op.f("fk_ingresses_credential_secret_id_secrets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["default_agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingresses_default_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_service_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_ingresses_execution_service_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_ingresses_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingresses")),
    )
    op.create_index("ix_ingresses_provider_status", "ingresses", ["provider_key", "status", "id"], unique=False)
    op.create_index("ix_ingresses_workspace_updated", "ingresses", ["workspace_id", "updated_at", "id"], unique=False)
    op.create_index("uq_ingresses_id_tenant", "ingresses", ["id", "organization_id", "workspace_id"], unique=True)
    op.create_index("uq_ingresses_workspace_name", "ingresses", ["workspace_id", "normalized_name"], unique=True)
    op.create_table(
        "ingress_agents",
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingress_agents_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_ingress_agents_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ingress_id", "agent_id", name=op.f("pk_ingress_agents")),
    )
    op.create_index(
        "ix_ingress_agents_agent", "ingress_agents", ["workspace_id", "agent_id", "ingress_id"], unique=False
    )
    op.create_table(
        "ingress_routes",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("ingress_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=128), nullable=False),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("match_json", sa.JSON(), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=True),
        sa.Column("input_mapping_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("min_interval_ms", sa.BigInteger(), nullable=False),
        sa.Column("max_batch_events", sa.BigInteger(), nullable=False),
        sa.Column("capability_overlays_json", sa.JSON(), nullable=False),
        sa.Column("provider_policy_json", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_ingress_routes_created_by_type_valid")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_ingress_routes_name_bounded")),
        sa.CheckConstraint("max_batch_events >= 1", name=op.f("ck_ingress_routes_max_batch_events_positive")),
        sa.CheckConstraint("min_interval_ms >= 1", name=op.f("ck_ingress_routes_min_interval_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ingress_routes_version_positive")),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_ingress_routes_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id", "organization_id", "workspace_id"],
            ["ingresses.id", "ingresses.organization_id", "ingresses.workspace_id"],
            name=op.f("fk_ingress_routes_ingress_id_ingresses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_routes")),
        sa.UniqueConstraint("ingress_id", "normalized_name", name="uq_ingress_routes_ingress_name"),
    )
    op.create_index(
        "ix_ingress_routes_listing", "ingress_routes", ["ingress_id", "enabled", "updated_at", "id"], unique=False
    )
    op.create_index(
        "uq_ingress_routes_id_tenant", "ingress_routes", ["id", "organization_id", "workspace_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_ingress_routes_id_tenant", table_name="ingress_routes")
    op.drop_index("ix_ingress_routes_listing", table_name="ingress_routes")
    op.drop_table("ingress_routes")
    op.drop_index("ix_ingress_agents_agent", table_name="ingress_agents")
    op.drop_table("ingress_agents")
    op.drop_index("uq_ingresses_workspace_name", table_name="ingresses")
    op.drop_index("uq_ingresses_id_tenant", table_name="ingresses")
    op.drop_index("ix_ingresses_workspace_updated", table_name="ingresses")
    op.drop_index("ix_ingresses_provider_status", table_name="ingresses")
    op.drop_table("ingresses")
    op.drop_index("uq_connectivity_commands_request", table_name="connectivity_commands")
    op.drop_index("ix_connectivity_commands_resource", table_name="connectivity_commands")
    op.drop_table("connectivity_commands")
    # ### end Alembic commands ###
