"""add connector domain resources.

Revision ID: a1b1e59d7ae3
Revises: 916295e4a4e4
Create Date: 2026-08-30 14:48:22.544374+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b1e59d7ae3"
down_revision: str | Sequence[str] | None = "916295e4a4e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectors",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_connectors_version_positive")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_connectors_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
    )
    op.create_index(
        "ix_connectors_workspace_updated",
        "connectors",
        ["organization_id", "workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_index("uq_connectors_id_tenant", "connectors", ["id", "organization_id", "workspace_id"], unique=True)
    op.create_table(
        "connections",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_id", sa.String(length=72), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=True),
        sa.Column("principal_id", sa.String(length=72), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider_key", sa.String(length=200), nullable=False),
        sa.Column("provider_state_version", sa.String(length=200), nullable=False),
        sa.Column("provider_state", sa.JSON(), nullable=False),
        sa.Column("account_external_id", sa.String(length=500), nullable=False),
        sa.Column("account_display_name", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifecycle_operation_id", sa.String(length=200), nullable=True),
        sa.Column("cleanup_pending", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(principal_type IS NULL AND principal_id IS NULL) OR (principal_type IN ('user', 'service_account') AND principal_id IS NOT NULL)",
            name=op.f("ck_connections_principal_ref_complete"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'disabled', 'reauthorization_required', 'revoked')",
            name=op.f("ck_connections_status_valid"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_connections_version_positive")),
        sa.ForeignKeyConstraint(
            ["connector_id", "organization_id", "workspace_id"],
            ["connectors.id", "connectors.organization_id", "connectors.workspace_id"],
            name=op.f("fk_connections_connector_id_connectors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_connections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
    )
    op.create_index(
        "ix_connections_personal_selection",
        "connections",
        ["organization_id", "workspace_id", "connector_id", "principal_type", "principal_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "ix_connections_workspace_connector_status",
        "connections",
        ["organization_id", "workspace_id", "connector_id", "status", "id"],
        unique=False,
    )
    op.create_index("uq_connections_id_tenant", "connections", ["id", "organization_id", "workspace_id"], unique=True)
    op.create_table(
        "connector_revisions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("provider_key", sa.String(length=200), nullable=False),
        sa.Column("provider_config_version", sa.String(length=200), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_connector_revisions_version_positive")),
        sa.ForeignKeyConstraint(
            ["connector_id", "organization_id", "workspace_id"],
            ["connectors.id", "connectors.organization_id", "connectors.workspace_id"],
            name=op.f("fk_connector_revisions_connector_id_connectors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_connector_revisions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_revisions")),
        sa.UniqueConstraint("connector_id", "version", name="uq_connector_revisions_connector_version"),
    )
    op.create_index(
        "ix_connector_revisions_workspace_connector",
        "connector_revisions",
        ["organization_id", "workspace_id", "connector_id", "version"],
        unique=False,
    )
    op.create_index(
        "uq_connector_revisions_id_tenant",
        "connector_revisions",
        ["id", "organization_id", "workspace_id"],
        unique=True,
    )
    op.create_table(
        "connection_setups",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("connector_revision_id", sa.String(length=72), nullable=False),
        sa.Column("target_connection_id", sa.String(length=72), nullable=True),
        sa.Column("provider_key", sa.String(length=200), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=True),
        sa.Column("principal_id", sa.String(length=72), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("setup_mode", sa.String(length=100), nullable=False),
        sa.Column("initiated_by_type", sa.String(length=32), nullable=False),
        sa.Column("initiated_by_id", sa.String(length=72), nullable=False),
        sa.Column("operation_id", sa.String(length=200), nullable=False),
        sa.Column("request_digest", sa.String(length=128), nullable=False),
        sa.Column("continuation_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("next_action", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.String(length=200), nullable=True),
        sa.Column("connection_id", sa.String(length=72), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('starting', 'pending', 'completing', 'completed', 'failed')",
            name=op.f("ck_connection_setups_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["connection_id", "organization_id", "workspace_id"],
            ["connections.id", "connections.organization_id", "connections.workspace_id"],
            name=op.f("fk_connection_setups_connection_id_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["connector_revision_id", "organization_id", "workspace_id"],
            ["connector_revisions.id", "connector_revisions.organization_id", "connector_revisions.workspace_id"],
            name=op.f("fk_connection_setups_connector_revision_id_connector_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_connection_id", "organization_id", "workspace_id"],
            ["connections.id", "connections.organization_id", "connections.workspace_id"],
            name=op.f("fk_connection_setups_target_connection_id_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_connection_setups_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connection_setups")),
        sa.UniqueConstraint("operation_id", name="uq_connection_setups_operation_id"),
    )
    op.create_index("ix_connection_setups_expiry", "connection_setups", ["status", "expires_at", "id"], unique=False)
    op.create_table(
        "triggers",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("agent_revision_id", sa.String(length=72), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("schedule_type", sa.String(length=32), nullable=True),
        sa.Column("schedule_expression", sa.String(length=200), nullable=True),
        sa.Column("schedule_timezone", sa.String(length=200), nullable=True),
        sa.Column("interval_seconds", sa.BigInteger(), nullable=True),
        sa.Column("next_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connector_revision_id", sa.String(length=72), nullable=True),
        sa.Column("connection_id", sa.String(length=72), nullable=True),
        sa.Column("event_type", sa.String(length=200), nullable=True),
        sa.Column("provider_event_config_version", sa.String(length=200), nullable=True),
        sa.Column("event_config", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("input_template", sa.JSON(), nullable=False),
        sa.Column("provider_state_version", sa.String(length=200), nullable=True),
        sa.Column("provider_state", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("event_cursor", sa.String(length=2000), nullable=True),
        sa.Column("lifecycle_operation_id", sa.String(length=200), nullable=True),
        sa.Column("cleanup_pending", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.String(length=200), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(source_kind = 'schedule' AND connector_revision_id IS NULL AND connection_id IS NULL AND event_type IS NULL AND provider_event_config_version IS NULL AND event_config IS NULL) OR (source_kind = 'connector_event' AND schedule_type IS NULL AND schedule_expression IS NULL AND schedule_timezone IS NULL AND interval_seconds IS NULL AND connector_revision_id IS NOT NULL AND connection_id IS NOT NULL AND event_type IS NOT NULL AND provider_event_config_version IS NOT NULL AND event_config IS NOT NULL)",
            name=op.f("ck_triggers_source_fields_match_kind"),
        ),
        sa.CheckConstraint(
            "principal_type IN ('user', 'service_account')", name=op.f("ck_triggers_principal_type_valid")
        ),
        sa.CheckConstraint(
            "source_kind != 'schedule' OR (schedule_type = 'cron' AND schedule_expression IS NOT NULL AND schedule_timezone IS NOT NULL AND interval_seconds IS NULL) OR (schedule_type = 'interval' AND schedule_expression IS NULL AND schedule_timezone IS NULL AND interval_seconds > 0)",
            name=op.f("ck_triggers_schedule_fields_valid"),
        ),
        sa.CheckConstraint(
            "source_kind IN ('schedule', 'connector_event')", name=op.f("ck_triggers_source_kind_valid")
        ),
        sa.CheckConstraint(
            "status IN ('disabled', 'activating', 'active', 'failed')", name=op.f("ck_triggers_status_valid")
        ),
        sa.CheckConstraint(
            "(provider_state_version IS NULL AND provider_state IS NULL) OR (provider_state_version IS NOT NULL AND provider_state IS NOT NULL)",
            name=op.f("ck_triggers_provider_state_complete"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_triggers_version_positive")),
        sa.ForeignKeyConstraint(
            ["connection_id", "organization_id", "workspace_id"],
            ["connections.id", "connections.organization_id", "connections.workspace_id"],
            name=op.f("fk_triggers_connection_id_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["connector_revision_id", "organization_id", "workspace_id"],
            ["connector_revisions.id", "connector_revisions.organization_id", "connector_revisions.workspace_id"],
            name=op.f("fk_triggers_connector_revision_id_connector_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_triggers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_triggers")),
    )
    op.create_index(
        "ix_triggers_schedule_claim", "triggers", ["status", "source_kind", "next_scheduled_at", "id"], unique=False
    )
    op.create_index(
        "ix_triggers_workspace_updated",
        "triggers",
        ["organization_id", "workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_index("uq_triggers_id_tenant", "triggers", ["id", "organization_id", "workspace_id"], unique=True)
    op.create_table(
        "trigger_occurrences",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("trigger_id", sa.String(length=72), nullable=False),
        sa.Column("occurrence_key", sa.String(length=500), nullable=False),
        sa.Column("provider_event_id", sa.String(length=500), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_turn_id", sa.String(length=72), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(provider_event_id IS NOT NULL AND scheduled_for IS NULL) OR (provider_event_id IS NULL AND scheduled_for IS NOT NULL)",
            name=op.f("ck_trigger_occurrences_source_identity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id", "organization_id", "workspace_id"],
            ["triggers.id", "triggers.organization_id", "triggers.workspace_id"],
            name=op.f("fk_trigger_occurrences_trigger_id_triggers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_trigger_occurrences_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trigger_occurrences")),
        sa.UniqueConstraint("trigger_id", "occurrence_key", name="uq_trigger_occurrences_trigger_key"),
    )
    op.create_index(
        "ix_trigger_occurrences_workspace_received",
        "trigger_occurrences",
        ["organization_id", "workspace_id", "received_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trigger_occurrences_workspace_received", table_name="trigger_occurrences")
    op.drop_table("trigger_occurrences")
    op.drop_index("uq_triggers_id_tenant", table_name="triggers")
    op.drop_index("ix_triggers_workspace_updated", table_name="triggers")
    op.drop_index("ix_triggers_schedule_claim", table_name="triggers")
    op.drop_table("triggers")
    op.drop_index("ix_connection_setups_expiry", table_name="connection_setups")
    op.drop_table("connection_setups")
    op.drop_index("uq_connector_revisions_id_tenant", table_name="connector_revisions")
    op.drop_index("ix_connector_revisions_workspace_connector", table_name="connector_revisions")
    op.drop_table("connector_revisions")
    op.drop_index("uq_connections_id_tenant", table_name="connections")
    op.drop_index("ix_connections_workspace_connector_status", table_name="connections")
    op.drop_index("ix_connections_personal_selection", table_name="connections")
    op.drop_table("connections")
    op.drop_index("uq_connectors_id_tenant", table_name="connectors")
    op.drop_index("ix_connectors_workspace_updated", table_name="connectors")
    op.drop_table("connectors")
    # ### end Alembic commands ###
