"""add a2a protocol bindings.

Revision ID: e68684416aa8
Revises: 2fd6b42b0e47
Create Date: 2026-09-04 10:28:32.311767+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e68684416aa8"
down_revision: str | Sequence[str] | None = "2fd6b42b0e47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "a2a_context_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("client_principal_type", sa.String(length=32), nullable=False),
        sa.Column("client_principal_id", sa.String(length=72), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("context_id", sa.String(length=512), nullable=False),
        sa.Column("session_id", sa.String(length=72), nullable=False),
        sa.Column("root_thread_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "client_principal_type IN ('user', 'service_account')",
            name=op.f("ck_a2a_context_bindings_principal_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_a2a_context_bindings_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "root_thread_id"],
            ["threads.tenant_id", "threads.id"],
            name=op.f("fk_a2a_context_bindings_organization_id_threads"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "session_id"],
            ["sessions.tenant_id", "sessions.id"],
            name=op.f("fk_a2a_context_bindings_organization_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_a2a_context_bindings")),
        sa.UniqueConstraint(
            "client_principal_type",
            "client_principal_id",
            "agent_id",
            "context_id",
            name="uq_a2a_context_client_agent_context",
        ),
    )
    op.create_index(
        "ix_a2a_context_root_thread", "a2a_context_bindings", ["organization_id", "root_thread_id", "id"], unique=False
    )
    op.create_index(
        "uq_a2a_context_id_scope", "a2a_context_bindings", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_table(
        "a2a_task_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("context_binding_id", sa.String(length=72), nullable=False),
        sa.Column("context_id", sa.String(length=512), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("agent_revision_id", sa.String(length=72), nullable=False),
        sa.Column("thread_id", sa.String(length=72), nullable=False),
        sa.Column("current_run_id", sa.String(length=72), nullable=False),
        sa.Column("run_ids_json", sa.JSON(), nullable=False),
        sa.Column("client_tool_surface_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(client_tool_surface_digest) = 64",
            name=op.f("ck_a2a_task_bindings_client_tool_surface_digest_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_a2a_task_bindings_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["context_binding_id", "organization_id", "workspace_id"],
            ["a2a_context_bindings.id", "a2a_context_bindings.organization_id", "a2a_context_bindings.workspace_id"],
            name=op.f("fk_a2a_task_bindings_context_binding_id_a2a_context_bindings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "current_run_id"],
            ["runs.tenant_id", "runs.id"],
            name=op.f("fk_a2a_task_bindings_organization_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "thread_id"],
            ["threads.tenant_id", "threads.id"],
            name=op.f("fk_a2a_task_bindings_organization_id_threads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_a2a_task_bindings")),
        sa.UniqueConstraint("organization_id", "id", name="uq_a2a_tasks_tenant_id"),
    )
    op.create_index(
        "ix_a2a_tasks_context_created", "a2a_task_bindings", ["context_binding_id", "created_at", "id"], unique=False
    )
    op.create_index(
        "ix_a2a_tasks_current_run", "a2a_task_bindings", ["organization_id", "current_run_id", "id"], unique=False
    )
    op.create_table(
        "a2a_message_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("client_principal_type", sa.String(length=32), nullable=False),
        sa.Column("client_principal_id", sa.String(length=72), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=False),
        sa.Column("task_id", sa.String(length=72), nullable=False),
        sa.Column("message_id", sa.String(length=512), nullable=False),
        sa.Column("request_digest_sha256", sa.String(length=64), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "client_principal_type IN ('user', 'service_account')",
            name=op.f("ck_a2a_message_bindings_principal_type_valid"),
        ),
        sa.CheckConstraint(
            "length(request_digest_sha256) = 64", name=op.f("ck_a2a_message_bindings_request_digest_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_a2a_message_bindings_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["runs.tenant_id", "runs.id"],
            name=op.f("fk_a2a_message_bindings_organization_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "organization_id"],
            ["a2a_task_bindings.id", "a2a_task_bindings.organization_id"],
            name=op.f("fk_a2a_message_bindings_task_id_a2a_task_bindings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_a2a_message_bindings")),
        sa.UniqueConstraint(
            "client_principal_type",
            "client_principal_id",
            "agent_id",
            "message_id",
            name="uq_a2a_messages_client_agent_message",
        ),
    )
    op.create_index("ix_a2a_messages_run", "a2a_message_bindings", ["organization_id", "run_id", "id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_a2a_messages_run", table_name="a2a_message_bindings")
    op.drop_table("a2a_message_bindings")
    op.drop_index("ix_a2a_tasks_current_run", table_name="a2a_task_bindings")
    op.drop_index("ix_a2a_tasks_context_created", table_name="a2a_task_bindings")
    op.drop_table("a2a_task_bindings")
    op.drop_index("uq_a2a_context_id_scope", table_name="a2a_context_bindings")
    op.drop_index("ix_a2a_context_root_thread", table_name="a2a_context_bindings")
    op.drop_table("a2a_context_bindings")
    # ### end Alembic commands ###
