"""remember project model preferences.

Revision ID: 9c59aaa12f44
Revises: a65ad8a5330d
Create Date: 2026-09-11 09:30:34.726785+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c59aaa12f44"
down_revision: str | Sequence[str] | None = "a65ad8a5330d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_model_preference",
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project_model_preference")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_model_preference")
    # ### end Alembic commands ###
