"""migrate sessions to threads.

Revision ID: f293cefc6ea1
Revises: 41ec8abea31a
Create Date: 2026-09-02 11:46:53.384759+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f293cefc6ea1"
down_revision: str | Sequence[str] | None = "41ec8abea31a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    legacy_tables = (
        "accepted_configuration",
        "composition_snapshot",
        "configuration_snapshot",
        "current_configuration",
        "local_session",
        "child_thread",
        "child_execution",
        "environment_binding",
    )
    connection = op.get_bind()
    populated = [
        table
        for table in legacy_tables
        if connection.exec_driver_sql(f'SELECT 1 FROM "{table}" LIMIT 1').first() is not None
    ]
    if populated:
        raise RuntimeError(
            "The Session-era Harness UI store contains authority rows that cannot be "
            "safely converted to Thread source-generation contracts. Start with a "
            "new data root after preserving the existing store."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread",
        sa.Column("thread_id", sa.String(length=80), nullable=False),
        sa.Column("parent_thread_id", sa.String(length=80), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("initial_state_schema_version", sa.String(length=64), nullable=False),
        sa.Column("initial_state_digest", sa.String(length=64), nullable=False),
        sa.Column("continuation_schema_version", sa.String(length=64), nullable=True),
        sa.Column("continuation_digest", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_thread_parent_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_thread")),
    )
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thread_parent_thread_id"), ["parent_thread_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_thread_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "configuration_source",
        sa.Column("generation_digest", sa.String(length=64), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("resource_kind", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["generation_digest"],
            ["accepted_configuration.generation_digest"],
            name=op.f("fk_configuration_source_generation_digest_accepted_configuration"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("generation_digest", "relative_path", name=op.f("pk_configuration_source")),
    )
    op.create_table(
        "resource_index",
        sa.Column("generation_digest", sa.String(length=64), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("resource_kind", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("normalized_digest", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_digest"],
            ["accepted_configuration.generation_digest"],
            name=op.f("fk_resource_index_generation_digest_accepted_configuration"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("generation_digest", "relative_path", name=op.f("pk_resource_index")),
        sa.UniqueConstraint("generation_digest", "resource_kind", "resource_id", name="resource_identity"),
    )
    op.create_table(
        "thread_configuration",
        sa.Column("thread_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("agent_source_kind", sa.String(length=16), nullable=False),
        sa.Column("agent_source_id", sa.String(length=128), nullable=False),
        sa.Column("environment_profile_id", sa.String(length=128), nullable=False),
        sa.Column("harness_plugin_ids_json", sa.Text(), nullable=False),
        sa.Column("environment_run_extension_ids_json", sa.Text(), nullable=False),
        sa.Column("mcp_server_ids_json", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "agent_source_kind IN ('agent', 'markdown')", name=op.f("ck_thread_configuration_agent_source_kind")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_thread_configuration_version")),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_thread_configuration_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_thread_configuration")),
    )
    op.drop_table("child_execution")
    op.drop_table("environment_binding")
    op.drop_table("composition_snapshot")
    with op.batch_alter_table("child_thread", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_thread_parent_thread_id"))
        batch_op.drop_index(batch_op.f("ix_child_thread_session_id"))

    op.drop_table("child_thread")
    op.drop_table("configuration_snapshot")
    with op.batch_alter_table("local_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_local_session_updated_at"))

    op.drop_table("local_session")

    # Session-era accepted rows contain schema-v1 inline documents and cannot be
    # represented as complete schema-v2 source generations. The App reaccepts the
    # current source tree after startup, so replace these heads rather than
    # manufacturing invalid generation objects or Thread selections.
    op.drop_table("current_configuration")
    op.drop_table("accepted_configuration")
    op.create_table(
        "accepted_configuration",
        sa.Column("generation_digest", sa.String(length=64), nullable=False),
        sa.Column("object_schema_version", sa.String(length=64), nullable=False),
        sa.Column("object_digest", sa.String(length=64), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("generation_digest", name=op.f("pk_accepted_configuration")),
    )
    op.create_table(
        "current_configuration",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("generation_digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint("singleton_id = 1", name=op.f("ck_current_configuration_singleton")),
        sa.ForeignKeyConstraint(
            ["generation_digest"],
            ["accepted_configuration.generation_digest"],
            name=op.f("fk_current_configuration_generation_digest_accepted_configuration"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_current_configuration")),
    )
    op.create_table(
        "child_execution",
        sa.Column("execution_id", sa.String(length=80), nullable=False),
        sa.Column("parent_thread_id", sa.String(length=80), nullable=False),
        sa.Column("child_thread_id", sa.String(length=80), nullable=False),
        sa.Column("child_run_id", sa.String(length=80), nullable=False),
        sa.Column("segment_index", sa.Integer(), nullable=False),
        sa.Column("run_composition_schema_version", sa.String(length=64), nullable=False),
        sa.Column("run_composition_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("selected_checkpoint_schema_version", sa.String(length=64), nullable=True),
        sa.Column("selected_checkpoint_digest", sa.String(length=64), nullable=True),
        sa.Column("resumed_from", sa.String(length=80), nullable=True),
        sa.Column("failure_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("segment_index >= 0", name=op.f("ck_child_execution_segment_index")),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'cancelled', 'lost')",
            name=op.f("ck_child_execution_status"),
        ),
        sa.CheckConstraint(
            "(segment_index = 0 AND resumed_from IS NULL) OR (segment_index > 0 AND resumed_from IS NOT NULL)",
            name=op.f("ck_child_execution_resume_link"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_child_execution_parent_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["child_thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_child_execution_child_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resumed_from"],
            ["child_execution.execution_id"],
            name=op.f("fk_child_execution_resumed_from_child_execution"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("execution_id", name=op.f("pk_child_execution")),
        sa.UniqueConstraint("child_thread_id", "segment_index", name="segment"),
        sa.UniqueConstraint("resumed_from", name=op.f("uq_child_execution_resumed_from")),
    )
    with op.batch_alter_table("child_execution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_child_execution_child_thread_id"), ["child_thread_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_child_execution_parent_thread_id"), ["parent_thread_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_child_execution_status"), ["status"], unique=False)

    op.create_table(
        "environment_binding",
        sa.Column("thread_id", sa.String(length=80), nullable=False),
        sa.Column("environment_profile_id", sa.String(length=128), nullable=False),
        sa.Column("profile_digest", sa.String(length=64), nullable=False),
        sa.Column("adapter_key", sa.String(length=200), nullable=False),
        sa.Column("normalized_root", sa.Text(), nullable=False),
        sa.Column("state_schema_version", sa.String(length=64), nullable=True),
        sa.Column("state_digest", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(state_digest IS NULL AND state_schema_version IS NULL) OR "
            "(state_digest IS NOT NULL AND state_schema_version IS NOT NULL)",
            name=op.f("ck_environment_binding_state_reference"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_environment_binding_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "environment_profile_id",
            "profile_digest",
            "adapter_key",
            "normalized_root",
            name=op.f("pk_environment_binding"),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reject an unsafe semantic downgrade before changing any table."""

    raise RuntimeError(
        "The Thread-era Harness UI store cannot be safely downgraded to the "
        "Session-era authority model. Preserve this store and select a different "
        "data root for an older Harness UI release."
    )
