"""retain observed thread usage.

Revision ID: 11422c5bac45
Revises: 9ad1ce20a90f
Create Date: 2026-09-07 18:35:20.933666+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "11422c5bac45"
down_revision: str | Sequence[str] | None = "9ad1ce20a90f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_usage",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("root_thread_id", sa.String(length=80), nullable=False),
        sa.Column("origin_thread_id", sa.String(length=80), nullable=False),
        sa.Column("record_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=256), nullable=False),
        sa.Column("descendant", sa.Boolean(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_thread_usage_origin_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_thread_id"],
            ["thread.thread_id"],
            name=op.f("fk_thread_usage_root_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_thread_usage")),
        sa.UniqueConstraint("root_thread_id", "record_id", name="identity"),
    )
    with op.batch_alter_table("thread_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thread_usage_root_thread_id"), ["root_thread_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_usage_root_thread_id"))

    op.drop_table("thread_usage")
    # ### end Alembic commands ###
