"""add small thread work projections.

Revision ID: c82e5ae6ef80
Revises: 1da116a90fda
Create Date: 2026-10-01 05:46:33.356027+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c82e5ae6ef80"
down_revision: str | Sequence[str] | None = "1da116a90fda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_work",
        sa.Column("thread_id", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("object_schema_version", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("summary_json", sa.Text(), nullable=False),
        sa.Column("tasks_json", sa.Text(), nullable=True),
        sa.Column("notes_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["thread.thread_id"], name=op.f("fk_thread_work_thread_id_thread"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_thread_work")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thread_work")
    # ### end Alembic commands ###
