"""add thread owned local roots.

Revision ID: 3a52b4914bbb
Revises: 0c38589db1f4
Create Date: 2026-09-19 14:14:11.695702+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a52b4914bbb"
down_revision: str | Sequence[str] | None = "0c38589db1f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread_configuration", schema=None) as batch_op:
        batch_op.add_column(sa.Column("local_roots_json", sa.Text(), server_default="[]", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread_configuration", schema=None) as batch_op:
        batch_op.drop_column("local_roots_json")

    # ### end Alembic commands ###
