"""add durable thread completion markers.

Revision ID: 57b54299e47e
Revises: 122039abf689
Create Date: 2026-09-16 16:16:21.232356+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "57b54299e47e"
down_revision: str | Sequence[str] | None = "122039abf689"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completion_version", sa.Integer(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("completion_run_id", sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column("completion_digest", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_column("completed_at")
        batch_op.drop_column("completion_digest")
        batch_op.drop_column("completion_run_id")
        batch_op.drop_column("completion_version")

    # ### end Alembic commands ###
