"""add continuation read models.

Revision ID: acd7efeb9fd8
Revises: 9aeed42d15b3
Create Date: 2026-09-17 09:11:52.720926+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "acd7efeb9fd8"
down_revision: str | Sequence[str] | None = "9aeed42d15b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.add_column(sa.Column("read_model_digest", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("read_model_schema_version", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("read_model_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_column("read_model_json")
        batch_op.drop_column("read_model_schema_version")
        batch_op.drop_column("read_model_digest")

    # ### end Alembic commands ###
