"""add device environment bindings and selections.

Revision ID: 0c38589db1f4
Revises: ba240ec65035
Create Date: 2026-09-19 04:02:32.716673+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0c38589db1f4"
down_revision: str | Sequence[str] | None = "ba240ec65035"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("environment_binding", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("device_id", sa.String(length=128), server_default=sa.text("('')"), nullable=False)
        )
        batch_op.add_column(sa.Column("alias", sa.String(length=63), server_default=sa.text("('')"), nullable=False))
        # Alembic does not detect primary-key membership changes.
        batch_op.drop_constraint("pk_environment_binding", type_="primary")
        batch_op.create_primary_key(
            "pk_environment_binding",
            [
                "thread_id",
                "environment_profile_id",
                "profile_digest",
                "adapter_key",
                "normalized_root",
                "device_id",
                "alias",
            ],
        )

    with op.batch_alter_table("thread_configuration", schema=None) as batch_op:
        batch_op.add_column(sa.Column("environment_bindings_json", sa.Text(), server_default="[]", nullable=False))
        batch_op.add_column(sa.Column("default_environment", sa.String(length=63), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread_configuration", schema=None) as batch_op:
        batch_op.drop_column("default_environment")
        batch_op.drop_column("environment_bindings_json")

    with op.batch_alter_table("environment_binding", schema=None) as batch_op:
        batch_op.drop_constraint("pk_environment_binding", type_="primary")
        batch_op.create_primary_key(
            "pk_environment_binding",
            ["thread_id", "environment_profile_id", "profile_digest", "adapter_key", "normalized_root"],
        )
        batch_op.drop_column("alias")
        batch_op.drop_column("device_id")

    # ### end Alembic commands ###
