"""add planned update handoff.

Revision ID: ba240ec65035
Revises: 63e8be47c2e2
Create Date: 2026-09-18 12:33:19.328997+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ba240ec65035"
down_revision: str | Sequence[str] | None = "63e8be47c2e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planned_restart",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.CheckConstraint("singleton_id = 1", name=op.f("ck_planned_restart_singleton")),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_planned_restart")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Do not silently discard an operator's update handoff."""
    if op.get_bind().execute(sa.text("SELECT 1 FROM planned_restart LIMIT 1")).first() is not None:
        raise RuntimeError("Cannot downgrade while an update handoff exists; resolve maintenance first.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planned_restart")
    # ### end Alembic commands ###
