"""add browser push subscriptions.

Revision ID: 9aeed42d15b3
Revises: 57b54299e47e
Create Date: 2026-09-17 01:45:39.988296+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9aeed42d15b3"
down_revision: str | Sequence[str] | None = "57b54299e47e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_push_key",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.CheckConstraint("singleton_id = 1", name=op.f("ck_web_push_key_singleton")),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_web_push_key")),
    )
    op.create_table(
        "web_push_subscription",
        sa.Column("subscription_id", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("thread_ids_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_web_push_subscription")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_push_subscription")
    op.drop_table("web_push_key")
    # ### end Alembic commands ###
