"""retain latest root execution summary.

Revision ID: 4bd3d3ab1b82
Revises: c82e5ae6ef80
Create Date: 2026-10-10 03:33:01.383703+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4bd3d3ab1b82"
down_revision: str | Sequence[str] | None = "c82e5ae6ef80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_execution_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_column("last_execution_json")

    # ### end Alembic commands ###
