"""replace push thread interest with activity.

Revision ID: 63e8be47c2e2
Revises: e416fbd4674c
Create Date: 2026-09-18 12:56:01.853981+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "63e8be47c2e2"
down_revision: str | Sequence[str] | None = "e416fbd4674c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_push_subscription", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_active_at", sa.DateTime(), nullable=True))
        batch_op.drop_column("thread_ids_json")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_push_subscription", schema=None) as batch_op:
        # Removed interests cannot be recovered; old clients repopulate them.
        batch_op.add_column(sa.Column("thread_ids_json", sa.TEXT(), nullable=False, server_default="[]"))
        batch_op.drop_column("last_active_at")
    with op.batch_alter_table("web_push_subscription", schema=None) as batch_op:
        batch_op.alter_column("thread_ids_json", server_default=None)

    # ### end Alembic commands ###
