"""add local identity credentials and invitations.

Revision ID: 8560ee8dfdab
Revises: 03c32fc8dca5
Create Date: 2026-09-08 04:32:59.631312+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8560ee8dfdab"
down_revision: str | Sequence[str] | None = "03c32fc8dca5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("user_id", sa.String(length=72), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_sessions_token_hash")),
    )
    op.create_index("ix_auth_sessions_user_created", "auth_sessions", ["user_id", "created_at", "id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("verification_mode", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.String(length=72), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=72), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verification_mode IN ('email', 'out_of_band')", name=op.f("ck_invitations_verification_mode_valid")
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_accepted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        "ix_invitations_organization_created", "invitations", ["organization_id", "created_at", "id"], unique=False
    )
    op.create_index(
        "uq_invitations_bootstrap",
        "invitations",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("created_by_user_id IS NULL"),
        sqlite_where=sa.text("created_by_user_id IS NULL"),
    )
    op.create_index("uq_invitations_id_organization", "invitations", ["id", "organization_id"], unique=True)
    op.create_table(
        "password_credentials",
        sa.Column("user_id", sa.String(length=72), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_credentials_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_password_credentials")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("boundary_type", sa.String(length=32), nullable=False),
        sa.Column("boundary_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("boundary_type = 'workspace'", name=op.f("ck_api_keys_boundary_type_valid")),
        sa.CheckConstraint(
            "principal_type IN ('user', 'service_account')", name=op.f("ck_api_keys_principal_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["boundary_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_api_keys_boundary_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index(
        "ix_api_keys_owner_boundary", "api_keys", ["principal_type", "principal_id", "boundary_id"], unique=False
    )
    op.create_table(
        "invitation_grants",
        sa.Column("invitation_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=72), nullable=False),
        sa.Column("role_key", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "(resource_type = 'organization' AND workspace_id IS NULL AND resource_id = organization_id AND role_key IN ('member', 'admin')) OR (resource_type = 'workspace' AND workspace_id IS NOT NULL AND resource_id = workspace_id AND role_key IN ('viewer', 'runner', 'builder', 'admin'))",
            name=op.f("ck_invitation_grants_grant_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id", "organization_id"],
            ["invitations.id", "invitations.organization_id"],
            name=op.f("fk_invitation_grants_invitation_id_invitations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_invitation_grants_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("invitation_id", "resource_type", "resource_id", name=op.f("pk_invitation_grants")),
    )
    op.add_column("service_accounts", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_accounts", "version")
    op.drop_table("invitation_grants")
    op.drop_index("ix_api_keys_owner_boundary", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("password_credentials")
    op.drop_index("uq_invitations_id_organization", table_name="invitations")
    op.drop_index(
        "uq_invitations_bootstrap",
        table_name="invitations",
        postgresql_where=sa.text("created_by_user_id IS NULL"),
        sqlite_where=sa.text("created_by_user_id IS NULL"),
    )
    op.drop_index("ix_invitations_organization_created", table_name="invitations")
    op.drop_table("invitations")
    op.drop_index("ix_auth_sessions_user_created", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
