"""add event connection leases.

Revision ID: c0355d7f89ba
Revises: eb41d745e5d0
Create Date: 2026-09-17 04:01:35.352820+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c0355d7f89ba"
down_revision: str | Sequence[str] | None = "eb41d745e5d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectivity_event_connections",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("account_versions", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(length=72), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_connectivity_event_connections")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connectivity_event_connections")
    # ### end Alembic commands ###
