"""add web provider accounts.

Revision ID: c9632d7e8521
Revises: 10fb2934dec9
Create Date: 2026-09-09 13:41:35.529483+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9632d7e8521"
down_revision: str | Sequence[str] | None = "10fb2934dec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_providers",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=384), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_type", sa.String(length=32), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_web_providers_created_by_type_valid")
        ),
        sa.CheckConstraint(
            "updated_by_type IN ('user', 'service_account')", name=op.f("ck_web_providers_updated_by_type_valid")
        ),
        sa.CheckConstraint(
            "(ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL) OR (ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL)",
            name=op.f("ck_web_providers_credential_material_consistent"),
        ),
        sa.CheckConstraint(
            "credential_generation >= 0", name=op.f("ck_web_providers_credential_generation_nonnegative")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_web_providers_name_bounded")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_web_providers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_web_providers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_providers")),
    )
    op.create_index(
        "ix_web_providers_workspace_updated", "web_providers", ["workspace_id", "updated_at", "id"], unique=False
    )
    op.create_index("uq_web_providers_identity_scope", "web_providers", ["id", "organization_id"], unique=True)
    op.create_index(
        "uq_web_providers_organization_normalized_name",
        "web_providers",
        ["organization_id", "normalized_name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.create_index(
        "uq_web_providers_workspace_name", "web_providers", ["workspace_id", "normalized_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_web_providers_workspace_name", table_name="web_providers")
    op.drop_index(
        "uq_web_providers_organization_normalized_name",
        table_name="web_providers",
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.drop_index("uq_web_providers_identity_scope", table_name="web_providers")
    op.drop_index("ix_web_providers_workspace_updated", table_name="web_providers")
    op.drop_table("web_providers")
    # ### end Alembic commands ###
