"""persist accepted environment directories.

Revision ID: 6e90e09b75b3
Revises: 7925615e9e83
Create Date: 2026-09-19 04:02:51.125634+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6e90e09b75b3"
down_revision: str | Sequence[str] | None = "7925615e9e83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_environment_mounts", sa.Column("working_directory", sa.String(length=4096), nullable=True))
    op.add_column("runs", sa.Column("environment_working_directory", sa.String(length=4096), nullable=True))
    op.add_column("threads", sa.Column("default_environment_working_directory", sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "default_environment_working_directory")
    op.drop_column("runs", "environment_working_directory")
    op.drop_column("run_environment_mounts", "working_directory")
    # ### end Alembic commands ###
