"""initialize ingress routing and admission.

Revision ID: 676ce43cf244
Revises: 6a290c689265
Create Date: 2026-09-04 08:22:26.999041+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "676ce43cf244"
down_revision: str | Sequence[str] | None = "6a290c689265"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_accounts",
        sa.Column("receive_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("default_agent_id", sa.String(length=72), nullable=True),
        sa.Column("execution_service_account_id", sa.String(length=72), nullable=True),
        sa.Column("input_batching_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("provider_policy_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("identity_digest", sa.String(length=64), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=384), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("provider_config_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_application_accounts_created_by_type_valid")
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_application_accounts_status_valid")),
        sa.CheckConstraint(
            "(deleted_at IS NULL AND ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL) OR (deleted_at IS NOT NULL AND ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL)",
            name=op.f("ck_application_accounts_credential_material_consistent"),
        ),
        sa.CheckConstraint(
            "NOT receive_enabled OR (default_agent_id IS NOT NULL AND execution_service_account_id IS NOT NULL)",
            name=op.f("ck_application_accounts_receiver_configured"),
        ),
        sa.CheckConstraint(
            "credential_generation >= 1", name=op.f("ck_application_accounts_credential_generation_positive")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_application_accounts_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_application_accounts_version_positive")),
        sa.ForeignKeyConstraint(
            ["default_agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_application_accounts_default_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_service_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_application_accounts_execution_service_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_application_accounts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_accounts")),
    )
    op.create_index(
        "ix_application_accounts_provider_status",
        "application_accounts",
        ["provider_key", "status", "id"],
        unique=False,
    )
    op.create_index(
        "ix_application_accounts_workspace_updated",
        "application_accounts",
        ["workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_application_accounts_id_organization",
        "application_accounts",
        ["id", "organization_id", "workspace_id"],
        unique=True,
    )
    op.create_index(
        "uq_application_accounts_identity",
        "application_accounts",
        ["workspace_id", "provider_key", "identity_digest"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_application_accounts_workspace_name",
        "application_accounts",
        ["workspace_id", "normalized_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "account_targets",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("target_kind", sa.String(length=32), nullable=False),
        sa.Column("external_target_id", sa.String(length=2048), nullable=False),
        sa.Column("agent_id", sa.String(length=72), nullable=True),
        sa.Column("config_override_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("input_batching_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("provider_policy_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("receive_enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "target_kind IN ('conversation', 'repository')", name=op.f("ck_account_targets_target_kind_valid")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_account_targets_version_positive")),
        sa.ForeignKeyConstraint(
            ["account_id", "organization_id", "workspace_id"],
            ["application_accounts.id", "application_accounts.organization_id", "application_accounts.workspace_id"],
            name=op.f("fk_account_targets_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_account_targets_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_targets")),
        sa.UniqueConstraint("account_id", "target_kind", "external_target_id", name="uq_account_targets_object"),
    )
    op.create_index("ix_account_targets_listing", "account_targets", ["account_id", "updated_at", "id"], unique=False)
    op.create_index(
        "uq_account_targets_id_organization", "account_targets", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_table(
        "agent_thread_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("external_ref_kind", sa.String(length=128), nullable=False),
        sa.Column("external_ref_id", sa.String(length=2048), nullable=False),
        sa.Column("thread_id", sa.String(length=72), nullable=True),
        sa.Column("next_batch_sequence", sa.BigInteger(), nullable=False),
        sa.Column("next_submission_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("next_batch_sequence >= 1", name=op.f("ck_agent_thread_bindings_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["account_id", "organization_id", "workspace_id"],
            ["application_accounts.id", "application_accounts.organization_id", "application_accounts.workspace_id"],
            name=op.f("fk_agent_thread_bindings_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "thread_id"],
            ["threads.organization_id", "threads.id"],
            name=op.f("fk_agent_thread_bindings_organization_id_threads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_thread_bindings")),
        sa.UniqueConstraint(
            "account_id", "external_ref_kind", "external_ref_id", name="uq_agent_thread_bindings_external_ref"
        ),
    )
    op.create_index(
        "ix_agent_thread_bindings_thread", "agent_thread_bindings", ["organization_id", "thread_id", "id"], unique=False
    )
    op.create_index(
        "uq_agent_thread_bindings_id_organization",
        "agent_thread_bindings",
        ["id", "organization_id", "workspace_id"],
        unique=True,
    )
    op.create_table(
        "ingress_batches",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("binding_id", sa.String(length=72), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("event_count", sa.BigInteger(), nullable=False),
        sa.Column("event_bytes", sa.BigInteger(), nullable=False),
        sa.Column("append_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_kind", sa.String(length=32), nullable=True),
        sa.Column("result_id", sa.String(length=72), nullable=True),
        sa.Column("rejection_reason", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')", name=op.f("ck_ingress_batches_status_valid")
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_ingress_batches_attempt_count_non_negative")),
        sa.CheckConstraint("claim_generation >= 0", name=op.f("ck_ingress_batches_claim_generation_non_negative")),
        sa.CheckConstraint("event_bytes >= 0", name=op.f("ck_ingress_batches_event_bytes_non_negative")),
        sa.CheckConstraint("event_count >= 1", name=op.f("ck_ingress_batches_event_count_positive")),
        sa.ForeignKeyConstraint(
            ["binding_id", "organization_id", "workspace_id"],
            ["agent_thread_bindings.id", "agent_thread_bindings.organization_id", "agent_thread_bindings.workspace_id"],
            name=op.f("fk_ingress_batches_binding_id_agent_thread_bindings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_batches")),
        sa.UniqueConstraint("binding_id", "sequence", name="uq_ingress_batches_sequence"),
    )
    op.create_index(
        "ix_ingress_batches_claim",
        "ingress_batches",
        ["status", "available_at", "claim_expires_at", "id"],
        unique=False,
    )
    op.create_index("ix_ingress_batches_retention", "ingress_batches", ["status", "terminal_at", "id"], unique=False)
    op.create_index(
        "uq_ingress_batches_id_organization", "ingress_batches", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_table(
        "ingress_admissions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("batch_id", sa.String(length=72), nullable=True),
        sa.Column("event_identity_kind", sa.String(length=128), nullable=False),
        sa.Column("event_identity_digest", sa.String(length=64), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("event_json", sa.JSON(), nullable=False),
        sa.Column("ordering_key", sa.String(length=2048), nullable=False),
        sa.Column("event_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=128), nullable=True),
        sa.Column("dedup_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "batch_id IS NOT NULL OR rejection_reason IS NOT NULL",
            name=op.f("ck_ingress_admissions_event_destination_known"),
        ),
        sa.CheckConstraint("event_size_bytes >= 0", name=op.f("ck_ingress_admissions_event_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["account_id", "organization_id", "workspace_id"],
            ["application_accounts.id", "application_accounts.organization_id", "application_accounts.workspace_id"],
            name=op.f("fk_ingress_admissions_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["batch_id", "organization_id", "workspace_id"],
            ["ingress_batches.id", "ingress_batches.organization_id", "ingress_batches.workspace_id"],
            name=op.f("fk_ingress_admissions_batch_id_ingress_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_admissions")),
        sa.UniqueConstraint(
            "account_id", "event_identity_kind", "event_identity_digest", name="uq_ingress_admissions_identity"
        ),
    )
    op.create_index(
        "ix_ingress_admissions_capacity", "ingress_admissions", ["workspace_id", "account_id", "batch_id"], unique=False
    )
    op.create_index(
        "ix_ingress_admissions_order", "ingress_admissions", ["batch_id", "ordering_key", "id"], unique=False
    )
    op.create_index("ix_ingress_admissions_retention", "ingress_admissions", ["dedup_expires_at", "id"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ingress_admissions_retention", table_name="ingress_admissions")
    op.drop_index("ix_ingress_admissions_order", table_name="ingress_admissions")
    op.drop_index("ix_ingress_admissions_capacity", table_name="ingress_admissions")
    op.drop_table("ingress_admissions")
    op.drop_index("uq_ingress_batches_id_organization", table_name="ingress_batches")
    op.drop_index("ix_ingress_batches_retention", table_name="ingress_batches")
    op.drop_index("ix_ingress_batches_claim", table_name="ingress_batches")
    op.drop_table("ingress_batches")
    op.drop_index("uq_agent_thread_bindings_id_organization", table_name="agent_thread_bindings")
    op.drop_index("ix_agent_thread_bindings_thread", table_name="agent_thread_bindings")
    op.drop_table("agent_thread_bindings")
    op.drop_index("uq_account_targets_id_organization", table_name="account_targets")
    op.drop_index("ix_account_targets_listing", table_name="account_targets")
    op.drop_table("account_targets")
    op.drop_index(
        "uq_application_accounts_workspace_name",
        table_name="application_accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_application_accounts_identity",
        table_name="application_accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("uq_application_accounts_id_organization", table_name="application_accounts")
    op.drop_index("ix_application_accounts_workspace_updated", table_name="application_accounts")
    op.drop_index("ix_application_accounts_provider_status", table_name="application_accounts")
    op.drop_table("application_accounts")
