"""add connection-owned MCP OAuth clients.

Revision ID: f6ec04da96ed
Revises: ec86f1da8c98
Create Date: 2026-09-11 10:22:28.166155+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f6ec04da96ed"
down_revision: str | Sequence[str] | None = "ec86f1da8c98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_oauth_clients",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "(ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL) OR (ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL)",
            name=op.f("ck_mcp_oauth_clients_credential_material_consistent"),
        ),
        sa.CheckConstraint(
            "credential_generation >= 0", name=op.f("ck_mcp_oauth_clients_credential_generation_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["id", "organization_id", "workspace_id"],
            ["mcp_connections.id", "mcp_connections.organization_id", "mcp_connections.workspace_id"],
            name=op.f("fk_mcp_oauth_clients_id_mcp_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_oauth_clients")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mcp_oauth_clients")
    # ### end Alembic commands ###
