"""add bot reception scope.

Revision ID: 96f61e7ecace
Revises: 838688629ca8
Create Date: 2026-09-15 15:35:02.164500+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "96f61e7ecace"
down_revision: str | Sequence[str] | None = "838688629ca8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_accounts",
        sa.Column("reception_scope", sa.String(length=32), server_default="all_accessible", nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_application_accounts_reception_scope_valid"),
        "application_accounts",
        "reception_scope IN ('all_accessible', 'configured_targets')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_application_accounts_reception_scope_valid"), "application_accounts", type_="check")
    op.drop_column("application_accounts", "reception_scope")
    # ### end Alembic commands ###
