"""initialize connector providers.

Revision ID: f1f948fa1903
Revises: 4d09e6da2dd5
Create Date: 2026-09-04 08:22:08.891876+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1f948fa1903"
down_revision: str | Sequence[str] | None = "4d09e6da2dd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_providers",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=384), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_connector_providers_created_by_type_valid")
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_connector_providers_status_valid")),
        sa.CheckConstraint(
            "(ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL) OR "
            "(ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL)",
            name=op.f("ck_connector_providers_credential_material_consistent"),
        ),
        sa.CheckConstraint(
            "credential_generation >= 1", name=op.f("ck_connector_providers_credential_generation_positive")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_connector_providers_name_bounded")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_connector_providers_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_connector_providers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_connector_providers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_providers")),
    )
    op.create_index(
        "uq_connector_providers_organization_name",
        "connector_providers",
        ["organization_id", "normalized_name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.create_index(
        "ix_connector_providers_driver_status", "connector_providers", ["type", "status", "id"], unique=False
    )
    op.create_index(
        "ix_connector_providers_workspace_updated",
        "connector_providers",
        ["workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_connector_providers_id_organization", "connector_providers", ["id", "organization_id"], unique=True
    )
    op.create_index(
        "uq_connector_providers_workspace_name", "connector_providers", ["workspace_id", "normalized_name"], unique=True
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_connector_providers_workspace_name", table_name="connector_providers")
    op.drop_index("uq_connector_providers_id_organization", table_name="connector_providers")
    op.drop_index("ix_connector_providers_workspace_updated", table_name="connector_providers")
    op.drop_index("ix_connector_providers_driver_status", table_name="connector_providers")
    op.drop_table("connector_providers")
