"""add bot memory directory and sharing.

Revision ID: dec4ba43dd78
Revises: 96f61e7ecace
Create Date: 2026-09-15 15:42:11.355409+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dec4ba43dd78"
down_revision: str | Sequence[str] | None = "96f61e7ecace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_memory_scopes",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("provider_id", sa.String(length=72), nullable=False),
        sa.Column("external_conversation_id", sa.String(length=2048), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "audience IN ('public', 'private', 'direct', 'unknown')", name=op.f("ck_bot_memory_scopes_audience_valid")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_bot_memory_scopes_version_positive")),
        sa.ForeignKeyConstraint(
            ["account_id", "organization_id", "workspace_id"],
            ["application_accounts.id", "application_accounts.organization_id", "application_accounts.workspace_id"],
            name=op.f("fk_bot_memory_scopes_account_id_application_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id", "organization_id"],
            ["memory_providers.id", "memory_providers.organization_id"],
            name=op.f("fk_bot_memory_scopes_provider_id_memory_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_memory_scopes")),
        sa.UniqueConstraint(
            "account_id", "provider_id", "external_conversation_id", name="uq_bot_memory_scope_identity"
        ),
    )
    op.create_index(
        "ix_bot_memory_scopes_account", "bot_memory_scopes", ["account_id", "provider_id", "id"], unique=False
    )
    op.create_table(
        "bot_memory_sharing_policies",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("provider_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kinds_json", sa.JSON(), nullable=False),
        sa.Column("include_history", sa.Boolean(), nullable=False),
        sa.Column("enroll_future_groups", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("future_since", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_bot_memory_sharing_policies_version_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["application_accounts.id"],
            name=op.f("fk_bot_memory_sharing_policies_account_id_application_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["memory_providers.id"],
            name=op.f("fk_bot_memory_sharing_policies_provider_id_memory_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_memory_sharing_policies")),
    )
    op.create_index("ix_bot_memory_policies_account", "bot_memory_sharing_policies", ["account_id", "id"], unique=False)
    op.create_table(
        "bot_memory_documents",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("scope_id", sa.String(length=72), nullable=False),
        sa.Column("native_id", sa.String(length=512), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("body_digest", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=320), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("activity_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=128), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("correction_of", sa.String(length=72), nullable=True),
        sa.Column("publication_source_id", sa.String(length=72), nullable=True),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('daily', 'long_term')", name=op.f("ck_bot_memory_documents_kind_valid")),
        sa.CheckConstraint(
            "state != 'active' OR (native_id IS NOT NULL AND saved_at IS NOT NULL)",
            name=op.f("ck_bot_memory_documents_active_confirmed"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'active', 'unconfirmed', 'deleting', 'deleted')",
            name=op.f("ck_bot_memory_documents_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["correction_of"],
            ["bot_memory_documents.id"],
            name=op.f("fk_bot_memory_documents_correction_of_bot_memory_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["publication_source_id"],
            ["bot_memory_documents.id"],
            name=op.f("fk_bot_memory_documents_publication_source_id_bot_memory_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["bot_memory_scopes.id"],
            name=op.f("fk_bot_memory_documents_scope_id_bot_memory_scopes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_memory_documents")),
        sa.UniqueConstraint("scope_id", "native_id", name="uq_bot_memory_document_native"),
        sa.UniqueConstraint("scope_id", "request_key", name="uq_bot_memory_document_request"),
    )
    op.create_index(
        "ix_bot_memory_documents_browse",
        "bot_memory_documents",
        ["scope_id", "state", "activity_date", "id"],
        unique=False,
    )
    op.create_index(
        "ix_bot_memory_documents_source", "bot_memory_documents", ["publication_source_id", "state"], unique=False
    )
    op.create_table(
        "bot_memory_sharing_participants",
        sa.Column("policy_id", sa.String(length=72), nullable=False),
        sa.Column("scope_id", sa.String(length=72), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["bot_memory_sharing_policies.id"],
            name=op.f("fk_bot_memory_sharing_participants_policy_id_bot_memory_sharing_policies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["bot_memory_scopes.id"],
            name=op.f("fk_bot_memory_sharing_participants_scope_id_bot_memory_scopes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("policy_id", "scope_id", name=op.f("pk_bot_memory_sharing_participants")),
    )
    op.create_table(
        "bot_memory_publication_recipients",
        sa.Column("document_id", sa.String(length=72), nullable=False),
        sa.Column("scope_id", sa.String(length=72), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["bot_memory_documents.id"],
            name=op.f("fk_bot_memory_publication_recipients_document_id_bot_memory_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["bot_memory_scopes.id"],
            name=op.f("fk_bot_memory_publication_recipients_scope_id_bot_memory_scopes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("document_id", "scope_id", name=op.f("pk_bot_memory_publication_recipients")),
    )
    op.add_column("application_accounts", sa.Column("memory_json", sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_accounts", "memory_json")
    op.drop_table("bot_memory_publication_recipients")
    op.drop_table("bot_memory_sharing_participants")
    op.drop_index("ix_bot_memory_documents_source", table_name="bot_memory_documents")
    op.drop_index("ix_bot_memory_documents_browse", table_name="bot_memory_documents")
    op.drop_table("bot_memory_documents")
    op.drop_index("ix_bot_memory_policies_account", table_name="bot_memory_sharing_policies")
    op.drop_table("bot_memory_sharing_policies")
    op.drop_index("ix_bot_memory_scopes_account", table_name="bot_memory_scopes")
    op.drop_table("bot_memory_scopes")
    # ### end Alembic commands ###
