"""add configuration assistant scope drafts and immutable receipts.

Revision ID: cc0c0700dbc7
Revises: 838688629ca8
Create Date: 2026-09-15 18:21:56.823232+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cc0c0700dbc7"
down_revision: str | Sequence[str] | None = "838688629ca8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    triggers = []
    sqlite = op.get_bind().dialect.name == "sqlite"
    if sqlite:
        # This private migration connection holds the writer lock throughout the
        # rebuild. Disable FK actions so copying referenced tables cannot cascade
        # into existing data; check all references before committing the revision.
        op.get_bind().exec_driver_sql("PRAGMA foreign_keys=OFF")
        op.get_bind().exec_driver_sql("BEGIN IMMEDIATE")
        triggers = list(
            op.get_bind().exec_driver_sql(
                "SELECT name, sql FROM sqlite_schema WHERE type = 'trigger' AND sql IS NOT NULL"
            )
        )
        for name, _ in triggers:
            quoted = name.replace('"', '""')
            op.get_bind().exec_driver_sql(f'DROP TRIGGER "{quoted}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_drafts",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("owner_user_id", sa.String(length=72), nullable=False),
        sa.Column("session_id", sa.String(length=72), nullable=False),
        sa.Column("thread_id", sa.String(length=72), nullable=False),
        sa.Column("predecessor_draft_id", sa.String(length=72), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("target_agent_id", sa.String(length=72), nullable=True),
        sa.Column("source_selector", sa.String(length=16), nullable=False),
        sa.Column("source_agent_revision_id", sa.String(length=72), nullable=True),
        sa.Column("source_agent_revision_version", sa.BigInteger(), nullable=True),
        sa.Column("base_agent_revision_id", sa.String(length=72), nullable=True),
        sa.Column("base_agent_version", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("config", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("creation_metadata", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latest_validation", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("application_receipt", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("applied_agent_revision_id", sa.String(length=72), nullable=True),
        sa.Column("application_key_hash", sa.String(length=64), nullable=True),
        sa.Column("application_request_digest", sa.String(length=64), nullable=True),
        sa.Column("terminal_reason", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(mode = 'create' AND target_agent_id IS NULL AND source_selector = 'empty' AND source_agent_revision_id IS NULL AND source_agent_revision_version IS NULL AND base_agent_revision_id IS NULL AND base_agent_version IS NULL) OR (mode = 'update' AND target_agent_id IS NOT NULL AND source_selector <> 'empty' AND source_agent_revision_id IS NOT NULL AND source_agent_revision_version >= 1 AND base_agent_revision_id IS NOT NULL AND base_agent_version >= 1 AND config IS NOT NULL)",
            name=op.f("ck_configuration_drafts_source_shape_valid"),
        ),
        sa.CheckConstraint(
            "(status = 'applied' AND application_receipt IS NOT NULL AND applied_agent_revision_id IS NOT NULL AND application_key_hash IS NOT NULL AND application_request_digest IS NOT NULL) OR (status <> 'applied' AND application_receipt IS NULL AND applied_agent_revision_id IS NULL AND application_key_hash IS NULL AND application_request_digest IS NULL)",
            name=op.f("ck_configuration_drafts_application_receipt_consistent"),
        ),
        sa.CheckConstraint(
            "source_selector IN ('current', 'explicit', 'empty')",
            name=op.f("ck_configuration_drafts_source_selector_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'applied', 'discarded', 'expired')", name=op.f("ck_configuration_drafts_status_valid")
        ),
        sa.CheckConstraint("length(content_digest) = 64", name=op.f("ck_configuration_drafts_digest_sha256")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_configuration_drafts_version_positive")),
        sa.ForeignKeyConstraint(
            ["applied_agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_configuration_drafts_applied_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["base_agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_configuration_drafts_base_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "session_id", "thread_id"],
            ["threads.organization_id", "threads.session_id", "threads.id"],
            name=op.f("fk_configuration_drafts_organization_id_threads"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_configuration_drafts_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_draft_id"],
            ["configuration_drafts.id"],
            name=op.f("fk_configuration_drafts_predecessor_draft_id_configuration_drafts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_configuration_drafts_source_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_configuration_drafts_target_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_configuration_drafts_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_drafts")),
    )
    op.create_index(
        "ix_configuration_drafts_owner_updated",
        "configuration_drafts",
        ["workspace_id", "owner_user_id", "updated_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_configuration_drafts_open_thread",
        "configuration_drafts",
        ["thread_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
        sqlite_where=sa.text("status = 'open'"),
    )
    op.create_index(
        "uq_configuration_drafts_thread_id",
        "configuration_drafts",
        ["id", "organization_id", "session_id", "thread_id"],
        unique=True,
    )
    with op.batch_alter_table("agent_revisions") as batch:
        batch.add_column(sa.Column("system_definition", sa.JSON(none_as_null=True), nullable=True))
    with op.batch_alter_table("agents") as batch:
        batch.add_column(sa.Column("system_purpose", sa.String(length=32), nullable=True))
    op.create_index("uq_agents_workspace_system_purpose", "agents", ["workspace_id", "system_purpose"], unique=True)
    with op.batch_alter_table("agents") as batch:
        batch.create_check_constraint(
            op.f("ck_agents_system_purpose_valid"),
            "system_purpose IS NULL OR (system_purpose = 'configuration_assistant' AND source = 'builtin')",
        )
    with op.batch_alter_table("runs") as batch:
        batch.add_column(sa.Column("configuration_context", sa.JSON(none_as_null=True), nullable=True))
        batch.add_column(sa.Column("configuration_draft_id", sa.String(length=72), nullable=True))
        batch.create_foreign_key(
            "fk_runs_configuration_draft_same_thread",
            "configuration_drafts",
            ["configuration_draft_id", "organization_id", "session_id", "thread_id"],
            ["id", "organization_id", "session_id", "thread_id"],
            ondelete="RESTRICT",
            use_alter=True,
        )
        batch.create_check_constraint(
            op.f("ck_runs_configuration_binding_consistent"),
            "(configuration_draft_id IS NULL AND configuration_context IS NULL) OR (configuration_draft_id IS NOT NULL AND configuration_context IS NOT NULL)",
        )
    with op.batch_alter_table("sessions") as batch:
        batch.add_column(sa.Column("configuration_owner_user_id", sa.String(length=72), nullable=True))
        batch.add_column(sa.Column("configuration_target_agent_id", sa.String(length=72), nullable=True))
    op.create_index(
        "ix_sessions_configuration_owner",
        "sessions",
        ["workspace_id", "configuration_owner_user_id", "updated_at", "id"],
        unique=False,
    )
    with op.batch_alter_table("sessions") as batch:
        batch.create_foreign_key(
            op.f("fk_sessions_configuration_target_agent_id_agents"),
            "agents",
            ["configuration_target_agent_id", "organization_id", "workspace_id"],
            ["id", "organization_id", "workspace_id"],
            ondelete="RESTRICT",
        )
        batch.create_foreign_key(
            op.f("fk_sessions_configuration_owner_user_id_users"),
            "users",
            ["configuration_owner_user_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch.create_check_constraint(
            op.f("ck_sessions_configuration_scope_valid"),
            "configuration_owner_user_id IS NOT NULL OR configuration_target_agent_id IS NULL",
        )
    with op.batch_alter_table("threads", copy_from=_sqlite_threads() if sqlite else None) as batch:
        batch.add_column(sa.Column("configuration_active_draft_id", sa.String(length=72), nullable=True))
        batch.add_column(sa.Column("configuration_latest_draft_id", sa.String(length=72), nullable=True))
        batch.create_foreign_key(
            "fk_threads_configuration_latest_draft",
            "configuration_drafts",
            ["configuration_latest_draft_id", "organization_id", "session_id", "id"],
            ["id", "organization_id", "session_id", "thread_id"],
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        )
        batch.create_foreign_key(
            "fk_threads_configuration_active_draft",
            "configuration_drafts",
            ["configuration_active_draft_id", "organization_id", "session_id", "id"],
            ["id", "organization_id", "session_id", "thread_id"],
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        )
    # ### end Alembic commands ###
    if sqlite:
        for _, statement in triggers:
            op.get_bind().exec_driver_sql(statement)
        op.execute(
            sa.text(
                "CREATE INDEX IF NOT EXISTS ix_threads_selected_run ON threads (organization_id, coalesce(current_run_id, head_run_id))"
            )
        )
        if op.get_bind().exec_driver_sql("PRAGMA foreign_key_check").first() is not None:
            raise RuntimeError("Configuration migration would violate foreign key integrity.")


def downgrade() -> None:
    """Reverse only before configuration data exists; never erase its protection."""
    connection = op.get_bind()
    if connection.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM configuration_drafts) "
            "OR EXISTS (SELECT 1 FROM sessions WHERE configuration_owner_user_id IS NOT NULL) "
            "OR EXISTS (SELECT 1 FROM agents WHERE system_purpose IS NOT NULL) "
            "OR EXISTS (SELECT 1 FROM runs WHERE configuration_context IS NOT NULL)"
        )
    ).scalar():
        raise RuntimeError("Cannot downgrade while protected configuration assistant data exists.")
    triggers = []
    sqlite = op.get_bind().dialect.name == "sqlite"
    if sqlite:
        # This private migration connection holds the writer lock throughout the
        # rebuild. Disable FK actions so copying referenced tables cannot cascade
        # into existing data; check all references before committing the revision.
        op.get_bind().exec_driver_sql("PRAGMA foreign_keys=OFF")
        op.get_bind().exec_driver_sql("BEGIN IMMEDIATE")
        triggers = list(
            op.get_bind().exec_driver_sql(
                "SELECT name, sql FROM sqlite_schema WHERE type = 'trigger' AND sql IS NOT NULL"
            )
        )
        for name, _ in triggers:
            quoted = name.replace('"', '""')
            op.get_bind().exec_driver_sql(f'DROP TRIGGER "{quoted}"')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", copy_from=_sqlite_threads() if sqlite else None) as batch:
        batch.drop_constraint("fk_threads_configuration_active_draft", type_="foreignkey")
        batch.drop_constraint("fk_threads_configuration_latest_draft", type_="foreignkey")
        batch.drop_column("configuration_latest_draft_id")
        batch.drop_column("configuration_active_draft_id")
    with op.batch_alter_table("sessions") as batch:
        batch.drop_constraint(op.f("ck_sessions_configuration_scope_valid"), type_="check")
        batch.drop_constraint(op.f("fk_sessions_configuration_owner_user_id_users"), type_="foreignkey")
        batch.drop_constraint(op.f("fk_sessions_configuration_target_agent_id_agents"), type_="foreignkey")
    op.drop_index("ix_sessions_configuration_owner", table_name="sessions")
    with op.batch_alter_table("sessions") as batch:
        batch.drop_column("configuration_target_agent_id")
        batch.drop_column("configuration_owner_user_id")
    with op.batch_alter_table("runs") as batch:
        batch.drop_constraint(op.f("ck_runs_configuration_binding_consistent"), type_="check")
        batch.drop_constraint("fk_runs_configuration_draft_same_thread", type_="foreignkey")
        batch.drop_column("configuration_draft_id")
        batch.drop_column("configuration_context")
    with op.batch_alter_table("agents") as batch:
        batch.drop_constraint(op.f("ck_agents_system_purpose_valid"), type_="check")
    op.drop_index("uq_agents_workspace_system_purpose", table_name="agents")
    with op.batch_alter_table("agents") as batch:
        batch.drop_column("system_purpose")
    with op.batch_alter_table("agent_revisions") as batch:
        batch.drop_column("system_definition")
    op.drop_index("uq_configuration_drafts_thread_id", table_name="configuration_drafts")
    op.drop_index(
        "uq_configuration_drafts_open_thread",
        table_name="configuration_drafts",
        postgresql_where=sa.text("status = 'open'"),
        sqlite_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_configuration_drafts_owner_updated", table_name="configuration_drafts")
    op.drop_table("configuration_drafts")
    # ### end Alembic commands ###
    if sqlite:
        for _, statement in triggers:
            op.get_bind().exec_driver_sql(statement)
        op.execute(
            sa.text(
                "CREATE INDEX IF NOT EXISTS ix_threads_selected_run ON threads (organization_id, coalesce(current_run_id, head_run_id))"
            )
        )
        if op.get_bind().exec_driver_sql("PRAGMA foreign_key_check").first() is not None:
            raise RuntimeError("Configuration migration would violate foreign key integrity.")


def _sqlite_threads() -> sa.Table:
    # Keep accounting checks inline: the owning earlier revision drops these
    # columns natively on downgrade. Reflection otherwise moves them to the table.
    table = sa.Table("threads", sa.MetaData(), autoload_with=op.get_bind())
    for name in ("next_delivery_sequence", "pending_count", "pending_bytes"):
        suffix = "positive" if name == "next_delivery_sequence" else "non_negative"
        constraint_name = f"ck_threads_{name}_{suffix}"
        check = next(item for item in table.constraints if item.name == constraint_name)
        assert isinstance(check, sa.CheckConstraint)
        table.constraints.remove(check)
        table.c[name].constraints.add(sa.CheckConstraint(check.sqltext, name=constraint_name))
    return table
