"""add bot verification observations.

Revision ID: fa5bed0a37f2
Revises: 6d411183b2c5
Create Date: 2026-09-15 16:53:50.445436+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fa5bed0a37f2"
down_revision: str | Sequence[str] | None = "6d411183b2c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_checks",
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["application_accounts.id"],
            name=op.f("fk_bot_checks_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id", "conversation_id", name=op.f("pk_bot_checks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_checks")
    # ### end Alembic commands ###
