"""add a2a push configurations.

Revision ID: 0d5f1ae47708
Revises: e68684416aa8
Create Date: 2026-09-04 13:33:22.179973+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d5f1ae47708"
down_revision: str | Sequence[str] | None = "e68684416aa8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "a2a_push_configurations",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("task_id", sa.String(length=72), nullable=False),
        sa.Column("creator_principal_type", sa.String(length=32), nullable=False),
        sa.Column("creator_principal_id", sa.String(length=72), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2048), nullable=False),
        sa.Column("authentication_scheme", sa.String(length=128), nullable=True),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("delivery_generation", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'active' AND deleted_at IS NULL) OR (state = 'disabled' AND deleted_at IS NOT NULL)",
            name=op.f("ck_a2a_push_configurations_lifecycle_valid"),
        ),
        sa.CheckConstraint(
            "creator_principal_type IN ('user', 'service_account')",
            name=op.f("ck_a2a_push_configurations_creator_type_valid"),
        ),
        sa.CheckConstraint("state IN ('active', 'disabled')", name=op.f("ck_a2a_push_configurations_state_valid")),
        sa.CheckConstraint(
            "(ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL) OR "
            "(ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL)",
            name=op.f("ck_a2a_push_configurations_credential_material_consistent"),
        ),
        sa.CheckConstraint(
            "credential_generation >= 1",
            name=op.f("ck_a2a_push_configurations_credential_generation_positive"),
        ),
        sa.CheckConstraint(
            "delivery_generation >= 1", name=op.f("ck_a2a_push_configurations_delivery_generation_positive")
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "organization_id"],
            ["a2a_task_bindings.id", "a2a_task_bindings.organization_id"],
            name=op.f("fk_a2a_push_configurations_task_id_a2a_task_bindings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_a2a_push_configurations")),
        sa.UniqueConstraint("organization_id", "id", name="uq_a2a_push_configurations_organization_id"),
    )
    op.create_index(
        "ix_a2a_push_configurations_task",
        "a2a_push_configurations",
        ["organization_id", "task_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_a2a_push_configurations_task", table_name="a2a_push_configurations")
    op.drop_table("a2a_push_configurations")
    # ### end Alembic commands ###
