"""fence conversation memory bindings across target recreation.

Revision ID: eb41d745e5d0
Revises: 4662868f6a0f
Create Date: 2026-09-16 05:10:54.097898+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eb41d745e5d0"
down_revision: str | Sequence[str] | None = "4662868f6a0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_memory_scopes", sa.Column("binding_floor", sa.Integer(), server_default="1", nullable=False))
    op.execute("UPDATE bot_memory_scopes SET binding_floor = version + 1 WHERE audience = 'unknown'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    fenced = (
        op.get_bind()
        .execute(sa.text("SELECT EXISTS (SELECT 1 FROM bot_memory_scopes WHERE binding_floor > 1)"))
        .scalar_one()
    )
    if fenced:
        raise RuntimeError("Conversation revocation fences cannot be downgraded; retain this schema and roll forward")
    op.drop_column("bot_memory_scopes", "binding_floor")
    # ### end Alembic commands ###
