"""retain filesystem memory storage bindings.

Revision ID: f38b358b08bd
Revises: f2abf114c374
Create Date: 2026-09-18 08:30:15.514158+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f38b358b08bd"
down_revision: str | Sequence[str] | None = "f2abf114c374"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_storage_bindings",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("target_digest", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("provider_identity", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("environment_id", sa.String(length=72), nullable=False),
        sa.Column("root", sa.Text(), nullable=False),
        sa.Column("backing_identity", sa.String(length=256), nullable=False),
        sa.Column("initialized", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_memory_storage_bindings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_storage_bindings")),
    )
    op.create_index("uq_memory_storage_target", "memory_storage_bindings", ["target_digest"], unique=True)
    op.create_table(
        "run_memory_storage_bindings",
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("selection_digest", sa.String(length=64), nullable=False),
        sa.Column("storage_id", sa.String(length=72), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_memory_storage_bindings_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["memory_storage_bindings.id"],
            name=op.f("fk_run_memory_storage_bindings_storage_id_memory_storage_bindings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", "selection_digest", name=op.f("pk_run_memory_storage_bindings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_memory_storage_bindings")
    op.drop_index("uq_memory_storage_target", table_name="memory_storage_bindings")
    op.drop_table("memory_storage_bindings")
    # ### end Alembic commands ###
