"""retain bot settings generation in setup evidence.

Revision ID: 4662868f6a0f
Revises: 1ca0ca92df47
Create Date: 2026-09-16 04:58:23.978068+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4662868f6a0f"
down_revision: str | Sequence[str] | None = "1ca0ca92df47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_replies", sa.Column("settings_version", sa.BigInteger(), server_default="0", nullable=False))
    op.add_column("bot_tests", sa.Column("settings_version", sa.BigInteger(), server_default="0", nullable=False))
    op.execute(
        "UPDATE bot_tests t SET settings_version = s.version FROM bot_account_settings s WHERE s.account_id = t.account_id"
    )
    op.execute(
        "UPDATE bot_replies r SET settings_version = s.version FROM bot_account_settings s WHERE s.account_id = r.account_id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_tests", "settings_version")
    op.drop_column("bot_replies", "settings_version")
    # ### end Alembic commands ###
