"""initialize mcp connections.

Revision ID: 6a290c689265
Revises: f1f948fa1903
Create Date: 2026-09-04 08:22:17.588102+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a290c689265"
down_revision: str | Sequence[str] | None = "f1f948fa1903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_connections",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("normalized_name", sa.String(length=384), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2048), nullable=False),
        sa.Column("auth_mode", sa.String(length=32), nullable=False),
        sa.Column("static_header_names_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.String(length=32), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("refresh_claim_generation", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("refresh_claim_owner", sa.String(length=128), nullable=True),
        sa.Column("refresh_claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "(status = 'action_required') = (status_reason IS NOT NULL)",
            name=op.f("ck_mcp_connections_status_reason_valid"),
        ),
        sa.CheckConstraint(
            "auth_mode IN ('none', 'bearer', 'oauth', 'static_headers')",
            name=op.f("ck_mcp_connections_auth_mode_valid"),
        ),
        sa.CheckConstraint(
            "created_by_type IN ('user', 'service_account')", name=op.f("ck_mcp_connections_created_by_type_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'action_required', 'disabled')",
            name=op.f("ck_mcp_connections_status_valid"),
        ),
        sa.CheckConstraint(
            "status_reason IS NULL OR status_reason IN ('reauthorization_required', 'incompatible')",
            name=op.f("ck_mcp_connections_status_reason_value_valid"),
        ),
        sa.CheckConstraint(
            "(ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL) OR (ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL)",
            name=op.f("ck_mcp_connections_credential_material_consistent"),
        ),
        sa.CheckConstraint(
            "credential_generation >= 0", name=op.f("ck_mcp_connections_credential_generation_non_negative")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_mcp_connections_name_bounded")),
        sa.CheckConstraint(
            "refresh_claim_generation >= 0", name=op.f("ck_mcp_connections_refresh_claim_generation_non_negative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_mcp_connections_version_positive")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_mcp_connections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_connections")),
    )
    op.create_index(
        "ix_mcp_connections_workspace_updated", "mcp_connections", ["workspace_id", "updated_at", "id"], unique=False
    )
    op.create_index(
        "uq_mcp_connections_id_organization", "mcp_connections", ["id", "organization_id", "workspace_id"], unique=True
    )
    op.create_index(
        "uq_mcp_connections_workspace_name", "mcp_connections", ["workspace_id", "normalized_name"], unique=True
    )
    op.create_table(
        "mcp_oauth_sessions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("mcp_connection_id", sa.String(length=72), nullable=False),
        sa.Column("initiating_user_id", sa.String(length=72), nullable=False),
        sa.Column("connection_version", sa.BigInteger(), nullable=False),
        sa.Column("state_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("claim_generation", sa.BigInteger(), nullable=False),
        sa.Column("claim_owner", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'received', 'exchanging', 'completed', 'failed', 'expired')",
            name=op.f("ck_mcp_oauth_sessions_status_valid"),
        ),
        sa.CheckConstraint(
            "(ciphertext IS NULL AND nonce IS NULL AND encryption_key_id IS NULL) OR (ciphertext IS NOT NULL AND nonce IS NOT NULL AND encryption_key_id IS NOT NULL)",
            name=op.f("ck_mcp_oauth_sessions_credential_material_consistent"),
        ),
        sa.CheckConstraint("claim_generation >= 0", name=op.f("ck_mcp_oauth_sessions_claim_generation_non_negative")),
        sa.CheckConstraint(
            "credential_generation >= 1", name=op.f("ck_mcp_oauth_sessions_credential_generation_positive")
        ),
        sa.ForeignKeyConstraint(
            ["initiating_user_id"],
            ["users.id"],
            name=op.f("fk_mcp_oauth_sessions_initiating_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mcp_connection_id", "organization_id", "workspace_id"],
            ["mcp_connections.id", "mcp_connections.organization_id", "mcp_connections.workspace_id"],
            name=op.f("fk_mcp_oauth_sessions_mcp_connection_id_mcp_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_oauth_sessions")),
    )
    op.create_index(
        "ix_mcp_oauth_sessions_connection",
        "mcp_oauth_sessions",
        ["mcp_connection_id", "status", "created_at", "id"],
        unique=False,
    )
    op.create_index("ix_mcp_oauth_sessions_expiry", "mcp_oauth_sessions", ["status", "expires_at", "id"], unique=False)
    op.create_index("uq_mcp_oauth_sessions_state", "mcp_oauth_sessions", ["state_digest"], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_mcp_oauth_sessions_state", table_name="mcp_oauth_sessions")
    op.drop_index("ix_mcp_oauth_sessions_expiry", table_name="mcp_oauth_sessions")
    op.drop_index("ix_mcp_oauth_sessions_connection", table_name="mcp_oauth_sessions")
    op.drop_table("mcp_oauth_sessions")
    op.drop_index("uq_mcp_connections_workspace_name", table_name="mcp_connections")
    op.drop_index("uq_mcp_connections_id_organization", table_name="mcp_connections")
    op.drop_index("ix_mcp_connections_workspace_updated", table_name="mcp_connections")
    op.drop_table("mcp_connections")
