"""add durable memory organization work.

Revision ID: 7925615e9e83
Revises: 08a74ef312ee
Create Date: 2026-09-18 09:28:18.073848+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7925615e9e83"
down_revision: str | Sequence[str] | None = "08a74ef312ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_organization_work",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("storage_id", sa.String(length=72), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("plan_digest", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("owner", sa.String(length=72), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_memory_organization_work_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["memory_storage_bindings.id"],
            name=op.f("fk_memory_organization_work_storage_id_memory_storage_bindings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_organization_work")),
    )
    op.create_index(
        "ix_memory_organization_pending", "memory_organization_work", ["status", "available_at"], unique=False
    )
    op.add_column(
        "bot_account_settings", sa.Column("auto_organize", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "bot_run_memory_bindings", sa.Column("auto_organize", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("run_memory_storage_bindings", sa.Column("organization_policy", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("run_memory_storage_bindings", "organization_policy")
    op.drop_column("bot_run_memory_bindings", "auto_organize")
    op.drop_column("bot_account_settings", "auto_organize")
    op.drop_index("ix_memory_organization_pending", table_name="memory_organization_work")
    op.drop_table("memory_organization_work")
    # ### end Alembic commands ###
