"""retain bot memory execution binding.

Revision ID: 6d411183b2c5
Revises: dec4ba43dd78
Create Date: 2026-09-15 16:04:24.757694+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d411183b2c5"
down_revision: str | Sequence[str] | None = "dec4ba43dd78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("bot_memory_json", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "bot_memory_json")
    # ### end Alembic commands ###
