"""add workspace media understanding defaults.

Revision ID: fe344bbb730f
Revises: ec56e4426fb7
Create Date: 2026-09-20 07:45:29.253070+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fe344bbb730f"
down_revision: str | Sequence[str] | None = "ec56e4426fb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_media_understanding_defaults",
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("image_model_id", sa.String(length=72), nullable=True),
        sa.Column("video_model_id", sa.String(length=72), nullable=True),
        sa.Column("audio_model_id", sa.String(length=72), nullable=True),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workspace_media_understanding_defaults_version_positive")),
        sa.ForeignKeyConstraint(
            ["audio_model_id"],
            ["models.id"],
            name=op.f("fk_workspace_media_understanding_defaults_audio_model_id_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_model_id"],
            ["models.id"],
            name=op.f("fk_workspace_media_understanding_defaults_image_model_id_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["video_model_id"],
            ["models.id"],
            name=op.f("fk_workspace_media_understanding_defaults_video_model_id_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_media_understanding_defaults_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_workspace_media_understanding_defaults")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_media_understanding_defaults")
    # ### end Alembic commands ###
