"""record native bot reply observations.

Revision ID: 68dd93a34500
Revises: 531e35084653
Create Date: 2026-09-15 19:16:43.872692+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "68dd93a34500"
down_revision: str | Sequence[str] | None = "531e35084653"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_replies",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("binding_id", sa.String(length=72), nullable=False),
        sa.Column("target_id", sa.String(length=72), nullable=True),
        sa.Column("run_id", sa.String(length=72), nullable=False),
        sa.Column("run_attempt_id", sa.String(length=72), nullable=False),
        sa.Column("provider_key", sa.String(length=16), nullable=False),
        sa.Column("account_version", sa.BigInteger(), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("receipt_json", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'dispatching') = (finished_at IS NULL)", name=op.f("ck_bot_replies_completion_valid")
        ),
        sa.CheckConstraint(
            "(status = 'succeeded') = (receipt_json IS NOT NULL)", name=op.f("ck_bot_replies_receipt_valid")
        ),
        sa.CheckConstraint("provider_key IN ('slack', 'lark')", name=op.f("ck_bot_replies_provider_valid")),
        sa.CheckConstraint(
            "status IN ('dispatching', 'succeeded', 'rejected', 'outcome_unknown')",
            name=op.f("ck_bot_replies_status_valid"),
        ),
        sa.CheckConstraint(
            "account_version >= 1 AND credential_generation >= 1", name=op.f("ck_bot_replies_generation_valid")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "organization_id", "workspace_id"],
            ["application_accounts.id", "application_accounts.organization_id", "application_accounts.workspace_id"],
            name=op.f("fk_bot_replies_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["binding_id", "organization_id", "workspace_id"],
            ["agent_thread_bindings.id", "agent_thread_bindings.organization_id", "agent_thread_bindings.workspace_id"],
            name=op.f("fk_bot_replies_binding_id_agent_thread_bindings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id", "run_attempt_id"],
            ["run_attempts.organization_id", "run_attempts.run_id", "run_attempts.id"],
            name=op.f("fk_bot_replies_organization_id_run_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_replies")),
    )
    op.create_index("ix_bot_replies_account_started", "bot_replies", ["account_id", "started_at", "id"], unique=False)
    op.create_index("ix_bot_replies_run_started", "bot_replies", ["run_id", "started_at", "id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bot_replies_run_started", table_name="bot_replies")
    op.drop_index("ix_bot_replies_account_started", table_name="bot_replies")
    op.drop_table("bot_replies")
    # ### end Alembic commands ###
