"""initialize Environment providers, templates, and instances.

Revision ID: 568f8270be7a
Revises: f20843000572
Create Date: 2026-09-04 08:21:49.703184+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "568f8270be7a"
down_revision: str | Sequence[str] | None = "f20843000572"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environment_providers",
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("configuration_source", sa.String(length=16), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=True),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_environment_providers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_environment_providers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "configuration_source IN ('user', 'deployment')",
            name=op.f("ck_environment_providers_configuration_source_valid"),
        ),
        sa.CheckConstraint(
            "configuration_source != 'deployment' OR workspace_id IS NULL",
            name=op.f("ck_environment_providers_deployment_organization"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_providers")),
        sa.UniqueConstraint("id", "organization_id", name="uq_environment_providers_scope"),
    )
    op.create_index("ix_environment_providers_workspace", "environment_providers", ["workspace_id", "id"], unique=False)
    op.create_table(
        "environment_templates",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=True),
        sa.Column(
            "labels",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("current_revision_id", sa.String(length=72), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_environment_templates_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_environment_templates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_environment_templates_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_templates")),
        sa.UniqueConstraint("id", "organization_id", name="uq_environment_templates_scope"),
    )
    op.create_index("ix_environment_templates_workspace", "environment_templates", ["workspace_id", "id"], unique=False)
    op.create_index(
        "ix_environment_templates_labels",
        "environment_templates",
        ["labels"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.create_table(
        "environment_template_revisions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("template_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=True),
        sa.Column("provider_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("recipe", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_environment_template_revisions_version_positive")),
        sa.ForeignKeyConstraint(
            ["provider_id", "organization_id"],
            ["environment_providers.id", "environment_providers.organization_id"],
            name=op.f("fk_environment_template_revisions_provider_id_environment_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id", "organization_id"],
            ["environment_templates.id", "environment_templates.organization_id"],
            name=op.f("fk_environment_template_revisions_template_id_environment_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_template_revisions")),
        sa.UniqueConstraint("id", "provider_id", "organization_id", name="uq_environment_template_revisions_provider"),
        sa.UniqueConstraint("template_id", "version", name="uq_environment_template_revisions_version"),
    )
    op.create_table(
        "environments",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "labels",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("provider_id", sa.String(length=72), nullable=False),
        sa.Column("template_revision_id", sa.String(length=72), nullable=True),
        sa.Column("ownership", sa.String(length=16), nullable=False),
        sa.Column("access", sa.String(length=16), nullable=False),
        sa.Column("external_configuration", sa.JSON(), nullable=True),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.Column("target_identity", sa.String(length=256), nullable=True),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("retention_condition", sa.String(length=32), nullable=False),
        sa.Column("condition_since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("operation_generation", sa.BigInteger(), nullable=False),
        sa.Column("operation_id", sa.String(length=72), nullable=True),
        sa.Column("operation_action", sa.String(length=16), nullable=True),
        sa.Column("operation_owner", sa.String(length=72), nullable=True),
        sa.Column("operation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_maintenance_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(ownership = 'managed' AND template_revision_id IS NOT NULL) OR (ownership = 'external' AND template_revision_id IS NULL)",
            name=op.f("ck_environments_ownership_recipe"),
        ),
        sa.CheckConstraint(
            "retention_condition IN ('active','idle')", name=op.f("ck_environments_retention_condition_valid")
        ),
        sa.CheckConstraint(
            "status IN ('unprepared','running','stopped','deleted','unavailable')",
            name=op.f("ck_environments_status_valid"),
        ),
        sa.CheckConstraint(
            "generation >= 0 AND operation_generation >= 0", name=op.f("ck_environments_generation_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_environments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id", "organization_id"],
            ["environment_providers.id", "environment_providers.organization_id"],
            name=op.f("fk_environments_provider_id_environment_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["template_revision_id", "provider_id", "organization_id"],
            [
                "environment_template_revisions.id",
                "environment_template_revisions.provider_id",
                "environment_template_revisions.organization_id",
            ],
            name=op.f("fk_environments_template_revision_id_environment_template_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_environments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environments")),
        sa.UniqueConstraint("id", "workspace_id", name="uq_environments_scope"),
        sa.UniqueConstraint("target_identity", name="uq_environments_provider_target"),
    )
    op.create_index("ix_environments_maintenance", "environments", ["next_maintenance_at", "id"], unique=False)
    op.create_index("ix_environments_capacity", "environments", ["workspace_id", "ownership", "status"], unique=False)
    op.create_index(
        "ix_environments_labels",
        "environments",
        ["labels"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.create_table(
        "environment_commands",
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("environment_id", sa.String(length=72), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("action IN ('stop', 'delete')", name=op.f("ck_environment_commands_action_valid")),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')", name=op.f("ck_environment_commands_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], name=op.f("fk_environment_commands_environment_id_environments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_commands")),
    )


def downgrade() -> None:
    op.drop_table("environment_commands")
    op.drop_table("environments")
    op.drop_table("environment_template_revisions")
    op.drop_table("environment_templates")
    op.drop_table("environment_providers")
