"""correlate bot setup test observations.

Revision ID: 042c77935852
Revises: 68dd93a34500
Create Date: 2026-09-15 19:48:31.231327+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "042c77935852"
down_revision: str | Sequence[str] | None = "68dd93a34500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_tests",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("account_id", sa.String(length=72), nullable=False),
        sa.Column("account_version", sa.BigInteger(), nullable=False),
        sa.Column("credential_generation", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.String(length=72), nullable=False),
        sa.Column("target_version", sa.BigInteger(), nullable=False),
        sa.Column("external_target_id", sa.String(length=2048), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admission_id", sa.String(length=72), nullable=True),
        sa.Column("batch_id", sa.String(length=72), nullable=True),
        sa.Column("binding_id", sa.String(length=72), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_id", sa.String(length=72), nullable=True),
        sa.Column("steer_id", sa.String(length=72), nullable=True),
        sa.Column("rejection_code", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "account_version >= 1 AND credential_generation >= 1 AND target_version >= 1",
            name=op.f("ck_bot_tests_generation_valid"),
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_bot_tests_deadline_valid")),
        sa.ForeignKeyConstraint(
            ["account_id", "organization_id", "workspace_id"],
            ["application_accounts.id", "application_accounts.organization_id", "application_accounts.workspace_id"],
            name=op.f("fk_bot_tests_account_id_application_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_tests")),
    )
    op.create_index("ix_bot_tests_account_created", "bot_tests", ["account_id", "created_at", "id"], unique=False)
    op.create_index("ix_bot_tests_batch", "bot_tests", ["batch_id"], unique=False)
    op.add_column("bot_replies", sa.Column("test_id", sa.String(length=72), nullable=True))
    op.create_index(op.f("ix_bot_replies_test_id"), "bot_replies", ["test_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_bot_replies_test_id_bot_tests"), "bot_replies", "bot_tests", ["test_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when it is safe to do so."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_bot_replies_test_id_bot_tests"), "bot_replies", type_="foreignkey")
    op.drop_index(op.f("ix_bot_replies_test_id"), table_name="bot_replies")
    op.drop_column("bot_replies", "test_id")
    op.drop_index("ix_bot_tests_batch", table_name="bot_tests")
    op.drop_index("ix_bot_tests_account_created", table_name="bot_tests")
    op.drop_table("bot_tests")
    # ### end Alembic commands ###
