"""add configuration assistant sessions drafts and applications.

Revision ID: 0264713d02b1
Revises: 042c77935852
Create Date: 2026-09-16 03:59:39.788517+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0264713d02b1"
down_revision: str | Sequence[str] | None = "042c77935852"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_drafts",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("session_id", sa.String(length=72), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("target_agent_id", sa.String(length=72), nullable=True),
        sa.Column("source_selector", sa.String(length=16), nullable=False),
        sa.Column("source_agent_revision_id", sa.String(length=72), nullable=True),
        sa.Column("source_agent_revision_version", sa.BigInteger(), nullable=True),
        sa.Column("base_agent_revision_id", sa.String(length=72), nullable=True),
        sa.Column("base_agent_version", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("config", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("creation_metadata", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latest_validation", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("terminal_reason", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(mode = 'create' AND target_agent_id IS NULL AND source_selector = 'empty' AND base_agent_revision_id IS NULL AND base_agent_version IS NULL) OR (mode = 'update' AND target_agent_id IS NOT NULL AND base_agent_revision_id IS NOT NULL AND base_agent_version IS NOT NULL AND base_agent_version >= 1 AND config IS NOT NULL)",
            name=op.f("ck_configuration_drafts_target_shape_valid"),
        ),
        sa.CheckConstraint(
            "(source_selector = 'empty' AND source_agent_revision_id IS NULL AND source_agent_revision_version IS NULL) OR (source_selector <> 'empty' AND source_agent_revision_id IS NOT NULL AND source_agent_revision_version IS NOT NULL AND source_agent_revision_version >= 1)",
            name=op.f("ck_configuration_drafts_source_shape_valid"),
        ),
        sa.CheckConstraint(
            "source_selector IN ('current', 'explicit', 'empty')",
            name=op.f("ck_configuration_drafts_source_selector_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'discarded', 'expired')", name=op.f("ck_configuration_drafts_status_valid")
        ),
        sa.CheckConstraint("length(content_digest) = 64", name=op.f("ck_configuration_drafts_digest_sha256")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_configuration_drafts_version_positive")),
        sa.ForeignKeyConstraint(
            ["base_agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_configuration_drafts_base_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "session_id"],
            ["sessions.organization_id", "sessions.id"],
            name=op.f("fk_configuration_drafts_organization_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_configuration_drafts_source_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id", "organization_id", "workspace_id"],
            ["agents.id", "agents.organization_id", "agents.workspace_id"],
            name=op.f("fk_configuration_drafts_target_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "organization_id"],
            ["workspaces.id", "workspaces.organization_id"],
            name=op.f("fk_configuration_drafts_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_drafts")),
        sa.UniqueConstraint("id", "organization_id", "session_id", name="uq_configuration_drafts_session_scope"),
        sa.UniqueConstraint("id", "organization_id", "workspace_id", name="uq_configuration_drafts_scope"),
        sa.UniqueConstraint("session_id", name="uq_configuration_drafts_session"),
    )
    op.create_table(
        "configuration_applications",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("draft_id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(length=72), nullable=False),
        sa.Column("reviewed_version", sa.BigInteger(), nullable=False),
        sa.Column("agent_revision_id", sa.String(length=72), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("receipt", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("reviewed_version >= 1", name=op.f("ck_configuration_applications_version_positive")),
        sa.ForeignKeyConstraint(
            ["agent_revision_id", "organization_id", "workspace_id"],
            ["agent_revisions.id", "agent_revisions.organization_id", "agent_revisions.workspace_id"],
            name=op.f("fk_configuration_applications_agent_revision_id_agent_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["draft_id", "organization_id", "workspace_id"],
            ["configuration_drafts.id", "configuration_drafts.organization_id", "configuration_drafts.workspace_id"],
            name=op.f("fk_configuration_applications_draft_id_configuration_drafts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_applications")),
        sa.UniqueConstraint("draft_id", "key_hash", name="uq_configuration_applications_key"),
        sa.UniqueConstraint("draft_id", "reviewed_version", name="uq_configuration_applications_version"),
    )
    op.create_index(
        "ix_configuration_applications_draft_created",
        "configuration_applications",
        ["draft_id", "created_at", "id"],
        unique=False,
    )
    op.add_column("agents", sa.Column("system_purpose", sa.String(length=32), nullable=True))
    op.alter_column("agents", "current_revision_id", existing_type=sa.VARCHAR(length=72), nullable=True)
    op.create_index("uq_agents_workspace_system_purpose", "agents", ["workspace_id", "system_purpose"], unique=True)
    op.create_check_constraint(
        op.f("ck_agents_revision_source_valid"),
        "agents",
        "(system_purpose IS NULL AND current_revision_id IS NOT NULL) OR (system_purpose IS NOT NULL AND system_purpose = 'configuration_assistant' AND current_revision_id IS NULL AND version = 1)",
    )
    op.create_check_constraint(
        op.f("ck_agents_system_purpose_valid"),
        "agents",
        "system_purpose IS NULL OR (system_purpose = 'configuration_assistant' AND source = 'builtin')",
    )
    op.add_column("runs", sa.Column("configuration_context", sa.JSON(none_as_null=True), nullable=True))
    op.add_column("runs", sa.Column("configuration_draft_id", sa.String(length=72), nullable=True))
    op.alter_column("runs", "agent_revision_id", existing_type=sa.VARCHAR(length=72), nullable=True)
    op.create_foreign_key(
        "fk_runs_configuration_draft_same_session",
        "runs",
        "configuration_drafts",
        ["configuration_draft_id", "organization_id", "session_id"],
        ["id", "organization_id", "session_id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.create_check_constraint(
        op.f("ck_runs_configuration_binding_consistent"),
        "runs",
        "(configuration_draft_id IS NULL AND configuration_context IS NULL AND agent_revision_id IS NOT NULL) OR (configuration_draft_id IS NOT NULL AND configuration_context IS NOT NULL AND agent_revision_id IS NULL)",
    )
    op.add_column("sessions", sa.Column("configuration_owner_user_id", sa.String(length=72), nullable=True))
    op.add_column("sessions", sa.Column("configuration_draft_id", sa.String(length=72), nullable=True))
    op.create_index(
        "ix_sessions_configuration_owner",
        "sessions",
        ["workspace_id", "configuration_owner_user_id", "updated_at", "id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_sessions_configuration_owner_user_id_users"),
        "sessions",
        "users",
        ["configuration_owner_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_sessions_configuration_draft",
        "sessions",
        "configuration_drafts",
        ["configuration_draft_id", "organization_id", "id"],
        ["id", "organization_id", "session_id"],
        ondelete="RESTRICT",
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.create_check_constraint(
        op.f("ck_sessions_configuration_scope_valid"),
        "sessions",
        "(configuration_owner_user_id IS NULL AND configuration_draft_id IS NULL) OR (configuration_owner_user_id IS NOT NULL AND configuration_draft_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse only before protected configuration data exists."""
    connection = op.get_bind()
    if connection.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM configuration_applications) OR EXISTS (SELECT 1 FROM configuration_drafts) "
            "OR EXISTS (SELECT 1 FROM sessions WHERE configuration_owner_user_id IS NOT NULL) "
            "OR EXISTS (SELECT 1 FROM agents WHERE system_purpose IS NOT NULL) "
            "OR EXISTS (SELECT 1 FROM runs WHERE configuration_context IS NOT NULL)"
        )
    ).scalar():
        raise RuntimeError("Cannot downgrade while protected configuration assistant data exists.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_sessions_configuration_scope_valid"), "sessions", type_="check")
    op.drop_constraint("fk_sessions_configuration_draft", "sessions", type_="foreignkey")
    op.drop_constraint(op.f("fk_sessions_configuration_owner_user_id_users"), "sessions", type_="foreignkey")
    op.drop_index("ix_sessions_configuration_owner", table_name="sessions")
    op.drop_column("sessions", "configuration_draft_id")
    op.drop_column("sessions", "configuration_owner_user_id")
    op.drop_constraint(op.f("ck_runs_configuration_binding_consistent"), "runs", type_="check")
    op.drop_constraint("fk_runs_configuration_draft_same_session", "runs", type_="foreignkey")
    op.alter_column("runs", "agent_revision_id", existing_type=sa.VARCHAR(length=72), nullable=False)
    op.drop_column("runs", "configuration_draft_id")
    op.drop_column("runs", "configuration_context")
    op.drop_constraint(op.f("ck_agents_system_purpose_valid"), "agents", type_="check")
    op.drop_constraint(op.f("ck_agents_revision_source_valid"), "agents", type_="check")
    op.drop_index("uq_agents_workspace_system_purpose", table_name="agents")
    op.alter_column("agents", "current_revision_id", existing_type=sa.VARCHAR(length=72), nullable=False)
    op.drop_column("agents", "system_purpose")
    op.drop_index("ix_configuration_applications_draft_created", table_name="configuration_applications")
    op.drop_table("configuration_applications")
    op.drop_table("configuration_drafts")
    # ### end Alembic commands ###
