profile: local
replicaCount: 1
image:
  repository: a13n-service
  tag: local
  pullPolicy: Never
publicOrigin: http://127.0.0.1:8080
console:
  image:
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 30080
redis:
  enabled: true
postgresql:
  enabled: true
